### ISSUE TITLE
Armor Models with Rotation

### ISSUE THREAD

**Issue by Tschipp** [Tschipp/CarryOn#1]
Armor Models need to correctly show their arm rotation when a Tile is held.

**Comment by capnkirok** [comment]
In third person :)

**Comment by ColaLiao** [comment]
#183 ，But i install both LLibrary and Obfuscate already...

i think maybe i give more detail, so you can fix it easier.
or this mod is no longer update with 1.12.2 ?

**Comment by sepsol** [comment]
> 
> 
> This issue is fixed if Carry On is used together with Obfuscate.

This is how it looks like with Obfuscate mod when normally standing:
![image](https://user-images.githubusercontent.com/47871887/68072589-af57c080-fd9c-11e9-891e-4eb24762a120.png)
![image](https://user-images.githubusercontent.com/47871887/68072595-b979bf00-fd9c-11e9-9b17-81fdb1f4c9d8.png)

And this is how it looks like when going prone:
![image](https://user-images.githubusercontent.com/47871887/68072618-e5954000-fd9c-11e9-96ae-6851b16853e0.png)
![Uploading image.png…]()

This time both the paperdoll and 3D view have bugs! More on my issue at #206

**Comment by sepsol** [comment]
**note that it's not actually holding the chest even in 3pp**

**Comment by Tschipp** [comment]
This is now fixed with the rewrite (2.0.0)
