### ISSUE TITLE
Droppers and Dispensers are a problem and not sure why.

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [Tschipp/CarryOn#10]
I have a few mods also in play but none I couldn't see how any of them would modify droppers and dispensers in any way but using Carry On on droppers and dispensers causes me to pick up a block with a broken texture and when I place it down, the game crashes.

mod version: CarryOn MC1.11.2 v1.1.1

Note: Adding the dispenser and dropper in the blacklist doesn't prevent me from picking them up either.

https://pastebin.com/rYKFp4kj

**Comment by Tschipp** [comment]
Can you send me your config file?

**Comment by capnkirok** [comment]
Your icon looks like an Inventory Pet :)

**Comment by TheGuyFromTheInternet** [comment]
# Configuration file

general {

    ##########################################################################################################
    # settings
    #--------------------------------------------------------------------------------------------------------#
    # General Mod Settings
    ##########################################################################################################

    settings {
        # If the front of the Tile Entities should face the player or should face outward
        B:facePlayer=false

        # More complex Tile Entities slow down the player more
        B:heavyTiles=true

        # Maximum distance from where Blocks can be picked up
        D:maxDistance=2.5

        # Allow all blocks to be picked up, not just Tile Entites
        B:pickupAllBlocks=false
    }

    ##########################################################################################################
    # forbiddentiles
    #--------------------------------------------------------------------------------------------------------#
    # Tile Entities that the Player is not allowed to pick up
    ##########################################################################################################

    forbiddentiles {
        # Tile Entities that cannot be picked up
        S:forbiddenTiles <
            minecraft:end_portal
            minecraft:end_gateway
            minecraft:double_plant
            minecraft:bed
            minecraft:dropper
            minecraft:dispenser
            animania:block_trough
            animania:block_invisiblock
            colossalchests:*
            ic2:*
            bigreactors:*
            forestry:*
            tconstruct:*
            immersiveengineering:*
            embers:block_furnace
            embers:ember_bore
            embers:ember_activator
            embers:mixer
            embers:heat_coil
            embers:large_tank
            embers:crystal_cell
            embers:alchemy_pedestal
            embers:boiler
            embers:combustor
            embers:catalzyer
            embers:field_chart
            embers:inferno_forge
            storagedrawers:framingtable
         >
    }

    ##########################################################################################################
    # modeloverrides
    #--------------------------------------------------------------------------------------------------------#
    # Model Overrides based on NBT or on Meta. Advanced Users Only!
    ##########################################################################################################

    modeloverrides {
        # Model Overrides based on NBT or on Meta. Advanced Users Only!
        S:modelOverrides <
            minecraft:lit_furnace->minecraft:furnace
            minecraft:bed->minecraft:bed
            quark:custom_chest{type:"spruce"}->quark:custom_chest;0
            quark:custom_chest{type:"birch"}->quark:custom_chest;1
            quark:custom_chest{type:"jungle"}->quark:custom_chest;2
            quark:custom_chest{type:"acacia"}->quark:custom_chest;3
            quark:custom_chest{type:"dark_oak"}->quark:custom_chest;4
            quark:custom_chest_trap{type:"spruce"}->quark:custom_chest_trap;0
            quark:custom_chest_trap{type:"birch"}->quark:custom_chest_trap;1
            quark:custom_chest_trap{type:"jungle"}->quark:custom_chest_trap;2
            quark:custom_chest_trap{type:"acacia"}->quark:custom_chest_trap;3
            quark:custom_chest_trap{type:"dark_oak"}->quark:custom_chest_trap;4
            storagedrawers:basicdrawers;0{Mat:"spruce"}->storagedrawers:basicdrawers;0{material:"spruce"}
            storagedrawers:basicdrawers;0{Mat:"birch"}->storagedrawers:basicdrawers;0{material:"birch"}
            storagedrawers:basicdrawers;0{Mat:"jungle"}->storagedrawers:basicdrawers;0{material:"jungle"}
            storagedrawers:basicdrawers;0{Mat:"acacia"}->storagedrawers:basicdrawers;0{material:"acacia"}
            storagedrawers:basicdrawers;0{Mat:"dark_oak"}->storagedrawers:basicdrawers;0{material:"dark_oak"}
            storagedrawers:basicdrawers;1{Mat:"spruce"}->storagedrawers:basicdrawers;1{material:"spruce"}
            storagedrawers:basicdrawers;1{Mat:"birch"}->storagedrawers:basicdrawers;1{material:"birch"}
            storagedrawers:basicdrawers;1{Mat:"jungle"}->storagedrawers:basicdrawers;1{material:"jungle"}
            storagedrawers:basicdrawers;1{Mat:"acacia"}->storagedrawers:basicdrawers;1{material:"acacia"}
            storagedrawers:basicdrawers;1{Mat:"dark_oak"}->storagedrawers:basicdrawers;1{material:"dark_oak"}
            storagedrawers:basicdrawers;2{Mat:"spruce"}->storagedrawers:basicdrawers;2{material:"spruce"}
            storagedrawers:basicdrawers;2{Mat:"birch"}->storagedrawers:basicdrawers;2{material:"birch"}
            storagedrawers:basicdrawers;2{Mat:"jungle"}->storagedrawers:basicdrawers;2{material:"jungle"}
            storagedrawers:basicdrawers;2{Mat:"acacia"}->storagedrawers:basicdrawers;2{material:"acacia"}
            storagedrawers:basicdrawers;2{Mat:"dark_oak"}->storagedrawers:basicdrawers;2{material:"dark_oak"}
            storagedrawers:basicdrawers;3{Mat:"spruce"}->storagedrawers:basicdrawers;3{material:"spruce"}
            storagedrawers:basicdrawers;3{Mat:"birch"}->storagedrawers:basicdrawers;3{material:"birch"}
            storagedrawers:basicdrawers;3{Mat:"jungle"}->storagedrawers:basicdrawers;3{material:"jungle"}
            storagedrawers:basicdrawers;3{Mat:"acacia"}->storagedrawers:basicdrawers;3{material:"acacia"}
            storagedrawers:basicdrawers;3{Mat:"dark_oak"}->storagedrawers:basicdrawers;3{material:"dark_oak"}
            storagedrawers:basicdrawers;4{Mat:"spruce"}->storagedrawers:basicdrawers;4{material:"spruce"}
            storagedrawers:basicdrawers;4{Mat:"birch"}->storagedrawers:basicdrawers;4{material:"birch"}
            storagedrawers:basicdrawers;4{Mat:"jungle"}->storagedrawers:basicdrawers;4{material:"jungle"}
            storagedrawers:basicdrawers;4{Mat:"acacia"}->storagedrawers:basicdrawers;4{material:"acacia"}
            storagedrawers:basicdrawers;4{Mat:"dark_oak"}->storagedrawers:basicdrawers;4{material:"dark_oak"}
         >
    }

}

**Comment by TheGuyFromTheInternet** [comment]
Did some more testing, it turns out it may have to do with the [RedstonePlusPlus](https://minecraft.curseforge.com/projects/redstoneplusplus) mod since it does modify how the dropper and dispenser behave. What's more is that it makes the crafting table into a tile entity. I tried to pick up the crafting table and the result was the same: broken textures when at hand and crashes the game when you try placing the block down.

**Comment by Tschipp** [comment]
try disabling all of redstoneplus' blocks (modid:*)

**Comment by TheGuyFromTheInternet** [comment]
disabling the blocks in the config doesn't work. For some reason, it doesn't respect the config. :(

**Comment by capnkirok** [comment]
@Tschipp I think the blocks that have the problem are vanilla. Blocking the mod won't change that. Their may be a new property on the Tile Entity we can look at.

**Comment by Tschipp** [comment]
Fixed. Gonna be in the next release or in the next hotfix if we make one (probably not)
