### ISSUE TITLE
Duplication Bug when interacting with modded blocks.

### ISSUE THREAD

**Issue by Xules01** [Tschipp/CarryOn#102]
### Expected Behavior
Pick up object with inventory and place it back down.

### Actual Behavior
Object is picked up, but all of it's contents are duplicated and dropped on the floor.

### Steps to Reproduce
Happens every time so far.    

It occurs with 
Storage Drawers -  Contents, including drawer upgrades are duplicated.
Bibliocraft objects, like bookcases. shelves, chests, etc...
Electroblob's Wizardy - arcane workbench duplicates items in it's inventory if picked up.
Thaumcraft - duplicates items stored in Thaumcraft blocks, such as arcane workbench vis crystals. Essentia smeltery duplicates stored inventory.

Seems to work fine with IronChests mod and Thermal Expansion machines.

### Version of Minecraft, Carry On, Forge
forge-1.12.2-14.23.3.2680-universal
CarryOn+MC1.12.2+v1.9

### Screenshots encouraged
![2018-05-11_14 59 08](https://user-images.githubusercontent.com/7582362/39944687-2c63abee-552d-11e8-9797-4d24e7c936af.png)
![2018-05-11_14 59 41](https://user-images.githubusercontent.com/7582362/39944696-374c12da-552d-11e8-921b-f00e40134fc2.png)
![2018-05-11_15 01 32](https://user-images.githubusercontent.com/7582362/39944705-427ad89e-552d-11e8-9d8d-cabb97ebd395.png)
![2018-05-11_15 01 44](https://user-images.githubusercontent.com/7582362/39944707-44412214-552d-11e8-9023-650d7f89db6a.png)

**Comment by Tschipp** [comment]
Damn, I should have done more thorough testing... will have hotfix tomorrow, probably

**Comment by Tschipp** [comment]
Edit: I got a fix out today anyway... please check it out and report back if it works.

**Comment by Xules01** [comment]
Tested the new build and it works great!  Thank you.

**Comment by Tschipp** [comment]
Glad to hear!
