### ISSUE TITLE
[1.12.2] Gravestone duplication 

### ISSUE THREAD

**Issue by BuilderDan** [Tschipp/CarryOn#103]
### Expected Behavior
Picked upgravestone and it duplicated 

### Steps to Reproduce
Play on a server with this mod:https://minecraft.curseforge.com/projects/gravestone-mod?gameCategorySlug=mc-mods&projectID=238551

Whenever you pickup a gravestone and place it down it dupes the items within it...

Pickup a gravestone after death

### Version of Minecraft, Carry On, Forge
Forge: forge-1.12.2-14.23.3.2655-universal.jar
Carryon: CarryOn+MC1.12.2+v1.9.jar

**Comment by Tschipp** [comment]
Really? It works with my build of the latest. Please mind that I had to take down 1.9 when it had like 80 downloads on 1.12... so if you were one of those people, try re-downloading the mod.

**Comment by BuilderDan** [comment]
I believe its fixed, I'll update you if anything changes

**Comment by Tschipp** [comment]
I'm closing this for now
