### ISSUE TITLE
OpenComputers robot crash

### ISSUE THREAD

**Issue by Antyrox** [Tschipp/CarryOn#104]
### Expected Behavior
I tryed to carry opencomputers robot.

### Actual Behavior
I picked up opencomputers robot without any problems, but when i placed it back into the world my game crashed and my world file got corrupted. Here is link to [crash report](https://paste.dimdev.org/qivucowise.txt).

### Steps to Reproduce
1) Create opencomputers robot and put it somewhere. Pick it up and place it anywhere.

 ### Version of Minecraft, Carry On, Forge
All versions listed in crash file

**Comment by Tschipp** [comment]
Thank you for the report! Please blacklist OpenComputers in your pack, I will add it to the default blacklist.
