### ISSUE TITLE
[Request] Game Stages 2.0.90 compatibility

### ISSUE THREAD

**Issue by Fireztonez** [Tschipp/CarryOn#105]
Hello,
I want to know if you can update The GameStages support, to support the new version (v.2.0.90).

I don't think you need more information than that, but if you have any question, I will try to reply!

Karl

**Comment by Tschipp** [comment]
I will, but I’m gonna wait until 2.0 is no longer considered experimental

**Comment by Fireztonez** [comment]
Game Stages 2.0.91 is now available in release for about a month now... Are you able to update CarryOn soon, to be able to use in my modpack CarryOn, becose I can't use the old version of GameStages, So much mods in my modpack need the new version to work and you mod is the only good one I know to transport easily things, so I really want to be able to use.

Thank's for your great work!

**Comment by Tschipp** [comment]
Sorry for the long delay, I am pushing out an update soon
