### ISSUE TITLE
Torcherino

### ISSUE THREAD

**Issue by NinjaPhenix** [Tschipp/CarryOn#108]
Torcherino uses shift right click to change the speed of the torcherino which conflicts with the default key bind, could you add tocherino blocks to the default blacklist(they can be instantly broken).
ModID: torcherino

**Comment by Tschipp** [comment]
If it conflicts with the keybind, you can change the keybind or blacklist it, as you said. I usually only add blocks to the default blacklist that have game-breaking behavior.

**Comment by NinjaPhenix** [comment]
This didnt happen before but yes its very hacky code and is now removed in the [latest commit](https://github.com/NinjaPhenix/Torcherino/commit/c2eaa7b39344b0ca2c1cbde64cffbd0b6db5982e), torcherino version 7.5

**Comment by Tschipp** [comment]
Ok great, thanks
