### ISSUE TITLE
Trouble with Rustic crushing tub and brewing barrels.

### ISSUE THREAD

**Issue by swestrup** [Tschipp/CarryOn#109]
### Expected Behavior
Expect to pick up item and contents with shift-right-click.

### Actual Behavior
CarryOn produces an error message, and the contents of the crushing tub or brewing barrel is erased.

### Steps to Reproduce
1) Put down a crushing tub or a brewing barrel from the Rustic Mod
2) Crush a few apples in the crushing tub (by jumping on them), or add a bucket of apple juice to the brewing barrel.
3) Attempt to shift-right-click pick-up the item.

### Version of Minecraft, Carry On, Forge
This is happening inside the SevTech 3.0.6 modpack, so there could be multiple interactions.
Minecraft: 1.12.2
CarryOn: 1.8
Forge: 8.0.99.99

**Comment by Tschipp** [comment]
This bug was (probably) fixed in the latest version. Either update yourself or wait on Darkosto to release an update.

**Comment by Tschipp** [comment]
Going to close this now. Feel free to comment if it should be reopened
