### ISSUE TITLE
Configurable pick up distance

### ISSUE THREAD

**Issue by mser7** [Tschipp/CarryOn#110]
### Expected Behavior
Put in a different value and have the distance changing to match that value

### Actual Behavior
Can't modify the pick up distance, the config automatically reset everytime.
# Maximum distance from where Blocks and Entities can be picked up
        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:maxDistance=2.5

### Version of Minecraft, Carry On, Forge
CarryOn+MC1.12.2+v1.9
Forge 14.23.4.2703

**Comment by Tschipp** [comment]
It works on my machine

**Comment by mser7** [comment]
Here, I made a gif showing you my problem
https://imgur.com/2o8Cvn8

**Comment by Tschipp** [comment]
You need to actually change the config value and not the Min/Max bounds value. The value you need to edit is below the Max-Bounds value.

**Comment by mser7** [comment]
Got it to work thanks.
