### ISSUE TITLE
Game always crash when carry mobs and enter to another dimenstion in 1.10.2

### ISSUE THREAD

**Issue by Ihaveaquestionforyou** [Tschipp/CarryOn#113]
### Expected Behavior
Game acting normally as I pick up my girl that come from shincolle mod and enter nether, supposed to create nether world because it my first time to enter nether in this world

### Actual Behavior
It crashed no matter how much effort I put on it. I try to delete some data of my saves because I hope it back to the time when I didn't enter the nether

### Steps to Reproduce
carry shincollection friendly mob and enter the nether

### Version of Minecraft, Carry On, Forge
1.10.2, latest forge by the time I post this, shin colle demand a forge that is very high

### Screenshots encouraged
crashed instantly, I don't have a chance to take it

**Comment by Tschipp** [comment]
Not able to recreate.

**Comment by Ihaveaquestionforyou** [comment]
Let me see if I can provide a crash log

Tschipp <notifications@github.com>于2018年7月6日 周五上午9:49写道：

**Comment by Ihaveaquestionforyou** [comment]
​
 crash-2018-06-13_05.27.49-server.txt
<https://drive.google.com/file/d/12edfaEDyNiUtrTwP7Wc-q49gEILlpRSf/view?usp=drive_web>
​​
 crash-2018-06-13_05.54.26-server.txt
<https://drive.google.com/file/d/1-zzq9ZC9vuQPIjmHAUMIJkOTKhQQQ3QZ/view?usp=drive_web>
​​
 crash-2018-06-13_05.39.15-server.txt
<https://drive.google.com/file/d/1UO9N0rSXEWr1HHeZnqFh1Q0zEZ_7YsSO/view?usp=drive_web>
​​
 crash-2018-06-13_06.00.08-server.txt
<https://drive.google.com/file/d/1wmY0wIzIWNS1WjZPJOhgkqLCdp6WWvG1/view?usp=drive_web>
​​
 crash-2018-06-13_05.29.40-server.txt
<https://drive.google.com/file/d/1M6M_9lDFe0cVkYN0cdPmBkM-gUcB5G-1/view?usp=drive_web>
​​
 crash-2018-06-13_05.42.10-server.txt
<https://drive.google.com/file/d/1SghMUmJqKJW4hA3vrGiK5AoXJfa8N3Qa/view?usp=drive_web>
​​
 crash-2018-06-13_04.47.33-server.txt
<https://drive.google.com/file/d/1gCMbNRS609MtyrFopBNKVIQCCuAiScaQ/view?usp=drive_web>
​​
 crash-2018-06-13_05.50.31-server.txt
<https://drive.google.com/file/d/1blDXa-tPm3NrjgZApKWL3eXTuQrvl-I9/view?usp=drive_web>
​​
 crash-2018-06-13_05.34.03-server.txt
<https://drive.google.com/file/d/1F8gVbXnDfzj-vLu88Rzpic2vTSeKQ8a-/view?usp=drive_web>
​As you can see, I tried many way to fix this problem. Such as remove mods,
change config, delete data, and also change the data inside the save file,
and it still not working.

**Comment by Ihaveaquestionforyou** [comment]
Well.... Since the crush was happened in the nether postal, I didn't ever
think about anything about grave mod.
I delete my game since that world was crashed and everything I did will
never come back

Tschipp <notifications@github.com>于2018年7月6日 周五上午10:26写道：

**Comment by Ihaveaquestionforyou** [comment]
If you want I can give you my saves file

**Comment by Tschipp** [comment]
No, but please try removing Graves

**Comment by Ihaveaquestionforyou** [comment]
Ok, just give me some time to let me do this and I will tell you the result

Tschipp <notifications@github.com>于2018年7月6日 周五下午3:33写道：

**Comment by Ihaveaquestionforyou** [comment]
Good news and bad news
It working normally, but not that normal, at least nether portal and mob
that I carried was gone, can't make sure whether is it normal thing, I am
very appreciate though.

油腻腻的汉堡包汉堡薯条麦当劳 <m7120520@gmail.com>于2018年7月6日 周五下午3:37写道：
