### ISSUE TITLE
Interaction issue with Industrial Foregoing

### ISSUE THREAD

**Issue by 2ndkirbyever** [Tschipp/CarryOn#116]
I already reported this to Industrial Foregoing's repo, but they said they did not support Carry On.
I used Carry On to move a material stonework factory. After placing it back down, it started using max int FE/tick. I don't know if the other machines in this mod are affected or not.

### Expected Behavior
The factory only uses 40 FE/tick after being placed back down.

### Actual Behavior
The factory consumes all of the power in my system.

### Steps to Reproduce

1. Place a material stonework factory and give it power.
2. Pick it up with Carry On and place it back down.
3. Say au revoir to your power!

### Version of Minecraft, Carry On, Forge
Minecraft 1.12.2
Carry On 1.9
Industrial Foregoing 1.10.2-178
Forge 14.23.4.2725

### Screenshots
Before carrying the stonework factory:
![2018-06-30_09 15 40](https://user-images.githubusercontent.com/16438720/42126249-b329fb94-7c4a-11e8-867d-b0728e2e63a9.png)
After carrying the stonework factory:
![2018-06-30_09 15 50](https://user-images.githubusercontent.com/16438720/42126253-c4736278-7c4a-11e8-9f20-474180534cf2.png)

**Comment by Tschipp** [comment]
If they won't support CarryOn, then I will just add it to the default blacklist
