### ISSUE TITLE
Minecolonies' Hut Blocks

### ISSUE THREAD

**Issue by stefan7080** [Tschipp/CarryOn#117]
### Expected Behavior
Placing back the block results in building working as usual.

### Actual Behavior
Colony ripped and block became resistant to even the most extreme cases of spamclicking in attempts to interact with it. This is most likely caused by data not being stored with nbt tags but in seperate files stored in the world folder.

### Steps to Reproduce
Pick up any block from Minecolonies

### Version of Minecraft, Carry On, Forge
1.12.2 - 1.9 - 14.23.4.12

### Screenshots encouraged
No screenshots since there is nothing to show.

Blacklisting this by default would reduce the chance of this happening to others in the future.

EDIT: Added Carry on and Forge versions

**Comment by Tschipp** [comment]
Yeah, blacklisting seems like the smartest option
