### ISSUE TITLE
GL Error: 1283 - StackOverflow when being hit by an arrow

### ISSUE THREAD

**Issue by Fogrits** [Tschipp/CarryOn#12]
Independent of holding a tileEntity or not, since the mod overrides the player model rendering
PS: The inventory GUI goes blank, until the StackOverflow message appears in the chat box.
PS²: Tested with only CarryOn active
Using latest version (1.12-1.1.1)

**Comment by capnkirok** [comment]
Yeah, we just saw this one yesterday. Thanks for the detail!

**Comment by capnkirok** [comment]
To be clear, this only happens in third person perspective. We will include a temporary fix, which actually prevents arrows from being rendered on the person if they have been shot.
