### ISSUE TITLE
[Suggestion]About carry bedrock

### ISSUE THREAD

**Issue by Tollainmear** [Tschipp/CarryOn#120]
### Expected Behavior
Pick up bedrock on survival mode

### Actual Behavior
could only pick up bedrock on creative mode

### Steps to Reproduce
what ever on blacklist mode on or whitelist mode on, bedrock could only pick up on creative mode

### Version of Minecraft, Carry On, Forge
MC 1.12.2
Forge 2655
CarryOn 1.9.1

Hi, I know that the bedrock was a unbreakable block which shouldn't be carried by players in survival mode, but it is convenient if it could be configurable...... so how about that suggestion? To make bedRock carryable when set `PickUpAllBlocks` option on? It seems like doesn't work now.

BTW, carry a snow layer then place it on another snow layer would replace the target snow layer.

**Comment by toyhippogriff** [comment]
This is easily resolved by creating a script specifying bedrock as carriable.

Create a file called "bedrock.json" in the carryon-scripts folder:

```
{
    "object": {
        "block": {
            "name": "minecraft:bedrock"
        }
    }, "conditions": {
        "gamemode": ">=0"
    }
}

**Comment by Tollainmear** [comment]
Thanks a lot :P

**Comment by Tschipp** [comment]
Also be sure to enable scripts in the config
