### ISSUE TITLE
Villagers take damage when picked up.

### ISSUE THREAD

**Issue by toyhippogriff** [Tschipp/CarryOn#121]
### Expected Behavior
Villagers should be picked up like any other entity, without taking damage.

### Actual Behavior
They take what appears to be suffocation damage upon being carried.

Edit: It would appear that cows are suffering from the same issue.

### Steps to Reproduce
1). Add a script allowing villagers to be carried.
2). Attempt to carry a villager.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Forge: 14.23.4.2703
Carry On: 1.9.1

### Screenshots encouraged
![2018-07-15_17 08 12](https://user-images.githubusercontent.com/41272642/42738942-bcf35350-8852-11e8-8497-740636d96239.png)

**Comment by Tschipp** [comment]
Uh what, that is definitely not an issue caused by carry on alone, as it doesn't happen in a fresh install. Is the entity actually taking damage, or just appearing to take damage?

**Comment by toyhippogriff** [comment]
It would appear that it only _looks like_ the villager takes damage. My mistake.
