### ISSUE TITLE
Carrying RS Drive voids drives

### ISSUE THREAD

**Issue by andr9528** [Tschipp/CarryOn#127]
### Expected Behavior
To be able to move Refined Storage Drive, by picking it up with this mod and placing it down elsewhere, keeping the drives inside.

### Actual Behavior
Moving Refined Storage Drive, by picking it up with this mod and placing it down elsewhere, voiding all content of the drive

### Steps to Reproduce
1. Have Refined Storage and Carry On installed
2. Place down Refined Storage Drive
3. Put in drives to the newly placed Drive
4. Pick up the Drive
5. Set down the drive
6. ...
7. Negative Profit!

### Version of Minecraft, Carry On, Forge
Minecraft --> 1.12.2
Carry On --> Version 1.9.3
Forge --> 14.23.4.2747
Refined Storage --> Version 1.6.3

**Comment by Tschipp** [comment]
This is strange... had this bug a while ago, thought it was finally fixed...
