### ISSUE TITLE
Picked up Wearable Backpack shows up as Air

### ISSUE THREAD

**Issue by Lordician** [Tschipp/CarryOn#13]
Hi there, first of all, amazing mod so far, great work!
Buuuut i come with an issue with another mod, not sure if this is due to how that mod works or how your mod works, but i figured i would try it here first.
The issue is with the Wearable Backpack mod where if i put a backpack down and try to pick it up, i carry around a block of air.
When i place the thing i am carrying however, it places the backpack down as expected, it is just a visual thing apparently.
Mod versions:
CarryOn MC1.11.2 v1.1.1
WearableBackpacks-1.11.2-2.3.2

It is just something small as it seems to work still, but having a pink texture missing block in your face is not so good for my poor eyes. :P

**Comment by capnkirok** [comment]
Yeah, this is due to CarryOn. We're going to have to find a better way to render the arms. Thanks for the note and the kind words :)

**Comment by Tschipp** [comment]
Wait... are you carrying the backpack with your hands or on your back?

**Comment by Lordician** [comment]
I am trying to pick up (and thus carry the backpack) with my hands.
There is nothing on my back, putting it on my back is done by shift-breaking it.

**Comment by capnkirok** [comment]
Oh, I see. Looks like another invisible texture.

**Comment by Tschipp** [comment]
You could try setting a custom override model, check the wiki for details

**Comment by Jomik** [comment]
I have overridden with a custom model, it "works"...
https://i.gyazo.com/85e130b8066a12ac31e3fce3596b7324.gif

However, the top part of the model is gone.

`wearablebackpacks:backpack->(block)wearablebackpacks:backpack`

**Comment by Tschipp** [comment]
cool, I'll close this!

**Comment by Jomik** [comment]
Well, if the "half" model isn't on your end. It does seem like some metadata is lost when overriding the model (obviously), as the backpack is brown, but turns white.
