### ISSUE TITLE
Carry On Crash With Ender Tank add by EnderStorage

### ISSUE THREAD

**Issue by AssassinsGBr** [Tschipp/CarryOn#131]
### Expected Behavior
Works with the other blocks add by this mod

### Actual Behavior
Everytime that I pick up an Ender Tank, he becomes an Ender Chest in my hands. And when a trie to place the block, crashes.

### Steps to Reproduce
Install EnderStorage and Carry On, trie to pick up an Ender Tank, and place the block

### Version of Minecraft, Carry On, Forge
Forge: 1.12.2-14.23.4.2759
Carry On: 1.12.2 v1.10
EnderStorage: 1.12.2-2.4.5.135-universal

**Comment by DaveJK** [comment]
I have this same problem while playing Enigmatica 2 Expert, but I am unsure if the tank turns into a chest before I tried placing it down. I have been unable to log back into the world again.

[Pastebin](https://pastebin.com/uvWwECJH)

Forge: 1.12.2-14.23.4.2751
Carry On: 1.12.2 v1.10
Ender Storage: 1.12.2-2.4.5.135-universal
