### ISSUE TITLE
Carrying a IronFurnaces's Gold furnace stucks the burn indicator

### ISSUE THREAD

**Issue by vpontin** [Tschipp/CarryOn#132]
### Expected Behavior
When carrying @XenoMustache [IronFurnaces](https://minecraft.curseforge.com/projects/iron-furnaces) ([GH repo](https://github.com/XenoMustache/ironfurnaces))'s gold furnace, it is expected to pause the burn indicator while carrrying, and then when the player place the block back on the ground the indicator resume decreasing.

### Actual Behavior
When carrying the gold furnace and placing it back the indicator became stuck on the level it had when picking the block, and never decreses until the player propely breaks the block.

### Steps to Reproduce

- Place a golden furnace;
- Put a lava bucket on it;
- Put something to burn;
- When it start burning carry the furnace;
- Place it back on the ground.
- Even removing the fuel the furnace is stuck on the level it had when pick up. 

### Version of Minecraft, Carry On, Forge

- Minecraft 1.12.2
- Forge 14.23.4.2760
- CarryOn 1.10
- IronFurnaces 1.3.1

### Screenshots encouraged
I think screenshots could not show propely the effect.

**Comment by Tschipp** [comment]
[Works as intended](https://i.gyazo.com/e55df9008be3bba9a3731a86ee2756af.gif), even when reproducing the exact steps that you listed.

**Comment by vpontin** [comment]
I began to think i mistaken things: The issue is @XenoMustache's Gold Furnace become stuck when using lava buckets, i got a similar one after i think the chunk where the furnace were unloaded.


Anyway closing the issue since it seems to be not a CarryOn problem.
