### ISSUE TITLE
incompatibility with protection plugins

### ISSUE THREAD

**Issue by Azvalk** [Tschipp/CarryOn#133]
### Expected Behavior

In a protected area, we can expect that flags such as "place"," destroy", "chest", could have effect on Carry On possibilities..

### Actual Behavior

It seems that Carry On totally ignore protection plugins like Universe Guard.
(main plugin of protection for sponge servers )
And.. it's a sad problem for a server..

### Steps to Reproduce

make a region with Universe Guard
/rg, select two corner
/rg name test
/rg flag flag place false
/rg flag flag destroy false
/rg save

(/rg edit test, when you want to edit the flags )

Put some tile entities, chest, chairs coming from other mods, furnaces..ect..
Try '-'
You will see a beautiful chest duplication that takes away the contents of the chest..

### Version of Minecraft, Carry On, Forge
1.12.2
Forge 2705
Carry On MC1.12.2 v1.10
UniverseGuard-2.15-1.12.2

**Comment by Tschipp** [comment]
Carry on fires a BlockEvent.BreakEvent before pickiung up blocks and an AttackEntityEvent when picking up entities. If the event is canceled, The block/entity is not picked up. This form of protection works for FTBUtils and other protection mods.

**Comment by Tschipp** [comment]
Is this still an issue?

**Comment by Tschipp** [comment]
Going to close this. Feel free to reopen if this is still an issue.
