### ISSUE TITLE
BetterStorageToo multiblock crates breaking when moved with CarryOn

### ISSUE THREAD

**Issue by TehStoneMan** [Tschipp/CarryOn#135]
### Expected Behavior
Crates remain in place.

### Actual Behavior
Crate functions broken, ghost blocks left in place.

### Steps to Reproduce
Build a crate and move it.

### Version of Minecraft, Carry On, Forge
Forge: 1.12.2-14.23.4.2758
Carry On: 1.12.2 v1.10
BetterStorageToo: 1.12.2-3.0.0.2

**Comment by Tschipp** [comment]
Multiblocks aren’t supported
