### ISSUE TITLE
The Unmoved Chest In A Double Chest Loses Its Contents When The Other Is Moved

### ISSUE THREAD

**Issue by EmosewaPixel** [Tschipp/CarryOn#136]
### Expected Behavior
 When one Chest that's a part of a double Chest, the other one should keep its contents.

### Actual Behavior
 When one Chest that's a part of a double Chest gets moved, the other one loses its contents.

### Steps to Reproduce
1. Put 2 Chests together
2. Put items in them to they both have something
3. Move one of them
4. The other one will now be empty

### Version of Minecraft, Carry On, Forge
1.12.2
1.11 (it does not happen on previous versions)
14.23.5.2768

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/25333164/46531701-73eb7980-c89e-11e8-86be-4729aada5d01.png)
![image](https://user-images.githubusercontent.com/25333164/46531697-6df59880-c89e-11e8-8c51-ee69ba163aac.png)
![image](https://user-images.githubusercontent.com/25333164/46531715-7ea60e80-c89e-11e8-86d9-c2edd8e7c23b.png)
![image](https://user-images.githubusercontent.com/25333164/46531719-82399580-c89e-11e8-9504-fa624ef62f15.png)
![image](https://user-images.githubusercontent.com/25333164/46531722-85348600-c89e-11e8-86b3-524a44a023a6.png)

**Comment by Tschipp** [comment]
Ouch, that's a bad one. Releasing hotfix later.

**Comment by Tschipp** [comment]
Hotfix is out (as soon as curse approves it)
