### ISSUE TITLE
Arms bug

### ISSUE THREAD

**Issue by agentwolf88** [Tschipp/CarryOn#137]
https://imgur.com/a/8DEqYp5

**Comment by Tschipp** [comment]
please post modlist.

**Comment by agentwolf88** [comment]
Mods:
  ActuallyAdditions-1.12.2-r141
  Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.5.0)
  AdvancedRocketry-1.12.2-1.4.1-104-universal
  animania-1.12.2-1.5.1.1
  AppleCore-mc1.12.2-3.1.4
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-1
  Aquaculture-1.12.2-1.6.6
  architecturecraft-1.12-3.80
  auroragsi-0.2.0
  AutomatedRedstone-1.12.2-6.1.3
  AutoRegLib-1.3-20
  autothirdperson-1.1.0
  Better-Railroads-1.0.0
  BetterFoliage-MC1.12-2.1.10
  BetterFps-1.4.8
  betterunderground-1.1.6
  BiblioCraft[v2.4.5][MC1.12.2]
  BiomesOPlenty-1.12.2-7.0.1.2402-universal
  buildcraft-7.99.17
  CameraObscura-1.0.3
  CarryOn+MC1.12.2+v1.11.1
  CD4017BE_lib-1.12.2-6.2.4
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.25
  CodeChickenLib-1.12.2-3.2.2.353-universal
  coherent_villages_beta_v1.4.8
  CommonCapabilities-1.12-1.4.0
  composter-1.12.2-1.9.2
  CookingForBlockheads_1.12.2-6.4.65
  CraftStudio-1.0.0.93-mc1.12-alpha
  CreativeCore_v1.9.35_mc1.12.2
  CTM-MC1.12.2-0.3.2.18
  CustomMobSpawner-3.11.4
  CustomNPCs_1.12.2(08jul18)
  CyclopsCore-1.12.2-0.11.5
  Decocraft-2.6.2_1.12.2
  device-mod-0.4.1-1.12.2
  DrZharks MoCreatures Mod-12.0.5
  DynamicSurroundings-1.12.2-3.4.9.16
  DynamicTrees-1.12.2-0.8.2
  DynamicTreesBOP-1.12.2-1.3.2
  EmptyHand-1.12.2-0.1.1-2
  EnderCore-1.12.2-0.5.41
  EnderIO-1.12.2-5.0.35
  Enhanced+Selection+Bounding+Box-1.0.1.1
  Erebus-1.0.23
  exnihilocreatio-1.12-0.3.2
  Exotic+Birds+1.12.2-2.1.0
  ExtraBitManipulation-1.12.2-3.3.1
  extrautils2-1.12-1.9.4
  FarmingForBlockheads_1.12.2-3.1.26
  Farseek-1.12-2.3.1
  forestry_1.12.2-5.8.1.349
  Forgelin-1.7.4
  furniture-5.13.0-1.12.2
  Guidebook-1.12.2-2.8.3
  HardcoreDarkness-MC1.12.2-2.0
  HungerInPeace-mc1.12-1.0.0
  HungerOverhaul-1.12.2-1.3.3.jenkins148
  Hwyla-1.8.26-B41_1.12.2
  IGCM_v1.2.3_mc1.12.2
  IGI-ToughAsNails-1.3_de
  IGISereneSeasons
  ImmersiveEngineering-0.12-85
  industrialcraft-2-2.8.100-ex112
  InGameInfoXML-1.12.2-2.8.2.94-universal
  IntegratedDynamics-1.12.2-0.11.11
  inventorypets-1.12-1.5.3.1
  IronBackpacks-1.12.2-3.0.8-12
  JEHC-1.12.2-1.6.1.0
  jei_1.12.2-4.13.1.220
  journeymap-1.12.2-5.5.2
  JurassiCraft-1.12.2-2.1.17
  JustAFewFish-1.7_for_1.12
  LibEx-1.12.2-1.0.8
  LibVulpes-1.12.2-0.2.8-39-universal
  lightswitch-1.1.1-mc1.12.2
  LittleTiles_v1.5.0-pre111_mc1.12.2
  llibrary-1.7.15-1.12.2
  LunatriusCore-1.12.2-1.2.0.42-universal
  malisiscore-1.12.2-6.4.0
  malisisdoors-1.12.2-7.3.0
  Mantle-1.12-1.3.1.21
  MCJoypad-Mod-1.12.2
  mcjtylib-1.12-3.0.5
  moarboats-1.12.2-3.0.0.2
  moon-core+7.0+(1.12)
  Mr_Crayfish_Vehicle_Spawner_1.2
  multihotbar-1.12.2-4.1-build-T122
  multihotbarcore-1.12.2-1.0.1-build-T22
  NetherEx-1.12.2-2.0.8
  NotEnoughIDs-1.5.4.2
  notenoughwands-1.12-1.7.1
  obfuscate-0.2.5-1.12.2
  OfflineSkins-1.12.2-v4
  OpticManager+v1.1.5+mc1.12.2
  OptiFine_1.12.2_HD_U_E2
  Pam's+HarvestCraft+1.12.2z
  pamscookables-1.1
  PTRLib-1.0.3
  Quark-r1.5-130
  RailRoads-1.1.1
  railsplus-1.1.0
  randomtweaks-1.12.2-2.1.7.0
  realserene-1.3
  RedstoneFlux-1.12-2.0.2.3-universal
  scenter-1.12.2-3.12.0
  Schematics-1.12.2.12
  SereneSeasons-1.12.2-1.2.6-universal
  ServerPropertiesLAN-2.65
  ShadowMC-1.12-3.8.0
  Signals-1.12.2-1.3.12-23-universal
  signpost-1.12-1.07.2
  SilentLib-1.12.2-3.0.6-154
  SimpleDivingGear-1.0.2+mc+1.12.2
  SoundFilters-0.10_for_1.12
  StorageBoats-3.3
  StorageDrawers-1.12.2-5.3.7
  Streams-1.12-0.4.4
  subh2o-1.12.2-1.5.6
  tanspit-1.12.2-1.3
  TConstruct-1.12.2-2.10.1.84
  TheBetweenlands-3.3.12-universal
  thutcore-1.12.2-5.19.8
  thuttech-1.12.2-6.1.5
  TinkerToolLeveling-1.12-1.0.3
  tombstone-3.1.2-1.12
  ToughAsNails-1.12.2-3.1.0.129-universal
  twilightforest-1.12.2-3.8.689-universal
  VanillaFix-1.0.9-97
  vehicle-mod-0.26.0-1.12.2
  WailaHarvestability-mc1.12-1.1.12
  Waystones_1.12.2-4.0.67
  wings-1.0.6-1.12.2
  wumpleutil-1.12.2-2.12.6

**Comment by Tschipp** [comment]
There's a conflict with obfuscate

**Comment by agentwolf88** [comment]
ok, thx
