### ISSUE TITLE
CLient crash while picking up Mo' Creature animal

### ISSUE THREAD

**Issue by lebanni** [Tschipp/CarryOn#138]
Versions :
forge-1.12.2-14.23.4.2765
CarryOn+MC1.12.2+v1.11.1
DrZharks MoCreatures Mod-12.0.5

[crash-2018-10-10_19.58.27-client.txt](https://github.com/Tschipp/CarryOn/files/2465993/crash-2018-10-10_19.58.27-client.txt)

**Comment by Tschipp** [comment]
I swear I thought I fixed this last week... were you playing on a server?

**Comment by lebanni** [comment]
Yes, it's a private server.

**Comment by Tschipp** [comment]
Nope, this works for me with the latest release, even on a server. Which animal specifically were you trying to pick up? Was it tamed or not?

**Comment by lebanni** [comment]
It was a tamed snake. But nevermind, I found out that Mo' Creature was overwhelming my server (TPS dropping to 3). Custom Mob Spawner is a pain in the ass to configure. So I removed it. Feel free to close this issue if you want. Sorry for bothering you.

**Comment by Tschipp** [comment]
Yeah dunno, snake also works for me... closing this
