### ISSUE TITLE
Scripts ignore White and Blacklist

### ISSUE THREAD

**Issue by Tschipp** [Tschipp/CarryOn#139]

**Comment by remclave** [comment]
This may be related to your scripts issue... We have blacklisted Thaumcraft from CarryOn which works for all of the blocks in the mod but but the Thaumcraft Golems can still be picked up and carried. It's disconcerting to say the least as the screen is black (like player vision is occluded by the object being carried).

**Comment by Tschipp** [comment]
Golems are entities. You need to add them to the entity blacklist.
