### ISSUE TITLE
Modded Chests Don't Rotate

### ISSUE THREAD

**Issue by WenXin20** [Tschipp/CarryOn#14]
Carry On-v1.1.1
Forge v1.10.2-2316

I noticed that most modded chests or tile entities don't rotate when placed to face the direction the player is facing, such as the Iron Chest Mod or the Bibliocraft Mod.

**Comment by capnkirok** [comment]
For most TEs (even modded) it works fine, but these two do not use the provided Minecraft rotation mechanics (I can't tell you why).

**Comment by Tschipp** [comment]
Yep, exactly. So this will unfortunately  not be fixed.
