### ISSUE TITLE
[1.12.2] CarryOn and Signs

### ISSUE THREAD

**Issue by TheSnowyChickens** [Tschipp/CarryOn#142]
### Expected Behavior
A other rendering type and not this:
[look at the screenshot area]

### Actual Behavior
Signs are invisible.
(In SevTech v3.0.8 Signs has the 16x16x16 blue "texture")

### Steps to Reproduce
Hold a Sign.

### Version of Minecraft, Carry On, Forge
MC: 1.12.2
Forge: 2772
C.O.: v1.11.1

### Screenshots encouraged
![grafik](https://user-images.githubusercontent.com/29357962/48514406-8920d400-e85e-11e8-90b1-6eaa88f3a823.png)

**Comment by TheSnowyChickens** [comment]
Ah, im stupid.

I saw it to late.
https://github.com/Tschipp/CarryOn/issues/66

**Comment by Tschipp** [comment]
Added a default model override for signs

**Comment by TheSnowyChickens** [comment]
Ahh, okay.
