### ISSUE TITLE
Carry mobs into rideable entities (Add blacklist/whitelist for stacking)

### ISSUE THREAD

**Issue by mser7** [Tschipp/CarryOn#143]
### Expected Behavior
Pick up a mob, and right-click a minecart with it, the mob should sit in the minecart

### Actual Behavior
Nothing happened

### Steps to Reproduce
Pick up a mob, and right click on the minecart entity

### Version of Minecraft, Carry On, Forge
MC 1.12.2
Cardry on 1.11.1
SSP

**Comment by mser7** [comment]
If a fix is possible, perhap make a compat with Animania to put animals into a cart or wagon

**Comment by Tschipp** [comment]
This *should* already be a feature, but apparently it's not working right.

**Comment by Tschipp** [comment]
Nevermind, it actually works. You just need to set the config entry "stackableEntities" in "settings" to true.

**Comment by Tschipp** [comment]
Also, what may be the problem in your case, is that the animal you're putting into the minecart/boat has a bigger hitbox than the minecart/boat. By default, you can only stack/insert smaller entities on larger ones. However, you can also disable that in the config, "entitySizeMattersStacking"

**Comment by mser7** [comment]
Oh, I disabled that, because I used to try to carry a mob, than right click on a horse to ride it while carrying the mob, and the result is the carrying mob will stack on top of a mob, and it then control it, and mess with my control, due to 1.12.2 mob stacking mechanic

**Comment by mser7** [comment]
Can we have a blacklist/whitelist config for this feature to prevent every mobs from being stacked on each other?

**Comment by Tschipp** [comment]
Hmm ok
