### ISSUE TITLE
[bug] picking up enderChest

### ISSUE THREAD

**Issue by daalekz** [Tschipp/CarryOn#144]
### Expected Behavior
Picking up an enderchest will put it in the player's arms, the same behaviour as all other vanilla chests 

### Actual Behavior
Picking up an enderchest makes it disappear. It doesn't drop a tile, it just disappears.

### Steps to Reproduce
Place an enderchest down (in any gamemode) and shift right click it with an empty hand. 

### Version of Minecraft, Carry On, Forge
Minecraft version 1.12.2
Forge 14.23.5.2768

**Comment by Tschipp** [comment]
This doesn't happen on a clean install. What other mods are you using?

**Comment by Tschipp** [comment]
Closing this...
