### ISSUE TITLE
[SUGGESTION] Allow the creation of scripts that allow for naturally spawning stacking mobs

### ISSUE THREAD

**Issue by Sunconure11** [Tschipp/CarryOn#145]
Since it's possible to stack mobs with this mod, why not allow scripts that do this function?

**Comment by Tschipp** [comment]
I feel like that is out of scope for this mod. CarryOn has nothing to do with spawning mechanics, and also the stacking functionality is secondary. Primary goal is transportation of blocks and entities, so this doesn't really fit.
