### ISSUE TITLE
Server Crash with Carry On

### ISSUE THREAD

**Issue by TacticalUniverse** [Tschipp/CarryOn#148]
### Expected Behavior
The server crashed out of nowhere with https://paste.feed-the-beast.com/view/a5465690

### Actual Behavior
Not sure what caused it

### Steps to Reproduce
Can't say as the server just crashed out of nowhere

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On:  1.12.2 v1.1.12
Forge: 2781 and above

**Comment by Tschipp** [comment]
Can't acces the log, please post somewhere else

**Comment by TacticalUniverse** [comment]
That's cause the log got removed after a day cause it took over 12 days to answer, I don't an extra copy of the crash report
