### ISSUE TITLE
Rustic's & Miniheads' Tile Entities Disappear when Placed

### ISSUE THREAD

**Issue by WenXin20** [Tschipp/CarryOn#15]
Carry On-v1.1.1
Forge v1.10.2-2316

The tile entities disappeared completely after being placed. It affects the display case from the [Miniheads Mod](https://minecraft.curseforge.com/projects/miniheads) and all the tile entities from [Rustic](https://minecraft.curseforge.com/projects/rustic). Something similar seems to happen with the [Simple Barrels Mod,](http://minecraft.curseforge.com/projects/simple-barrels) except the block still exists, but the display indicator addons and the items inside disappear instead.

**Comment by capnkirok** [comment]
@Tschipp Looks like we have some compat issues

**Comment by Tschipp** [comment]
Should no longer be a problem with the latest version
