### ISSUE TITLE
[1.12.2] Item pickup EXACTLY on teleport causes carried objects to be lost.

### ISSUE THREAD

**Issue by Tokeli** [Tschipp/CarryOn#152]
MC: 1.12.2
Forge: 14.23.5.2796
CarryOn: v1.12

Quite frankly this is such a weird edge-case that I was unable to get it to happen twice and I don't expect this report to go anywhere. On SMP, a player timed out as they went thru a nether portal while carrying a chest. They encountered that get-teleported-to-the-wrong-coords bug from vanilla, and logged in without their chest. 

Minutes later I went thru while carrying a chest, and my inventory instantly filled with the contents of THEIR chest. I lost my free hand and my chest vanished instead of being planted on the ground. Subsequent teleports thru kept giving me the rest of their items, tho they weren't visibly dropped anywhere.

### Expected Behavior
If CarryOn encounters an item in your hands immediately after teleport, it should dump it out so you continue to carry the chest/animal.

**Comment by NyanHype** [comment]
This happened to me everytime i tried to go trough a twilight portal carrying a spawner
