### ISSUE TITLE
Wolves wearing armor (from Wolf Armor and Storage mod) do not render armor

### ISSUE THREAD

**Issue by haykam821** [Tschipp/CarryOn#153]
### Expected Behavior

When picking up a wolf that has armor on, the wolf will continue to render its armor.

### Actual Behavior

The wolf that has been picked up will render with a chest (if it has one), but not its armor.

### Steps to Reproduce

1. Spawn a tamed wolf.
2. Give it wolf armor.
3. Try to pick it up.

### Version of Minecraft, Carry On, Forge

* **Minecraft:** 1.12.2
* **Carry On:** 1.12
* **Wolf Armor and Storage:** 2.2.3.6
* **Forge:** 14.23.5.2796

### Screenshots

![Wolf with armor before being picked up](https://user-images.githubusercontent.com/24855774/50193005-bdc2f800-0302-11e9-8f1d-714853e01cec.png)
![Wolf with armor after being picked up](https://user-images.githubusercontent.com/24855774/50193012-c1ef1580-0302-11e9-956a-07bced483e6d.png)

**Comment by Tschipp** [comment]
I directly call the render function for entities. I can't change how custom renderers handle their stuff.

**Comment by haykam821** [comment]
Ok. I will reopen this issue on the Wolf Armor and Storage repo if I can find it.
