### ISSUE TITLE
problems involving wearable backpacks in single player.

### ISSUE THREAD

**Issue by gravysamich** [Tschipp/CarryOn#154]
i lost a save because i accidentally picked up a filled back pack with this mod. the game crashed once i tried to put the pack back down. 

i tested it on a new world and i could pick up and place an empty back pack just fine, but if i add anything to the inventory the game crashes when replacing the back pack.

here is a pastebin of my crash report.

https://pastebin.com/JJpk4Qe4

the version i am using is Carry On MC1.12.2 v1.12.1.

**Comment by Tschipp** [comment]
backpacks are blacklisted in the latest version. Please refresh your config.
