### ISSUE TITLE
Can't pick up Animania Ferrets, Hamsters, Hedgehogs

### ISSUE THREAD

**Issue by Graywaren** [Tschipp/CarryOn#155]
Carry On doesn't seem to be working with these three animania animals. I can pick up animals smaller than them and similar to them, but I can't pick up these three animals which seems wrong to me. They're quite literally animals I can pick up/be pets in real life.... I can't actually pick up a draft horse with my bare hands in real life but I can do it with carry on! Any chance of a fix for this? Do I need to post it to Animania?

### Expected Behavior
Pick up the ferret/hamster/hedgehog

### Actual Behavior
Does nothing

### Steps to Reproduce
Find an animania ferret/hamster/hedgiehog in world or spawn one, [keybind]+click to attempt to pick up with carry on

### Version of Minecraft, Carry On, Forge
1.12.2, Forge b2805, carry on 1.12.1

**Comment by Tschipp** [comment]
They’re blacklisted by default because animania adds its own pickup ability. To be able to pick up the animal with animania, you need to tame it first.
