### ISSUE TITLE
Rendering problem : Betteranimal Plus Mod

### ISSUE THREAD

**Issue by LokyLive** [Tschipp/CarryOn#156]
### Steps to Reproduce
I've just tryed to transport a chicken ... i've never seen a chicken ass so close ....xD

### Version of Minecraft, Carry On, Forge

Mincraft: 1.12.2
Forge version 2784
Better animal Plus 4.1.0
### Screenshots encouraged

![image](https://user-images.githubusercontent.com/15186174/52523187-e88c5580-2c8e-11e9-9adb-7fdd09486553.png)

**Comment by Surac** [comment]
same here

**Comment by Surac** [comment]
i tried to change the render from chicken->(item)egg but it seams i cant chage the render behaviour of an item

**Comment by Tschipp** [comment]
render overrides only work for blocks. Alternatively you could try making a script that translates the chicken differently. I can't do much about this, as I can only calculate where the chicken should be according to its hitbox, but when the model is so much bigger than the hitbox, it looks weird.

**Comment by Surac** [comment]
Script works perfectly. Thanks for pointing this out to me
