### ISSUE TITLE
Pixelmon Faint after putting them down (Pixelmon Reforged 7.0.0)

### ISSUE THREAD

**Issue by Rosychu** [Tschipp/CarryOn#157]
Minecraft: 1.12.2
Forge: 14.23.5.2768
Carry On:  v1.12.1

**Expected Behavior.**
In Pixelmon Reforged 6.3.4 this mod had the ability to pick up and place down Pokemon no problem,

**Actual Behavior**
With the 7.0.0 & 7.0.1 update, you're able to pick up Pokemon still, but upon placing it down, it kills them.

I don't know if there's a fix possible, but, just wanted to bring it up.

Plus, I don't know if this needs to be a separate ticket or not, but Pixelmon Trainer/NPCs corrupt your data upon trying to pick them up. It's a given, it makes sense, but I had to blacklist it with: pixelmon:npc*

Thanks in advance.

**Comment by Jamdog** [comment]
There are several other compatibility issues with Pixelmon - I have logged these on the Pixelmon Bug Tracker, here: https://pixelmonmod.com/tracker.php?p=2&t=13311

**Comment by Tschipp** [comment]
Pixelmon has been blacklisted
