### ISSUE TITLE
Items carried through a Nether Portal seem to get deleted

### ISSUE THREAD

**Issue by Buttcrackofthunder** [Tschipp/CarryOn#159]
what I expected to happen:

I expected to pick up a blaze spawner in the nether, carry it through the portal and set it up in the overworld.

what really happens:

when I entered the portal with the spawner, and travelled, I arrived in the overworld carrying nothing. the spawner was also not on the other side.

how to reproduce:

pick up a blaze spawner (or anything, really, I've only tested it with a spawner) and try to carry it through the portal.

Versions:

MC:1.12.2
CO: 1.12.1
Forge:2768

**Comment by Tschipp** [comment]
Strange, for me it just places any entity/block on the other side. Same with end portals

**Comment by gollariel** [comment]
For me, spawners deleted :(. Also same behavior with "dimensional doors" mod

**Comment by Tschipp** [comment]
I will definitely look into it

**Comment by Tschipp** [comment]
Yeah, I will remove this "feature" in the next update.
