### ISSUE TITLE
Carrying Squids (or water mobs in general that die on land)

### ISSUE THREAD

**Issue by CREEATION** [Tschipp/CarryOn#160]
### Expected Behavior
1. Carrying squids (and fishes, like those from [Just A Few Fish](https://minecraft.curseforge.com/projects/just-a-few-fish)) on land should hurt them after the "default safe time on land" while you carry them
2. Carry water mobs even after they got hurt on land and resume hurting the mobs while carrying

### Actual Behavior
1. You can hold water mobs forever on land
2. You can't pick up squids (and possibly other water mobs) anymore after the first time they get hurt on land

### Version of Minecraft, Carry On, Forge
`1.12.2`, `1.12.1`, `14.23.5.2776`

**Comment by Tschipp** [comment]
That won’t be fixed, as the entities aren’t actually alive in the world but just a rendering. Similarly, when you put an entity into a safari net or something similar, the entity is no longer alive in the world

**Comment by CREEATION** [comment]
Makes sense, thanks! 🐢
