### ISSUE TITLE
[1.13.2] Crash upon generating world & joining.

### ISSUE THREAD

**Issue by Gbergz** [Tschipp/CarryOn#161]
### Expected Behavior
Generating & joining a world as normal.

### Actual Behavior
Game crashes after world-generation is done & then joins world.

### Steps to Reproduce
Create a new world & play.

### Version of Minecraft, Carry On, Forge
| Forge-25.0.92 | MC-1.13.2 | Carry On MC1.13.2 v1.12.2 |

### Crash report:
[Hastebin Crashlog](https://hastebin.com/iyinunoded)

**Comment by Viresneaker** [comment]
I encountered that I picked up an animal from Mo'Creature and my Minecraft crashed (because of Mod incompatibly?) and I couldn't join the server until I deleted my inventory files on the server. Maybe he crashed while he picked something up or has some mods who interfer.

**Comment by Tschipp** [comment]
Closing this, no longer supporting 1.13
