### ISSUE TITLE
Error when picking up slabfurnaces stacked

### ISSUE THREAD

**Issue by BotKendrick** [Tschipp/CarryOn#164]
### Expected Behavior
To pick up the slabfurnace like the other blocks 

### Actual Behavior
When picked up it has the blue and black box texture and when trying to place the item down, it doesn't allow it. Forces you to clear the item which is also deleting the items inside the slab furnaces

### Steps to Reproduce

places two slab furnaces down op top of each other and pickup the the furnaces.

### Version of Minecraft, Carry On, Forge

1.12.2
on the skyfactory 4 mp

**Comment by CobraTran** [comment]
This also occurs with stacked slab chests

**Comment by SNSTAR** [comment]
I don't know how uploading to threads on github works, maybe should've read the rules or something but I'm just here to post this.

I placed a slab furnace under a slab crafting table.

![Capture](https://user-images.githubusercontent.com/49695848/56238283-fa99c400-6042-11e9-8d05-28e0f10730f2.PNG)

**Comment by wanybae** [comment]
It happened to me also.
v4.0.2

**Comment by drmarko9** [comment]
This happened to me when I placed a full furnace on top of my  2 stacked slab furnaces.

**Comment by tyler489** [comment]
Seems To happen with all blocks from https://minecraft.curseforge.com/projects/slab-machines

**Comment by Tschipp** [comment]
Can't recreate this, if error persists please blacklist yourself and update to latest.
