### ISSUE TITLE
Crash in SkyFactory 4

### ISSUE THREAD

**Issue by ApolloMCC** [Tschipp/CarryOn#165]
SpongeForge 1.12.2-2768-7.1.6-RC3616
Forge 14.23.5.2831
Modpack: SkyFactory4

Crash report: https://pastebin.com/8qR3fuZ4

Showed this to sponge they said its carryon related.

**Comment by krisjenner** [comment]
Bump. Same error Sponge server Rc3616

[CRASH](https://gist.github.com/krisjenner/a412ab117911ae61516235018d315bff)
