### ISSUE TITLE
Sky Factory 4 Steel Block not crafting into usable Steel Ingots

### ISSUE THREAD

**Issue by Waffle1099** [Tschipp/CarryOn#167]
### Expected Behavior
Putting a 'Block of Steel' (Thermal Foundation) in the crafting grid gives 9 'Steel Ingot' (Thermal Foundation).

### Actual Behavior
Putting a 'Block of Steel' (Thermal Foundation) in the crafting grid gives 9 'item.tcomplement.materials.name' (Tinkers' Complement).
This item is missing a texture and can only be used to make 'Molten Steel' (Tinkers' Construct).

### Steps to Reproduce
Place a 'Block of Steel' into any crafting grid.

### Version of Minecraft, Carry On, Forge
Minecraft 1.12.2 
Carry On 1.12.1
Forge 14.23.5.2831

### Screenshots encouraged
![2019-04-18_03 08 23](https://user-images.githubusercontent.com/49747188/56346464-bcf28380-6187-11e9-8809-4cb0efe75b18.png)
![2019-04-18_03 08 49](https://user-images.githubusercontent.com/49747188/56346465-bcf28380-6187-11e9-83cc-a1150ddc1e8a.png)
![2019-04-18_03 09 05](https://user-images.githubusercontent.com/49747188/56346466-bcf28380-6187-11e9-8005-87a6ad4e2834.png)
![2019-04-18_03 10 18](https://user-images.githubusercontent.com/49747188/56346467-bcf28380-6187-11e9-9222-cf1b856701c8.png)

**Comment by Tschipp** [comment]
I think you got the wrong mod there mate

**Comment by Waffle1099** [comment]
This is the wrong place to report Skyfactory bugs sorry
