### ISSUE TITLE
Error when picking up

### ISSUE THREAD

**Issue by tonnot2541000** [Tschipp/CarryOn#168]
### Expected Behavior

picking up / placing items back on the ground

### Actual Behavior

mod slab machines all items. 
when stack full block.
can picking up, but can't placing.
All Items

### Steps to Reproduce

fix mod, and more bug

### Version of Minecraft, Carry On, Forge

SkyFactory 4 - 4.0.1	

### Screenshots encouraged
![2019-04-18_21 30 38](https://user-images.githubusercontent.com/49758131/56369428-8702dd00-6223-11e9-99c2-7626108494d1.png)

**Comment by tyler489** [comment]
#164
