### ISSUE TITLE
[1.11.2 v1.2] Dupe arm rendering with Better Survival

### ISSUE THREAD

**Issue by DeadPigman17** [Tschipp/CarryOn#17]
Using CarryOn and Better Survival 1.3, adds a 3rd arm to the player while carrying a block: 
![2017-08-20_17 39 51](https://user-images.githubusercontent.com/22800252/29496261-566138fe-85cf-11e7-8c62-497a4fa303ef.png)

**Comment by Tschipp** [comment]
I've talked with the dev of BetterSurvival and they are using the same method for rendering arms, which overlaps with our way. We will see if there's alternatives, to prevent further incompability, but the BetterSurvival dev would also have to update his code.

**Comment by capnkirok** [comment]
I got the same issue reported from the author of Mynko, simlar dupe arm rendering. Need to see how others handle this.

**Comment by Tschipp** [comment]
@capnkirok Better Survival handles it like we do, dunno about Mynko

**Comment by Tschipp** [comment]
Mynko is not having these rendering issues. I contacted Mynko's Author.

**Comment by capnkirok** [comment]
My recommendation is that Better Survival borrows our technique for showing/hiding the left arm, and only shows it when the player is not carrying. They could check for a child to the Body with our exact Rotation Angles and choose not to render their swinging arm if this child exists.
