### ISSUE TITLE
Picking up pairs of translocators and placing them crashes the game

### ISSUE THREAD

**Issue by observeroftime02** [Tschipp/CarryOn#170]
This is a bug encountered in SkyFactory 4 which includes this particular mod. The translocators are from another mod named [Translocators](https://minecraft.curseforge.com/projects/translocators)

Running vesion 4.0.2 in single player

* Place down two tanks and set up a pair of translocators between them
![2019-04-20_16 47 58](https://user-images.githubusercontent.com/43228249/56463584-14614100-638c-11e9-9b01-cf9f02579145.png)
* Shift+Right Click the plate of the translocator with empty hand
* You have now picked up the pair of translocators
![2019-04-20_16 48 34](https://user-images.githubusercontent.com/43228249/56463591-2c38c500-638c-11e9-9693-1ccfea928802.png)
* Placing it back in the original spot replaces the translocators without issue
* Placing them anywhere else crashes the game

Here's a [log of the crash](https://paste.ee/p/EJsFl) starting from the beginning. Any other relevant information is in the crash log.

Perhaps blacklisting these in the default config would be a good call, because there's really no reason one should be able to pick these up at all.

**Comment by reikonyx** [comment]
Just FYI this is happening in Project Ozone 3 for me currently. On the blacklist, **<translocators:*>** only works when a single one is placed but when the pair is placed together and working they are still able to be picked up. I added **<forgemultipartcbe:*>**  to the blacklist to stop it. The specific tile entity is **<forgemultipartcbe:multipart_block>**

**Comment by Tschipp** [comment]
hmm yeah then I should probably blacklist forge multipart. Could you create a new issue?
