### ISSUE TITLE
OpenComputers Case (Tier III)

### ISSUE THREAD

**Issue by XperioR** [Tschipp/CarryOn#171]
### Expected Behavior
After getting Computer Case in your hands you can simply put it on the ground anywhere you want

### Actual Behavior
Actually, when you have the Case in your hands, you can't put it anywhere, you get message from CarryOn mod on the chat and the console drops you bunch of errors

### Steps to Reproduce
1. Get Case to your inventory (you can do it by Creative mode)
2. Put it on the ground
3. Take it on your hands
4. Try to put it again on the ground

### Version of Minecraft, Carry On, Forge
(Sky Factory 4 modpack)
MC: 1.12.2
CarryOn: "CarryOn MC1.12.2 v1.12.1.jar"
Forge: 14.23.5.2831

### Screenshots encouraged

bug: https://imgur.com/QE0LQWr

log: https://pastebin.com/RDVq2pGm

**Comment by LezChap** [comment]
This appears to be the case with any OC case.

**Comment by dualmoon** [comment]
You can actually duplicate the case this way, but each duplicated case is empty, so your cpu/memory/disks/etc are all gone.
