### ISSUE TITLE
Moving rustic cabinets not working as expected

### ISSUE THREAD

**Issue by AlexejheroYTB** [Tschipp/CarryOn#172]
Cross-posted from https://github.com/Darkosto/SkyFactory4Issues/issues/657
Also reported on rustic github: https://github.com/the-realest-stu/Rustic/issues/254

---

Moving rustic cabinets is very strange and doesn't always work as expected

- **Moving the top half of the cabinet to another location**
  - _The top half retains its `top: true` attribute and turns into an invisible block (unexpected)_
  - The bottom half loses its `bottom: true` attribute
- **Moving the invisible top half of the cabinet back to its original location**
  - The bottom half gains its `bottom: true` attribute back and the cabinet becomes a multiblock again
- **Moving the bottom half of the cabinet to another location**
  - The bottom half loses its `bottom: true` attribute
  - The top half loses its `top: true` attribute
- **Moving the bottom half of the cabinet back to its original location**
  - _The attributes are not changed and the two halves are not merged (unexpected)_
- **Moving the top half of the cabinet to the same location but rotated**
  - _The cabinet becomes a multiblock, but it can be opened only from the direction that each half is facing (unexpected)_

Here is a video showcasing all of these issues: https://youtu.be/AeH9_nI4oAA

---

Would giving the moved block and the surrounding blocks a block update on pickup/place fix this?

**Comment by Tschipp** [comment]
So the thing is, by placing the block updates are already being sent. I had a similar problem with redstone repeaters once, but I managed to solve it by updating the redstone again after the block was placed. Since there's however no universal update function, it may be time to finally rewrite the code and add a proper api...

**Comment by Tschipp** [comment]
Rustic is blacklisted by default, update your config.
