### ISSUE TITLE
Skyfactory 4 - Picked up Bonsai now having lots appear

### ISSUE THREAD

**Issue by Sarelth** [Tschipp/CarryOn#173]
### Expected Behavior
Pick it up, put it down, done.

### Actual Behavior
Picked it up, can place one down, but still holding the original. New ones stay after restarting pack and can not get rid of the one in hand, also can not open inventory

### Steps to Reproduce
Not really sure, it happened to one other person on the server also.

### Version of Minecraft, Carry On, Forge
Sky factory 4 version 4.0.3, I believe the server is a spongeforge server.

### Screenshots encouraged
http://prntscr.com/nhoxfy

**Comment by Sarelth** [comment]
If I die, I place the bonsai at my grave when I come back and I can do other things now.

**Comment by Tschipp** [comment]
Can't recreate, please add it to your blacklist if it causes issues.
