### ISSUE TITLE
Crash with Forge 25.0.191

### ISSUE THREAD

**Issue by GrifVindh** [Tschipp/CarryOn#174]
### Expected Behavior
After clicking the Forge-modified version of Minecraft from the launcher, the Singleplayer/Multiplayer/Options selection screen displays.

### Actual Behavior
The "Mojang" (black text/white window) screen appears briefly, then closes, then the launcher displays a message that Carry On encountered an error during the load_registries event phase.

### Steps to Reproduce
Install Forge 25.0.191 (currently the latest version)
Place Carry On in the mod folder
Attempt to launch Minecraft with Forge

### Version of Minecraft, Carry On, Forge
Minecraft: 1.13.2
Forge: 25.0.91
Carry On: CarryOn+MC1.13.2+v1.12.2.jar

### Screenshots encouraged
![error](https://user-images.githubusercontent.com/49014549/56855674-49840b00-6919-11e9-8281-d8f95f90d3bf.png)

**Comment by Tschipp** [comment]
Yes, I‘m currently not around but will look at it in a week or so. In the meantime, try an older version of forge.

**Comment by Tschipp** [comment]
Should work on latest forge.
