### ISSUE TITLE
Chest dissappeared after going through portal

### ISSUE THREAD

**Issue by pennyarcade** [Tschipp/CarryOn#175]
### Prerequesites
1. Carry on Mod
2. Twilight Forest mod

### Expected Behavior
I keep carrying a cheat after passing through a portal.

### Actual Behavior
Chest full of stuff disappeared when stepping through a portal

### Steps to Reproduce
1. Pick up chest full of stuff.
2. Step through portal
3. Chest is gone

### Version of Minecraft, Carry On, Forge
- Minecraft 1.12.2
- Carry on 1.11.1
- Forge 14.23.5.2772
- Twilight Forest 3.8.689

### Screenshots encouraged
Hmm hard to screenshot a box thats gone...

**Comment by Tschipp** [comment]
Yes, should be fixed on 1.13 but haven’t ported to 1.12 yet
