### ISSUE TITLE
Doesnt respect GriefPrevention Claims

### ISSUE THREAD

**Issue by se7enek** [Tschipp/CarryOn#178]
### Expected Behavior
Chest should not be taken to hand.

### Actual Behavior
Chest WITH contents is being taken by player and chest stays on same spot, duplicating the chest, but removing contents from original one.

### Steps to Reproduce
1. Claim area while using GriefPrevention.
2. Ask someone to come and Shift+Rclick the chest

### Version of Minecraft, Carry On, Forge
1.12.2 Minecraft
1.12.2 v1.9 CarryOn
1.12.2-14.23.4.2707 Forge
1.12.2-2705-7.10 SpongeForge

### Screenshots encouraged
GriefPrevention denying pickup: http://se7en.pl/upload/1558818098.png
GriefPrevention issue: https://github.com/MinecraftPortCentral/GriefPrevention/issues/757

**Comment by Tschipp** [comment]
I don't know what I can do more than send out a regular break event:
[img](https://i.imgur.com/DmS9g9F.png)
Every time that a block is about to picked up, a break event is fired. This event is also fired when the player breaks a block by hand.
Likewise, when an entity is about to be picked up, I send an attack event... not sure what more I can do
