### ISSUE TITLE
[Compatibility] Blocks able to be removed when they really shouldn't be

### ISSUE THREAD

**Issue by Melonslise** [Tschipp/CarryOn#179]
### Expected Behavior
A block locked with my mod [Locks ](https://github.com/Melonslise/Locks) can't be picked up because I cancel the player block break event.

### Actual Behavior
A block locked with my mod [Locks ](https://github.com/Melonslise/Locks) CAN be picked up thus breaking the lock even though I cancel the player block break event.

### Steps to Reproduce
Lock a block with a lock from my mod [Locks ](https://github.com/Melonslise/Locks) and pick it up.

### Version of Minecraft, Carry On, Forge
1.12, may be the case and 1.14 too, haven't checked the latter

### Proposed solution
Fire a player block break event first and check if that goes through

**Comment by Tschipp** [comment]
Heh, now this is a strange coincidence. I'm currently working on a modpack and stumbled upon your mod Locks by chance. I must say, it's very well done. I assumed that you use the vanilla Lock mechanic, which CarryOn should respect. In fact, I tested your mod with CarryOn installed and was glad and surprised to find that it was working as intended. It didn't allow picking up locked blocks **In survival mode**, in Creative mode it still lets the player pick up the block. As soon as the lock is unlocked, the player can pick up the block in survival mode as well. 
I'm guessing you tested this in Creative mode, is that the case?

**Comment by MercurialPony** [comment]
Ohh yes, you're right haha, sorry!
