### ISSUE TITLE
[1.10.2]Crash opening inventory

### ISSUE THREAD

**Issue by NerdCraft** [Tschipp/CarryOn#18]
crash report: https://pastebin.com/BN6w5T1i

**Comment by Tschipp** [comment]
Can you specify? Does it crash when you try and open your inventory while carrying? Or just in general?

**Comment by NerdCraft** [comment]
general

**Comment by Tschipp** [comment]
Well that's bad... checking it out now

**Comment by Tschipp** [comment]
yep, that's a bad one. Hotfix coming in like 15 minutes

**Comment by Tschipp** [comment]
Fix out now

**Comment by NerdCraft** [comment]
It's working, thank you.
