### ISSUE TITLE
Quark chests visual bug

### ISSUE THREAD

**Issue by Fireztonez** [Tschipp/CarryOn#181]
### Actual Behavior
When you move part of a double chest from quark (By example Birch chest), the hitbox change but the visual doesn't fit with the new chest hitbox. This only happen when I move the chest with carry on, when I break and place again everithing is fine...

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Forge: 14.23.5.2838
Carry-On: 1.12.2
Quark: 1.5-167
AutoRegLib: 1.3-31

### Screenshots encouraged
You can see what's append : https://clips.twitch.tv/EndearingDignifiedHedgehogJonCarnage

**Comment by Tschipp** [comment]
Don't think I can do much about this... I think this is on quarks end. I already do as much as I can to rotate blocks that use nbt rotation (which is outdated and shouldn't be used anyway)
