### ISSUE TITLE
CarryOn "items" appearing in JEI

### ISSUE THREAD

**Issue by IronPiston** [Tschipp/CarryOn#182]
### Expected Behavior
Carryon should have no items in JEI

### Actual Behavior
Carryon registers 2 items in JEI that have no purpose

### Steps to Reproduce
Type "@carryon" into JEI and mouseover to find 2 invisible items

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Forge: 14.23.5.2838 (Latest)
Carryon: 1.12.2 (Latest_

### Screenshots encouraged
![2019-07-17_16 55 04](https://user-images.githubusercontent.com/11603684/61414469-a2799480-a8b3-11e9-8bf1-f4af85ff8f69.png)

I have also tried a crafttweaker script to remove these items, but because these items aren't in a creative tab, they can't be hidden.

**Comment by Tschipp** [comment]
Fixed with 2.0.0
