### ISSUE TITLE
Unable to place chest

### ISSUE THREAD

**Issue by emma-noo-noo** [Tschipp/CarryOn#184]
### Expected Behavior
Pick up non-living entity and place it back down again
### Actual Behavior
Picked up the chest, but when wanted to place it received the Error detected: cannot place block message. 
/carryon: clear works fine
Can pick up animals...
Appears to not work with non-living entities
### Steps to Reproduce
Pick up any non living entity....
try and place down

### Version of Minecraft, Carry On, Forge
Minecraft version: 1.12.2
Carry On: 1.12.2
Forge: 1.12.2-14.23.5.2838

### Screenshots encouraged
![2019-08-20_14 50 00](https://user-images.githubusercontent.com/43270604/63353441-a5f0b780-c35a-11e9-9a57-f63547435ab0.png)

**Comment by Tschipp** [comment]
That's definitely not because of just carry on. What other mods are you using that modify the vanilla chest?

**Comment by emma-noo-noo** [comment]
Well i have Quark on, which sorts the inventory in the chest, but haven't had a problem with that before...   i recently put on a few other mods, which i'm in the process of checking to see if that causes the problem... but the other one i could think of is Davincis' Vessels...

Recently updated a few of the mods if that could cause issues?

**Comment by emma-noo-noo** [comment]
Recently updated some of the mods if that could cause the issue?

**Comment by Tschipp** [comment]
I don't know, please try to isolate which mod is causing the problems.

**Comment by emma-noo-noo** [comment]
Hiya, found the mod that is responsible! it was silkyspawners v.1.3 
It appeared to affect most of the tile entities!
Thank you for your help!

**Comment by Tschipp** [comment]
Ok, I'm gonna close this.
