### ISSUE TITLE
Can't pick up mobs

### ISSUE THREAD

**Issue by iJoeyMonster** [Tschipp/CarryOn#187]
### Expected Behavior
Being able to pick up a pig or chicken.

### Actual Behavior
Nothing happens when I shift + Right click.

### Steps to Reproduce
Not sure? It just doesn't do anything. 

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On: CarryOn MC1.12.2 v1.12.2.jar
Forge: 14.23.5.2844

### Screenshots encouraged
Can't really show this with a screenshot. 

Is it possible that if my keybinds are bound to more than one thing as well as Carry On that it won't work?

**Comment by QuantumToasted** [comment]
Dumb question, but have you *checked* your keybinds? I just started a server recently with this plugin and several people have had the keybind disabled. Search for "carry" in your keybinds menu and you'll see the binding for it. Check if it's disabled. A few people have had it not bound on my server

**Comment by Tschipp** [comment]
Can't recreate this... gonna close this. Feel free to reopen if the issue persists.
