### ISSUE TITLE
Crashes When Trying to Pick Up Tektopia Villager.

### ISSUE THREAD

**Issue by TrueDakkon** [Tschipp/CarryOn#188]
Version: 1.12.2 (forge-14.23.5.2846)
When trying to pick up a Tektopia villager the game proceeds to crash.
**EDIT**: When trying to reload the world it will crash again. It essentially completely corrupts that world save.
[Crash Report](https://paste.dimdev.org/zaledateho.mccrashl)

**Comment by Tschipp** [comment]
Report this to TangoTek, he needs to add a null check (or I will blacklist the mod)
