### ISSUE TITLE
Crash when picking up Vanilla Fox

### ISSUE THREAD

**Issue by Partonetrain** [Tschipp/CarryOn#191]
### Expected Behavior
Fox gets picked up and can be placed back down normally

### Actual Behavior
Game crashes, world crashes with the same error when next opened

### Steps to Reproduce
1. New creative world
2. Spawn fox
3. Shift-rightclick on fox

### Version of Minecraft, Carry On, Forge
MC 1.14.4
CarryOn 1.12.3
Forge 28.1.1

Log: 
https://pastebin.com/EcC6mUfB

**Comment by DogResidue** [comment]
I experienced this too. https://pastebin.com/kfVpQhXG

**Comment by ghost** [comment]
Same. https://pastebin.com/wnV9Jrsw
