### ISSUE TITLE
Can't pick up blocks at head-level

### ISSUE THREAD

**Issue by WenXin20** [Tschipp/CarryOn#193]
### Expected Behavior
- To be able to pick up blocks at head-level or above.

### Actual Behavior
- Blocks, such as the furnace, can't be picked up if it's at head-level. Only of it's below.
- Chests at head-level can be picked up only if the character head is pressed into the chest or below head-level.
- `maxDistance` is still set to 2.5

### Steps to Reproduce

1. Place one furnace on top of another.
2. Try to Pick up the bottom furnace - success
3. Try to pick up the top furnace - no success

### Version of Minecraft, Carry On, Forge
- Minecraft v1.14.4
- Forge v28.1.10
- Carry On v1.12.3

**Comment by Tschipp** [comment]
1.14 is still in beta, please bare with me while I iron these things out

**Comment by WenXin20** [comment]
No problem, just reporting in case it was unknown.

**Comment by Tschipp** [comment]
Can't recreate this, both on latest and recommended forge

**Comment by Tschipp** [comment]
I was able to recreate this, but only outside of my modding environment...

**Comment by Tschipp** [comment]
Looks like this was a forge issue. I tried with forge 28.1.8 and it works as it should.
