### ISSUE TITLE
Camera Issue

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Tschipp/CarryOn#194]
### Expected Behavior
If Grab Any Entity on Telepad Block (mod from EnderIO), It will Teleport With You

### Actual Behavior
If Grab Any Entity on Telepad Block, Camera Issues Happen For 1 Minecraft Tick Before Being Normal again

### Steps to Reproduce
1. Build The Telepad (3x3)
2. Put Command Block At North Side of Telepad
3. Put the Stone Pressure Plate At Bottom of Telepad
4. Type On Command Block Like This "clone ~ ~-1 ~2 ~ ~-1 ~2 ~ ~1 ~1"
5. Put Any Entity On Stone Pressure Plate (top)
6. Do That Grab

### Version of Minecraft, Carry On, Forge
MC 1.12.2
Carry on Version 26/06/2019
Forge 14.23.5.2768

### Screenshots encouraged
Impossible!

**Comment by Tschipp** [comment]
Please make a video of this. I do not understand what you're trying to do.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
![2019-09-24_14 50 07](https://user-images.githubusercontent.com/40109698/65505714-cf29d800-df04-11e9-8cb8-86b85dbd9cf1.png)

**Comment by Tschipp** [comment]
I still don't understand. Please make a video.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
[Watch This.](https://github.com/Tschipp/CarryOn/files/3651048/Watch.This.zip)

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
i am wrong. this is torohealth bug.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
no this is ender io bug

**Comment by Tschipp** [comment]
This is not in any way related to CarryOn.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5256
