### ISSUE TITLE
Torohealth Is Broken

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Tschipp/CarryOn#195]
### Expected Behavior
Torohealth And Neat Mod Following Entity Health

### Actual Behavior
Torohealth Mod Isn't Following Entity Health While Neat Mod Following Entity Health

### Steps to Reproduce
Just Grab Entity and Put down

### Version of Minecraft, Carry On, Forge
MC 1.12.2
Carry on Version 26/06/2019
Forge 14.23.5.2768

### Screenshots encouraged
![2019-09-24_14 59 30](https://user-images.githubusercontent.com/40109698/65485255-53b43080-dedc-11e9-8619-f9b8fe99251a.png)

**Comment by Tschipp** [comment]
I don't understand. What is the behavior you're expecting?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
Center Health Bar is Correct (Neat), While Upper Left Health is Broken (ToroHealth).

**Comment by Tschipp** [comment]
Doesn't seem like my mod.
