### ISSUE TITLE
Save corruption upon picking up Baby Villager.

### ISSUE THREAD

**Issue by Ilusionz** [Tschipp/CarryOn#196]
### Expected Behavior
Picking up a baby villager.

### Actual Behavior
Game crashes to desktop, upon reloading the save the game thinks you're still holding the villager so it crashes right away.

### Steps to Reproduce
Read above.

### Version of Minecraft, Carry On, Forge
1.14.4 - MC
28.1.16 - Forge
1.12.3 - Carry On

Not screenshot, but I do have a log (attached)
[Crash.txt](https://github.com/Tschipp/CarryOn/files/3665958/Crash.txt)

**Comment by Partonetrain** [comment]
Happens with adult villagers as well. Same issue as https://github.com/Tschipp/CarryOn/issues/191. Some issue with NBT data
