### ISSUE TITLE
Crash on start of minecraft 1.14

### ISSUE THREAD

**Issue by RoseFox81** [Tschipp/CarryOn#199]
### Expected Behavior

Load in to play
### Actual Behavior
Immediate crash of game

### Version of Minecraft, Carry On, Forge
1.14 
Latest stable version of forge and Carryon

## Crash log file
[crash-2019-10-10_10.15.41-client.txt](https://github.com/Tschipp/CarryOn/files/3725707/crash-2019-10-10_10.15.41-client.txt)

**Comment by Tschipp** [comment]
Looks like I‘ll need to update forge

**Comment by Tschipp** [comment]
Nevermind. Looks like you need to update forge, recommended is 28.1.0. You have 28.0.95

**Comment by RoseFox81** [comment]
Oooh ok, will do

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
