### ISSUE TITLE
Can`t pick anything up

### ISSUE THREAD

**Issue by Loudsquid** [Tschipp/CarryOn#202]
Using on forge for 1.14.4

**Comment by Tschipp** [comment]
What version exactly? Some forge versions seem to have issues.

**Comment by Loudsquid** [comment]
Using forge 28.1.40

**Comment by AgentX2006** [comment]
Do you have something in your offhand slot? I made that mistake.

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
