### ISSUE TITLE
1.14.4 Server crash.

### ISSUE THREAD

**Issue by Wissi** [Tschipp/CarryOn#204]
### Expected Behavior
Server Doesn't crash?

### Actual Behavior
Server Crashes.

### Steps to Reproduce
Sneak-place a tile entity that you picked up with carry-on while aiming at another tile entity, it will place the tile entity you're holding, then pick up the other tile entity.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4
Forge 1.28.76
CarryOn MC1.14.4 v1.12.4

### Screenshots encouraged
Full server log [here.](https://gist.github.com/Wissi/0ce653e35e4903fe113f8d0a1c93e256)

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
