### ISSUE TITLE
When you pick up a chicken, your 1pp view is blocked

### ISSUE THREAD

**Issue by sepsol** [Tschipp/CarryOn#205]
### Expected Behavior
Your view not being fully blocked by a chicken-sized entity!

### Actual Behavior
Your view being fully blocked by a chicken!

### Steps to Reproduce
Just pick up a chicken!

### Version of Minecraft, Carry On, Forge
- Minecraft 1.14.4
- Forge 28.1.76
- OptiFine HD U F4
- CarryOn+MC1.14.4+v1.12.4

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/47871887/68065982-712fb200-fd46-11e9-865f-dfe648ec1374.png)

**Comment by Tschipp** [comment]
That's no chicken, that's something else. You can write a script to change the scale.

**Comment by sepsol** [comment]
I don't know how to write scripts, if you guide me step by step I'll do it though. I almost forgot to mension: that chicken is from [Better Animal Models ](https://www.curseforge.com/minecraft/mc-mods/better-animal-models)mod (5.2.1), so maybe that's why the chicken is bugging out.
