### ISSUE TITLE
Hands detach from character on paperdoll or when going prone

### ISSUE THREAD

**Issue by sepsol** [Tschipp/CarryOn#206]
### Expected Behavior
Hands stay attached to the body.

### Actual Behavior
Hands detach and float either upwards or downwards.

### Steps to Reproduce
Grab an item when having a paperdoll mod installed like [Console Experience](https://www.curseforge.com/minecraft/mc-mods/console-hud) or [Advanced Skin Customization](https://www.curseforge.com/minecraft/mc-mods/advanced-skin-customization). For the prone problem install [GoProne](https://www.curseforge.com/minecraft/mc-mods/goprone) mod and go prone with that and view your character either from 3pp or paperdoll.

### Version of Minecraft, Carry On, Forge
- Minecraft 1.14.4
- Forge 28.1.76
- OptiFine HD U F4
- CarryOn+MC1.14.4+v1.12.4
- ConsoleExperience-v1.5b4.1-1.14.4
- AdvancedSkinCustomization-2.0.2
- goprone-1.14.x-1.1.0

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/47871887/68066076-940e9600-fd47-11e9-889c-3cb5b4cc2448.png)
![image](https://user-images.githubusercontent.com/47871887/68066083-a4bf0c00-fd47-11e9-951a-ce74cc7a4b0b.png)

![image](https://user-images.githubusercontent.com/47871887/68066093-c9b37f00-fd47-11e9-9208-89bbd0419df5.png)
![image](https://user-images.githubusercontent.com/47871887/68066098-d506aa80-fd47-11e9-9894-1899e98655df.png)

**Comment by Tschipp** [comment]
Related to #1

**Comment by Tschipp** [comment]
This will be fixed in the 1.15/1.16 version
