### ISSUE TITLE
Can pick up monster spawners when blacklisted

### ISSUE THREAD

**Issue by Partonetrain** [Tschipp/CarryOn#208]
### Expected Behavior
Can't pick up minecraft:spawner when blacklisted in carryon-server.toml

### Actual Behavior
Can pick up and move spawner 

### Steps to Reproduce
1. add "minecraft:spawner" to forbiddenTiles in carryon-server.toml
2. Shift-right click on spawner in survival

### Version of Minecraft, Carry On, Forge
1.14.4
CarryOn 1.12.4
Forge 28.1.90
### Screenshots encouraged

![image](https://user-images.githubusercontent.com/19861808/69108699-1a5ef380-0a3b-11ea-83e0-bf66df83d0f4.png)

my config: https://pastebin.com/sgtAvnad

**Comment by Tschipp** [comment]
Which file are you editing? The one in the config folder or the one in the world?

**Comment by Partonetrain** [comment]
The one in the config folder... That would explain it. My bad. I'll edit the one in my save and then put it in defaultconfigs. If you don't mind me asking, what's the one in the config folder for then?

**Comment by Tschipp** [comment]
I think it’s supposed to just be the config that is used by default when creating a new world, whereas defaultconfig is the config as it was defined by the code
