### ISSUE TITLE
Crash when Carry On is active while interacting with a GUI block.

### ISSUE THREAD

**Issue by Matthew021750** [Tschipp/CarryOn#209]
### Expected Behavior
While carrying anything, be able to right click on a chest/crafting table/etc. and open the GUI.

### Actual Behavior
Game freezes and then crashes.

### Steps to Reproduce
Left shift + right click on a chest/crafting table/etc., then right click on a block which opens a GUI. (I.E. crafting table, brewing stand, furnace, etc.)

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4 
Carry On: CarryOn+MC1.14.4+v1.12.4.jar
Forge: 28.1.90

**Comment by Tschipp** [comment]
Log please

**Comment by noiamhippyman** [comment]
[crash-2020-03-27_11.12.00-client.txt](https://github.com/Tschipp/CarryOn/files/4394690/crash-2020-03-27_11.12.00-client.txt)

I'm not the OP but I just ran into the exact same problem. This is the log I got when I picked up a chest and tried to place it into a vanilla crafting table.

When I load back into the game the chest is placed on top of the crafting table though. So it get's placed but something with the rendering causes it to crash.

**Comment by noiamhippyman** [comment]
[crash-2020-03-27_11.28.04-client.txt](https://github.com/Tschipp/CarryOn/files/4394770/crash-2020-03-27_11.28.04-client.txt)

Here's a log with only Carry On installed. Hopefully this simplifies it for you a little bit.

**Comment by TerdyTheTerd** [comment]
Shouldn't opening GUI's be prevented while carrying something...if both hands are in use carrying a chest, then how are you able to "open" something else

**Comment by Tschipp** [comment]
It should. This is how it works on 1.12, but it looks like this doesn't work anymore on 1.14...

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
