### ISSUE TITLE
The jacket doesn't move with the arms

### ISSUE THREAD

**Issue by EmosewaGamer** [Tschipp/CarryOn#21]
The part of the jacket, the second skin layer, over the arms doesn't move with the arms when holding tile entities or entities:
![image](https://user-images.githubusercontent.com/25333164/29530599-d7ea0236-86a4-11e7-8e17-d427f90b7089.png)
![image](https://user-images.githubusercontent.com/25333164/29530617-e4677ce6-86a4-11e7-8a99-dee19d6d7af1.png)

**Comment by capnkirok** [comment]
Related to #1
