### ISSUE TITLE
Crash picking up vanilla baby panda

### ISSUE THREAD

**Issue by DogResidue** [Tschipp/CarryOn#210]
### Expected Behavior
The game does not crash when I pick up the panda.

### Actual Behavior
The game crashed about 10 seconds after I picked up the panda.

### Steps to Reproduce
1. Pick up a baby panda.
2. Wait for the game to crash.

### Version of Minecraft, Carry On, Forge
Minecraft - 1.14.4
Carry On - 1.12.4
Forge - 28.1.96

### Screenshots encouraged

I think what might have happened is the panda tried to sneeze while I was holding it and the game did not know how to handle it.

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
