### ISSUE TITLE
Crash putting a held parrot on a furnace

### ISSUE THREAD

**Issue by DogResidue** [Tschipp/CarryOn#211]
### Expected Behavior
I am holding my parrot and I put him down on the furnace. He is sitting on the furnace and my game does not crash.

### Actual Behavior
When I right clicked the furnace to put him down (it wasn't a shift right click, just a normal right click), my game crashed.

### Steps to Reproduce
1. Pick up a parrot.
2. Right click a furnace while holding it.

### Version of Minecraft, Carry On, Forge
Minecraft - 1.14.4
CarryOn - 1.12.4
Forge - 28.1.96

### Screenshots encouraged
This is my crash report: https://pastebin.com/Z7bySJHt

EDIT: I opened my game again and the parrot was sitting on the furnace where I put him.

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
