### ISSUE TITLE
Can't pickup anything with item in offhand.

### ISSUE THREAD

**Issue by AgentX2006** [Tschipp/CarryOn#214]
### Expected Behavior
Chest, machine, etc. will be picked up.

### Actual Behavior
Nothing happens. This may be as intended but the mod description is not clear that the offhand slot must be empty as well. I always carry The Ender from Ender IO with the direct enchant in my offhand so mined blocks go directly to my inventory. This means that when I want to move something I have to have 2 empty hotbar slots. One to swap the sword to and one to switch to afterwards to pick up the item I want to move.

### Steps to Reproduce
1. Equip item in offhand.
2. Try to pick up anything.

### Version of Minecraft, Carry On, Forge
MC 1.12.2
Carry On 1.12.3
Forge 14.23.5.2838

**Comment by Tschipp** [comment]
![image](https://user-images.githubusercontent.com/11649893/71024952-594d9b00-2106-11ea-8055-3a936a201822.png)
This is intended, and it says so on the mod page.
