### ISSUE TITLE
[1.14.4] CarryOn Spamming in Console/Logs

### ISSUE THREAD

**Issue by Gbergz** [Tschipp/CarryOn#215]
### Expected Behavior
No errors in logs, i would guess.

### Actual Behavior
Spewing out errors into the Console/Logs, like hundred lines.

### Steps to Reproduce
Having a Server Online w/ Mod installed & look at Console while it's booting.

### Version of Minecraft, Carry On, Forge
MC: 1.14.4
Forge: 28.1.107
CarryOn: 1.12.4

### Small message in the Console here:
https://hastebin.com/obiriraxos.cs

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
