### ISSUE TITLE
[1.14.4] Picking up a hopper crashed the Server/(game?)

### ISSUE THREAD

**Issue by Gbergz** [Tschipp/CarryOn#217]
### Information
One of our players playing on my Limitless Server crashed it while picking up a hopper w/ Carry On.

### Expected Behavior
Not crashing when picking up a hopper.

### Actual Behavior
Crashing when picking up a hopper.

### Steps to Reproduce
Pick up a hopper. w/ Carry On

### Version of Minecraft, Carry On, Forge
MC: 1.14.4
CarryOn: 1.12.4
Forge: 28.1.107

### Crashreport
[https://gist.github.com/Gbergz/0616329aec69b2fec4365321b1ebd0f7](https://gist.github.com/Gbergz/0616329aec69b2fec4365321b1ebd0f7)

### EDIT:
Could be something todo with NaturallyChargedCreepers(?), not sure though, just saw it in the crash report.

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
