### ISSUE TITLE
Duplicating slime glitch

### ISSUE THREAD

**Issue by Mustached-Man** [Tschipp/CarryOn#219]
### Expected Behavior
Carrying and dropping slimes.

### Actual Behavior
Duplicates smaller slime when i carry medium or large slimes.

### Steps to Reproduce
Shift + right click on any medium/big slime to pick up and see the results.

### Version of Minecraft, Carry On, Forge
1.12.2

### Screenshots encouraged
nah, here's a video instead.
https://streamable.com/v7z7z

**Comment by Tschipp** [comment]
🤔 I thought I fixed that ages ago? Will look into it. I assume you're using latest versions?

**Comment by Mustached-Man** [comment]
Indeed i was.

**Comment by Mustached-Man** [comment]
Only can be picked up in creative

**Comment by Tschipp** [comment]
Still can't recreate. Closing this, feel free to create a new issue if required.
