### ISSUE TITLE
please blacklist refined storage disk drives by default

### ISSUE THREAD

**Issue by EnderSam** [Tschipp/CarryOn#22]
I was playing a custom modpack on accident I used carryon to pick up a refined storage disk drive and it deleted it. I exited the world and everything and it was gone. It was my only disk drive with disks in and I lost everything.

**Comment by Tschipp** [comment]
I'm sorry to hear that. I hope you had s backup. I have a fix on hold that possibly fixed that issue, gonna have to test it.

**Comment by EnderSam** [comment]
yeah I'm lucky I did have a backup
