### ISSUE TITLE
[1.12.2] Multi-Block "blocks" can be picked up

### ISSUE THREAD

**Issue by TheWerdOfRa** [Tschipp/CarryOn#221]
### Screenshots encouraged: See bug report on Immersive Railroading:
https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/705

**Comment by Tschipp** [comment]
This is a known limitation. There are no ways for me to detect if a tile entity is part of a multiblock. I will add immersive railroading multiblocks to the default blacklist.
