### ISSUE TITLE
[1.14.4] Can't pick anything up.

### ISSUE THREAD

**Issue by the-Juice** [Tschipp/CarryOn#222]
I'm using Forge version 28.1.114 and can't pick things up whatsoever.

**Comment by Tschipp** [comment]
Yes, 1.14 is still quite unstable, sorry for that. I will update when I'm done with my exams.

**Comment by Alejandrom3** [comment]
Same with mine. I can't pick anything.

**Comment by DoCharlcate** [comment]
Same Issue here.

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
