### ISSUE TITLE
Bug with picking up campfires.

### ISSUE THREAD

**Issue by TheMisterShura** [Tschipp/CarryOn#224]
★Expected Behavior : 
Picking up an extinguished campfire should lead to putting down an extinguished campfire.

★Actual Behavior :
Picking up an extinguished campfire leads to putting down a lit campfire
★ Steps to Reproduce :
1-Placing a campfire and extinguishing it.
2-picking up the campfire.
3-placing it back.
★ Version of Minecraft, Carry On, Forge:
1.14

**Comment by Tschipp** [comment]
Won't fix, because this would cause a lot of specialized exceptions for certain blocks, and I don't want that.
