### ISSUE TITLE
Blacklist Thaumcraft golems because they make your screen turn black.

### ISSUE THREAD

**Issue by TheTrigg** [Tschipp/CarryOn#226]
Title. Put them back on the ground and you can see again; Press F5 and you can also see again.
1.12.

**Comment by Tschipp** [comment]
Not a bug, but rather the cause of them being very small.

**Comment by TheTrigg** [comment]
They are still scuffed and should be blacklisted.

**Comment by Tschipp** [comment]
I only blacklist game-breaking things. If you're bothered by the view you can write a carryon script that offsets the golems or blacklist them.
