### ISSUE TITLE
Picking up waystone from the waystone mod

### ISSUE THREAD

**Issue by frakier** [Tschipp/CarryOn#227]
### Expected Behavior
for blacklist to prevent picking up

### Actual Behavior
can be picked up

### Steps to Reproduce
added  "waystones:*" to the blacklist, the pick up a waystone
the waystone if two blocks tall so that may be part of the problem

### Version of Minecraft, Carry On, Forge
1.14.4
CarryOn+MC1.14.4+v1.12.4
forge-1.14.4-28.2.0

**Comment by Anatheras** [comment]
![2020-04-08_06 22 17](https://user-images.githubusercontent.com/31390992/78767984-af6a7680-7961-11ea-8544-e07fa998e07c.png)
i have it set to whitelist and i havent added waystone to be pickable

**Comment by chandler05** [comment]
Also affects 1.16, ran into this issue on a 1.16.4 server which broke a few of our waystones

**Comment by NyxWinter** [comment]
This is still broken or broken again on NF 1.21.1 version 2.2.4
