### ISSUE TITLE
Picking up Mo' Creatures entities causes game crash

### ISSUE THREAD

**Issue by MonkChampion** [Tschipp/CarryOn#229]
### Expected Behavior
Shift+Right clicking a Mo' Creatures mob should pick it up.

### Actual Behavior
Shift+Right clicking a Mo' Creatures mob crashes the game with the error "Failed to load entity NBT" and the server cannot be rejoined again by that player until Carry On is removed from the mod list of both server and client. (I have only tested on multiplayer but I assume the same would happen for a single-player world)

### Steps to Reproduce
1. Install Carry On and Mo' Creatures
2. Shift+Right click on a Mo' Creatures mob

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On: 1.12.3
Forge: 14.23.5.2847

(Not sure if you plan compatibility but I thought I would let you know of the issue in case its something you can fix or signs of a wider reaching problem)

Thankyou

**Comment by davigsm** [comment]
I have the same crash, it only crashes with tamed mobs
