### ISSUE TITLE
[1.12] Not working with most things...

### ISSUE THREAD

**Issue by MokahTGS** [Tschipp/CarryOn#23]
So far I've only been able to pickup a pig.  Storage Crates from actually additions don't work...any machine I've tried doesn't work.  Caches from Thermal Dynamics don't work.  Vanilla Furnaces don't work.  Vanilla Donkeys...yup you guessed it...don't work.

I've looked through the black list and none of those things are listed, so I'm not sure what I'm doing wrong but sneaking and right-clicking with an empty hand is not working on 95% of things in the game.

**Comment by Tschipp** [comment]
That is very strange. Could you test it in a new world, and in a fresh installation with only carry on and actually additions?

**Comment by Tschipp** [comment]
Going to close this one in two days if there are no further problems

**Comment by MokahTGS** [comment]
So the issue is with some mods and the right-click and sneak right-click mechanic.   Sometimes it works and sometimes it doesn't.   If this mod had a different key bind it would work 100%. 

The biggest issue is that is so haphazardly choosing when to work and when not too.   I'm not sure how to fix it other then adding a key bind.

**Comment by capnkirok** [comment]
Hey @MokahTGS ! The latest version of Carry On (1.3) has a keybind option :) Why don't you try it out and rebind it to something else and see how it works.

**Comment by MokahTGS** [comment]
Will do thx.   I'll close this and try it out.   If there is an problem I'll open a new issue.
