### ISSUE TITLE
Feature Request: use the server config located in configs

### ISSUE THREAD

**Issue by Anatheras** [Tschipp/CarryOn#230]
### Expected Behavior
Upon creating a new world it would use the settings set in the server config file located in modpack/config/

### Actual Behavior
It creates a new server config file in modpack/saves/"world name"/serverconfig/   using the original template

### Steps to Reproduce
1. Modify server config file in modpack/config/
2. Generate a new world and test it.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4
CarryOn: 1.12.4
Forge: 28.2.3

### Purpose of this feature
It would allow us to generate worlds using a predefined template that is not the original template set up by the mod.

**Comment by Tschipp** [comment]
Really? That shouldn't be the case, I'll check it out.

**Comment by Tschipp** [comment]
Ok, the server-config in the config folder was generated erroneously. Should no longer happen. Fixed on 1.16

**Comment by Tschipp** [comment]
If you want to have a default server config, you need to place it in the `defaultconfigs` folder.
