### ISSUE TITLE
Not working in 1.12.2

### ISSUE THREAD

**Issue by demiena** [Tschipp/CarryOn#233]
The mod is not working in 1.12.2. I tried changing settings, but it didn't work. How to fix???

**Comment by Tschipp** [comment]
No, the mod is working. Send me your settings.txt, your config file, your minecraft version, your forge version and your modlist.

**Comment by Yourname942** [comment]
The mod isn't working for me either anymore for some reason.

Minecraft 1.12.2 Forge 14.23.5.2847
Carryon: CarryOn MC1.12.2 v1.12.3.jar

My settings:
https://pastebin.com/TYzMEr6Q

My modlist:
https://pastebin.com/fR5d0Nvu

**Comment by Tschipp** [comment]
Ok, might be a forge issue. I will look into it.

**Comment by demiena** [comment]
Ok, i hope it will get fixed

**Comment by Tschipp** [comment]
I just tested it, works for me. Could you start removing other mods one by one and see when the problem gets fixed?

**Comment by Tschipp** [comment]
Or maybe not one by one but always half at a time, so you know which half the problem is in after every launch

**Comment by Tschipp** [comment]
Can I also get some more information about your systems?

**Comment by demiena** [comment]
Windows 10

GeForce GtX 1080
i9-9900K 3.60GHz, 3600 MGZ 
48,0 GB RAM

**Comment by demiena** [comment]
> Windows 10
> 
> GeForce GtX 1080
> i9-9900K 3.60GHz, 3600 MGZ RAM

**Comment by xVVitch** [comment]
doesn't work for me or anyone on my server either.
