### ISSUE TITLE
[1.14.4] Blacklisting Create tile entities not working

### ISSUE THREAD

**Issue by jaynesb** [Tschipp/CarryOn#235]
### Expected Behavior
Adding "create:*" to the carryon-server.toml blacklists should prevent the player from being able to pick up any entities from the Create mod.

### Actual Behavior
Create's tile entities can still be picked up, which makes using any behavior requiring sneak+right click impossible to execute.

### Steps to Reproduce

1. Add "create:*" to the forbiddenTiles blacklist in the carryon-server.toml config file.
2. Add "create:*" to the forbiddenEntities blacklist in the carryon-server.toml config file.
3. Launch the game.
4. Put down any tile entity block from Create... as an example, the Encased Shaft.
5. Sneak+Right Click on the block. The player starts carrying the block. 

I've also tried this explicitly specifying the name of blocks in the blacklist, with no change in behavior.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.14.4
Forge: 28.2.3
Carry On: v1.12.4
Create: v0.2.2b

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/16658072/79930876-779e0d00-83fe-11ea-80a8-884a715bb4dc.png)
![image](https://user-images.githubusercontent.com/16658072/79930909-8ab0dd00-83fe-11ea-979c-1c9410935493.png)

I've had a look through the log, but there don't appear to be messages from carryon, or anything interesting occurring when the player manages to pick up the item they shouldn't be able to pick up.

**Comment by Tschipp** [comment]
I assume you edited the configs in the right places?

**Comment by jaynesb** [comment]
Assuming "<instance directory>\config\carryon-server.toml" is the correct one as it very much looks like it is, yes.
Here's a copy of my current file: 
[carryon-server.txt](https://github.com/Tschipp/CarryOn/files/4514951/carryon-server.txt)

(Apparently github doesn't support uploading toml files, so i changed the extension to txt for upload. It is actually a .toml file in my config directory.)

**Comment by Tschipp** [comment]
And are you creating a new world after editing the config?

**Comment by jaynesb** [comment]
Wasn't aware that was required... it would be the first time i've ever heard of a mod requiring a new world upon a config change that didn't affect world generation.

That said, I've just tried it with a new world. Same behavior.

**Comment by Tschipp** [comment]
To my knowledge, this is how the new config works for 1.13+

**Comment by jaynesb** [comment]
I'm fairly certain that's incorrect. As a test, I picked a different mod in my modlist, Charm, and did a before/after test with its config for "TamedAnimalsNoDamage". Tried it on a world with it first disabled, and tamed animals took damage as normal. Exited the game, changed the config so it was enabled, reloaded the game, loaded the same world, and could no longer damage my tamed animal. Honestly, it would be kind of crazy if config was hardcoded into the world files upon world creation, so I'm glad that's not the case.

I decided to do some more testing, and noticed something... weird. I blacklisted the vanilla enchanting table ("minecraft:enchanting_table") to see if anything new added to the blacklist was working. At first I was unable to pick up the enchanting table, but when I moved to a slightly different angle, I _was_ able to pick up the enchanting table. I tried a significant number of angles and it was almost random whether or not the block was picked up, or opened its gui. Same with different distances from the table, though the closer i was the more likely it seemed it would pick up the table.

And then I did the same test with the enchanting table off of the blacklist, and the behavior was exactly the same. I'm no longer sure the blacklist does anything for _any_ entities that aren't on the blacklist by default.

Just to be absolutely sure, I made a fresh 1.14 instance with no other mods besides CarryOn, and the behavior was still the same as I've described.

I could not reproduce the behavior with items that were on the blacklist by default, so at least the default things are working.

**Comment by FernoXL** [comment]
I am also experiencing the same problem. Adding any other mob to the blacklist does not work.
I've tried everything that @jaynesb did with the same result.
Forge 1.14.4-forge-28.2.18

**Comment by FernoXL** [comment]
After looking through the files once more, I noticed that the "serverconfig" folder in the world save file isn't the same as what you put in the config folder. This is what seems to be causing the issue I think.
(I'm not a modder so I don't know).

**Comment by Tschipp** [comment]
Yes, I realize I wasn't very clear but that was the issue I described above. To my knowledge, this is how it works now in +1.13. I have gotten at least like 10 bug reports on this... Closing this then.

**Comment by FernoXL** [comment]
No, no... I've seen other mods put stuff in there based on what's in the config folder and it loads a new copy of it based on what's updated in the config every world load. Yours is not doing that for some reason intention or not It doesn't seem to be a 1.13+ thing. Please re-suggest this.

Also, the file doesn't change when you make a new world either. Its the same base file even if you have updated it before creating the world.

**Comment by Tschipp** [comment]
Can you link me to these mods? I originally followed McJty's tutorial for updating.

**Comment by FernoXL** [comment]
Try Valhelsia Structures
https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures
or Mine and Slash Auto Compatibility
https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-auto-compatibility
(though again I'm not a modder so I really don't know)

**Comment by Tschipp** [comment]
This functionality is fulfilled with the `defaultconfig` folder. A server-config is now no longer generated in the config folder.

**Comment by MrVaiza** [comment]
i just found out you cant have caps like for rats i put Rats:* at first and did not work but rats:* did and i did it in game while its open through mod options and clicked config easy 

hope this helps in your case

**Comment by Tschipp** [comment]
The config now is a common config in 2.0.0
