### ISSUE TITLE
Seems to break Storage Drawers

### ISSUE THREAD

**Issue by jdratlif** [Tschipp/CarryOn#239]
When I use this mod with Storage Drawers, I cannot place anything in the drawers. After I remove this mod, storage drawers works again.

Minecraft 1.12.2
CarryOn 1.12.3
Storage Drawers 5.4.2
Forge 14.23.5.2854

**Comment by Tschipp** [comment]
Can't recreate this. I'm gonna close this issue, but feel free to reopen another one if it is still a problem.
