### ISSUE TITLE
Request: Port to 1.15.2

### ISSUE THREAD

**Issue by natelovesyou** [Tschipp/CarryOn#240]
Please don't smack me over the internet for asking for a port. 😄 I can't help but want to use your mod!

I'm on some 1.15 modpack Discord servers and we keep ranting about how useful CarryOn is. Obviously, there's nothing quite like it. So, take this as both a request and a solid vote that it will be very appreciated and well-liked haha.

Anyway, think about it. :)

**Comment by Tschipp** [comment]
Yes I will update. But updating is not fun, and modding is my hobby. I will get to it eventually, but you must understand that I have other things that I must or want to do as well. I appreciate that you like the mod.
