### ISSUE TITLE
[Feature Request]Allow hitblock when carrying specific entities

### ISSUE THREAD

**Issue by wootaboot** [Tschipp/CarryOn#241]
Allow using scripts to hit blocks and place blocks down when carrying specified entities. Basically allow us to carry specified entities like a parrot. trying to do this with the stoneling from quark.

**Comment by Tschipp** [comment]
hm, this would need a complete rewrite of the underlying mechanics. Maybe

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
