### ISSUE TITLE
Placing on grass causes game crash

### ISSUE THREAD

**Issue by jgaier** [Tschipp/CarryOn#244]
### Expected Behavior
Replace the grass / (place it in front of it)

### Actual Behavior
Game crashes and after reloding the game, object is in front of the grass

### Steps to Reproduce
Pick up Furnace or Chest and Right-click on grass

### Version of Minecraft, Carry On, Forge
Minecraft version 1.14.4
Carry On version MC1.14.4+v1.12.4
Forge 28.2.0

**Comment by Tschipp** [comment]
logs please...

**Comment by jgaier** [comment]
https://pastebin.com/ABYSsF25

**Comment by Tschipp** [comment]
please don't paste the log here... put it in a pastebin
Edit: did it for you but please do it next time

**Comment by Tschipp** [comment]
Won't fix on 1.14. Fixed on 1.15. If this is very important, feel free to PR.
