### ISSUE TITLE
Issue placing OpenBlocks grave

### ISSUE THREAD

**Issue by Lil-Allie-Astra** [Tschipp/CarryOn#246]
Typically upon dying, the person who died takes a a buddy for protection as they retrieve their grave to reclaim their lost inventory, carrying back to a safe location to open it: the error comes when placing it down again.

### Expected Behavior
The grave be placed down in the same orientation relative to the player's facing, relative to when they picked it up.

### Actual Behavior
The grave is placed down with the front always faced North, and the epitaph bearing the player's name is usually gone as well. It is accompanied by an error in the console reading: 
"Error detected. Cannot place block. Execute "/carryon clear" to remove the item
Please report this error here" (linking to https://github.com/Tschipp/CarryOn/issues);
Still places grave as mentioned above.

### Steps to Reproduce
Pick up a grave that spawns from a player's death, containing their inventory from when they died, then place it down again.

### Version of Minecraft, Carry On, Forge
Minecraft 1.12.2
Carry On 1.12.3
Forge 14.23.5.2838
(OpenBolcks 1.7.3)

### Screenshots encouraged
Screenshot 1: Approached grave.
![2020-08-16_00 17 17](https://user-images.githubusercontent.com/49968937/90329080-67361300-df56-11ea-8ef4-0f7537e4115c.png)

Screenshot 2: Picked up grave from the side.
![2020-08-16_00 17 25](https://user-images.githubusercontent.com/49968937/90329085-6f8e4e00-df56-11ea-9acc-33ca5dee10ba.png)

Screenshot 3: Turned 90 degrees clockwise while holding grave to demonstrate the lack of change of orientation.
![2020-08-16_00 17 49](https://user-images.githubusercontent.com/49968937/90329090-787f1f80-df56-11ea-907e-46d0a86d9a36.png)

Screenshot 4: Placed grave back down, and received the aforementioned error.
![2020-08-16_00 17 58](https://user-images.githubusercontent.com/49968937/90329098-8339b480-df56-11ea-9ce4-4a3574956f58.png)

**Comment by Tschipp** [comment]
Strange that it still manages to place even though it sends that message. Is any data lost (apart from the orientation)?

**Comment by Lil-Allie-Astra** [comment]
So far to date, no data has been lost when placing them down. It just
always displays that error, and sometimes removes the epitaph (but thinking
about it now, that may be an issue with my resource pack and shader combo
rather than with CarryOn), or if the epitaph was already gone, sometimes
puts it back.

**Comment by Tschipp** [comment]
Yeah the removal of the epitaph sounds more like shader/resource pack issues, carry on wouldn't be able to recreate data if it wasn't already there... I'll go over the checks that cause that message, because it seems to be fine otherwise.
