### ISSUE TITLE
Help locating the config?

### ISSUE THREAD

**Issue by nosevole** [Tschipp/CarryOn#250]
I sincerely apologise if I'm just overlooking something and wasting your time, however I cannot find the config. 

### Expected Behavior
The curseforge page says it's accessible in-game from the menu...

### Actual Behavior
...but I see no options relating to the mod at all, other than one rebinding option in the controls menu.

### Steps to Reproduce
n/a

### Version of Minecraft, Carry On, Forge
1.16.2, 1.14.0.3, 33.0.42

### Screenshots encouraged
n/a

As I say, I'm really sorry if this is user error, but I've looked in every menu tab and am drawing a blank. Thanks for your time :) xx

**Comment by Tschipp** [comment]
The in-game config only exists for 1.12. I haven't gotten around to updating the page

**Comment by copygirl** [comment]
Where is the config file in the 1.16.5 version? I only see a `carryon-client.toml` one in the `config/` folder.

**Comment by Tschipp** [comment]
in the world specific config folder, as has been the case for all mods since 1.13

**Comment by copygirl** [comment]
Ah I see. So, presumably the `defaultconfigs/` folder is where you put the world specific config files, so they automatically get copied over when creating a singleplayer world or launching a server? Also, you say it's the case for all mods but here are the two config folders in comparison:

![image](https://user-images.githubusercontent.com/272586/109416609-9f1b1a00-79bf-11eb-9fc7-e650a53c59de.png)

**Comment by Tschipp** [comment]
Well, I might have to look into this then. Seems it has changed lately. In any case, yes, the defaultconfigs folder will copy any configs to the world folders when a new world is created.
