### ISSUE TITLE
dankstorage:dock not replaceable

### ISSUE THREAD

**Issue by 4Magma** [Tschipp/CarryOn#251]
I'm new to dank storage mod and have never before build an dock.
So i placed it on ground and put an dank storage in. As i tried to get
it back, i instead picked the dock up with CarryOn. 
But i couldn´t place the dock back.

### Expected Behavior
a) dock is blacklisted to prevent pickup
b) CarryOn can place dock

### Actual Behavior
- dock is pickable but not again placeable
- i think i got a text to use /carryon clear 

### Steps to Reproduce
- place dankstorage:dock 
- put dankstorage:dank_* in
- pickup with carry on
- try to place with carry on

### Version of Minecraft, Carry On, Forge
MC 1.16.2
carryon-1.16.2-1.14.0.3
dankstorage-3.10c
33.0.37

**Comment by Alaric323** [comment]
I can confirm this bug exists.  Right clicking the frame of the dock picks up the dock, but it cannot be placed back down, with or without the storage module inside.  Edit: Shift right clicking the storage module itself does work, but if you touch the frame by accident, you lose the frame and the storage module when you clear it.  

Below is the item ID that debug reports.

![image](https://user-images.githubusercontent.com/4038592/106687842-eec21d80-659a-11eb-8fc9-40c8facbfb60.png)
