### ISSUE TITLE
Unable to pick up blocks

### ISSUE THREAD

**Issue by Nexusdog** [Tschipp/CarryOn#252]
MC/F 1.15.2/31.2.36

Carryon-1.15.2-1.13.0.5

Unable to carry blocks. Rebinding keys, rebind then reset, no effect
Able/Disable white/black list, no effect

(Thanks for great mod tho!)

**Comment by Tschipp** [comment]
What blocks were you trying to pick up?

**Comment by Nexusdog** [comment]
A wide variety, from gravel, sand & dirt, to chests, leaves, you name it.

**Comment by Tschipp** [comment]
Hmm, chests should work (with default settings). Normal blocks only work if you enable pickupAllBlocks in the (server) config (in the world folder)

**Comment by Nexusdog** [comment]
Hi, sorry I wasn't too clear last night. I can pick up passive mobs such as pigs and cows, but no luck otherwise. I did as you suggested with the config and set to pick up all, but besides the mobs, no luck.

**Comment by Tschipp** [comment]
Are you using any other mods? Can you record a video of this happening (with chests)? Can you show your config (that is in the serverconfigs folder in the world folder)?

**Comment by NewbCyBot317** [comment]
Having the same issue using magma (mods+plugins) and it seems to be doing the same thing in 1.12.2

**Comment by Tschipp** [comment]
Can't recreate this. I'm gonna close this issue, but feel free to reopen another one if it is still a problem.
