### ISSUE TITLE
Picking up furnace resets burn time

### ISSUE THREAD

**Issue by Smearfo** [Tschipp/CarryOn#253]
### Expected Behavior
When picking up an active furnace, it would either keep or clear its current burn time

### Actual Behavior
The furnace's burn time is set back to full, and it stays at full until another item is smelted in the furnace

### Steps to Reproduce
Start something smelting, remove items from furnace, pick up furnace and place back down

### Version of Minecraft, Carry On, Forge 
Minecraft 1.12.2, Carry On 1.12.3.15, Forge 14.23.5.2854

**Comment by Tschipp** [comment]
I'm assuming with burn time you mean the moving arrow in the GUI and not the state of the fire, correct?

**Comment by Smearfo** [comment]
No, what I mean is that the fire goes back to full on placement, sorry for the miscommunication.

**Comment by Tschipp** [comment]
Okay, I'll investigate

**Comment by Tschipp** [comment]
This is a deeper issue. I'm gonna close this and reopen a new issue.
