### ISSUE TITLE
[1.15.2] Mod ceases to function after an indeterminate amount of time

### ISSUE THREAD

**Issue by FastBoye127** [Tschipp/CarryOn#255]
CarryOn seems to become permanently non-functional on a per-world basis. I'm not sure what triggers the problem, but once it occurs, nothing will get the functionality back, including uninstalling the mod and deleting its configs, loading the world without the mod, and then reinstalling. Creating a new world makes the mod function properly in that world, but after some time it will stop.

### Expected Behavior
Carryon functions normally across all worlds.

### Actual Behavior
Carryon ceases to function on a per-world basis.

### Steps to Reproduce
Unknown

### Version of Minecraft, Carry On, Forge
Minecraft 1.15.2
Forge 31.2.36
CarryOn 1.13.0.5

**Comment by Tschipp** [comment]
Is it possible that this is the same issue? https://github.com/Tschipp/CarryOn/issues/261
In any case, I'm gonna need some logs

**Comment by Tschipp** [comment]
Can't recreate this. I'm gonna close this issue, but feel free to reopen another one if it is still a problem.
