### ISSUE TITLE
[QUESTION] Fabric

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#256]
Is there any possibility we can see this mod ported to Fabric?

If not, can other modders fork the project to port to Fabric themselves?

**Comment by Tschipp** [comment]
I'm considering making a fabric port

**Comment by NathnTaylor** [comment]
That's super exciting! I'd love to see a port of it! Thanks for considering it <3

**Comment by YTG1234** [comment]
There's a [Fabric mod with similar functionality](https://curseforge.com/minecraft/mc-mods/carrier) so you (@Tschipp ) and that mod's author can collaborate on a complete Fabric port of this. I almost always like seeing official ports instead of alternatives.

**Comment by vico93** [comment]
> There's a [Fabric mod with similar functionality](https://curseforge.com/minecraft/mc-mods/carrier) so you ([at]Tschipp ) and that mod's author can collaborate on a complete Fabric port of this. I almost always like seeing official ports instead of alternatives.

_Yeah, i shouldn't have told in Fabric server about this..._

First of all the said mod doesn't have _even half_ of the functionalities CarryOn does like rendering carried enities, if heavy can or not be carried, former tile entities like chests can or not be carried, a separated keybind to carry (like CarryOn), [and so on](https://gist.github.com/vico93/cd6c14619b3342f17a45de0cc1de7660), second monopoly in any topic is just **bad**, in modding that just add more nuisances for moddders, since a usecase having a single mod implementation means more folks began to pesk them in each Minecraft update, while multiple takes alleviates modders from hate in case they are unable to update their mods for a while. The major example is myself, needing to brag server after server to see if someone have interest in make a mod similar to Pillar/AS Ruins (something lost even before the worldgen changes, back in 1.13), or TrainCarts which even never have a mod version (need to use awful hybrids to work with Forge/Fabric mods).

So... just no.

**Comment by Flexico** [comment]
Any progress on this?

**Comment by wolvyreen** [comment]
2 years running and STILL no fabric port! very sad indeed.

**Comment by Tschipp** [comment]
Fabric port is now available, starting from version 2.0.0
