### ISSUE TITLE
1.15.2 Server freeze

### ISSUE THREAD

**Issue by BaccarWozat** [Tschipp/CarryOn#261]
### Expected Behavior
Server should start as usual. It's done this every day for months.

### Actual Behavior
Does not start. Got lots of CarryOn errors in the latest.log below.

### Steps to Reproduce
If this is caused by CarryOn, it may have something to do with #255 .
At present I am trying to get the server going again even without CarryOn if necessary, without much success.

### Version of Minecraft, Carry On, Forge
MC 1.15.2
CarryOn 1.15.2-1.13.0.5
Forge 31.2.37
No crash report but here's the latest.log: https://pastebin.com/zrFxqucU

**Comment by BaccarWozat** [comment]
The server will not run the map even without CarryOn installed, but if # 255 is right the map was somehow made unplayable?!?
The map may be played (with or without CarryOn) in singleplayer though.
Further troubleshooting will be done. It might not be a CarryOn issue but I cannot be certain.

**Comment by Tschipp** [comment]
This is very confusing, I've never seen anything like it. I'll try to figure this out

**Comment by BaccarWozat** [comment]
Seems the problem was with Discord Integration. Not sure why it didn't say "ERROR" whereas CarryOn did, but it has something to do with a Discord update changing how the bot functions.
https://support-dev.discord.com/hc/en-us/articles/360056426994
