### ISSUE TITLE
[1.16.3] Cannot carry chests and crafting tables

### ISSUE THREAD

**Issue by jesuscc1993** [Tschipp/CarryOn#262]
### Expected Behavior
Should be able to carry chests and crafting tables.

### Actual Behavior
Cannot carry chests and crafting tables.

### Steps to Reproduce
Press hotkey + right click on chest or crafting table.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.16.3
Carry On: 1.15.1.7
Forge: 34.1.33
OptiFine: 1.16.3 HD U G3
(no more mods active)

### Screenshots encouraged
![carry](https://user-images.githubusercontent.com/8211197/97503349-2bb3be00-1975-11eb-8dd2-ae6e9cca9eb8.gif)
![image](https://user-images.githubusercontent.com/8211197/97503038-944e6b00-1974-11eb-869e-b97792173635.png)

### Comments
Entities like furnace and tamed wolf can be picked, while chests and crafting tables can't.

**Comment by Tschipp** [comment]
The crafting table is a regular block, not a tile entity, which can not be picked up by default. You can enable that in the config.
It kind of looked like in the clip that you were too far away from the chest, but not sure.

**Comment by jesuscc1993** [comment]
> It kind of looked like in the clip that you were too far away from the chest, but not sure.

I just tried again from the block right next to the chest and I still was unable to pick it up. It just opens the chest's inventory.

**Comment by jesuscc1993** [comment]
***Update:*** I have no idea what I was doing wrong before but it's working now so I'll close the ticket.
One little note, though: if you place a chest while still holding crouch next to another both remain single chests instead of becoming a double chest.

**Comment by Tschipp** [comment]
> One little note, though: if you place a chest while still holding crouch next to another both remain single chests instead of becoming a double chest.

That is indended behavior from vanilla
