### ISSUE TITLE
Blockstate parsing Exception

### ISSUE THREAD

**Issue by BedrockLegends** [Tschipp/CarryOn#266]
### Expected Behavior
Away to fix it

### Version of Minecraft, Carry On, Forge
Carry on - 1.16.3-1.15.1.7
Minecraft 1.16.4
Forge 35.0.7

### Screenshots encouraged
[Carryon issues.txt](https://github.com/Tschipp/CarryOn/files/5507293/Carryon.issues.txt)

**Comment by Tschipp** [comment]
It's just a warning, just ignore it
