### ISSUE TITLE
Dupe bug: Ice and Fire Pixie Jars 

### ISSUE THREAD

**Issue by GSValore** [Tschipp/CarryOn#268]
### Expected Behavior

Placing a jar when right-clicking while carrying jar.

### Actual Behavior

Jar is placed but also remains in your hands and throws an NPE.

### Steps to Reproduce

1. Place a Pixie jar (any color)
2. Crouch and pick it up
3. Attempt to place the jar

### Version of Minecraft, Carry On, Forge

Minecraft: 1.16.3
Carry On:  1.15.1.7
Ice and Fire: 2.1.2
Forge: 34.1.42

### Screenshots encouraged
![2020-11-20_21 42 40](https://user-images.githubusercontent.com/1607082/99866746-590d1980-2b79-11eb-8aad-278897141913.png)

### Error log: 
https://gist.github.com/GSValore/84ad8eb904aff557edd6a9edb5e84e17

**Comment by FurryApocalypse** [comment]
We had similar problem on 1.16.4.
Friend of mine decidet to /kill to get rid of jar from hands. (keep inventory was on)
In fact he remain dead and server stopped noticing him at all even if he was online. That was wierd. I had to delete his champion log from server to clear it up. That helped for perma-death.

**Comment by Tschipp** [comment]
/carryon clear should work in those cases

**Comment by FurryApocalypse** [comment]
Thank you!
