### ISSUE TITLE
How to rebound "shift" from crouching?

### ISSUE THREAD

**Issue by OldDogy** [Tschipp/CarryOn#27]
Crouch + empty hand right click is used on some machines/inventories even possibly custom entities for special tasks, and calling up those blocks special GUIs.
Example: Storage drawers

Instead what happens is that I'm always picking up all of those machines,inventories and entities.
And since I'm playing on a server I can't simply blacklist the block either.

It would be AMAZING if your mod would instead use a simple keybound for picking up instead of having it hardcoded to crouch and empty hand right click ?

Cheers !
~OldDogy

**Comment by Tschipp** [comment]
This was added in the 1.3 release

**Comment by OldDogy** [comment]
Oh Sorry for bothering !
