### ISSUE TITLE
How to distinguish pick up events from break events?

### ISSUE THREAD

**Issue by hammertater** [Tschipp/CarryOn#277]
Using carryon-1.16.3-1.15.1.7, attempting to pick up a block with CarryOn triggers a BreakEvent:

https://github.com/Tschipp/CarryOn/blob/171abb8210e29a8ee980177e6537cdcfb1ffb768/src/main/java/tschipp/carryon/common/handler/PickupHandler.java#L180-L191

This is fine, but I'm not sure how to distinguish CarryOn pickup attempts from normal block break attempts. What about defining an event that extends the normal BreakEvent? Something like

```java
class PickUpEvent extends BlockEvent.BreakEvent {
    public PickUpEvent(World world, BlockPos pos, BlockState state, PlayerEntity player) {
        super(world, pos, state, player);
    }
}
```

then post the event with

```java
BlockEvent.BreakEvent event = new PickUpEvent(world, pos, state, player); 
MinecraftForge.EVENT_BUS.post(event); 
```

so that other mods can check for this event with

```java
public static void onBreakEvent(BlockEvent.BreakEvent event) {
    if (event instanceof PickUpEvent) {
        ...
    }
}
```

or maybe there's a better way of doing this.

For context - someone using my TreeChop mod and CarryOn at the same time noticed a conflict of our BreakEvent behaviors (https://www.curseforge.com/minecraft/mc-mods/treechop?comment=60). A hacky fix from my end is to disable TreeChop during RightClickBlock events (when CarryOn posts BreakEvents), but I'm worried that this might cause unexpected conflicts with other mods.

**Comment by Tschipp** [comment]
Yeah sure, I can wrap the event in a PickUp event

**Comment by hammertater** [comment]
Works great, thanks!

**Comment by Tschipp** [comment]
Great to hear!
