### ISSUE TITLE
Picking up a Minecart teleports the driver to void

### ISSUE THREAD

**Issue by Dekamir** [Tschipp/CarryOn#280]
### Expected Behavior
Do nothing

### Actual Behavior
Pulls Minecart under the player and teleports the player to void

### Steps to Reproduce
Try to carry a Minecart while a player is inside

### Version of Minecraft, Carry On, Forge
1.16.5, 1.15.1.7, 36.0.1

### Screenshots encouraged
_It's just the void._

**Comment by manic-vermin** [comment]
Something similar happened when I picked up a villager in a boat. The villager was nowhere to be found. Version 1.16.4.
