### ISSUE TITLE
Picking up FTB questscreen (3x3) locks up player

### ISSUE THREAD

**Issue by GHTShullubullu** [Tschipp/CarryOn#285]
### Expected Behavior
When picking up block players should be able to put it down again.

### Actual Behavior
When picking up center block of a 3x3 FTB questscreen makes it so that the player can not put it down again.

### Steps to Reproduce
Place 3x3 FTB questscreen and shift + right click.

### Other info
Issue found with ATlauncher opening modpack "Trillionaire".
Doing a /kill empties inventory and the block is removed. However if player picks up gravestone with items (From "Tomb Many Graves" mod) the block returns to inventory and soft locks the player.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry on : 1.12.3
Forge: 14.23.5.2847
Tomb Many Graves 1.12-4.2.0

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/13290079/106648587-c2a19f00-6590-11eb-9fb8-d72575fec59a.png)

**Comment by Tschipp** [comment]
For future reference, use /carryon clear to remove the block if this happens
