### ISSUE TITLE
[Bug & Compatibility] Physics Mod

### ISSUE THREAD

**Issue by ConqAra** [Tschipp/CarryOn#286]
(1.16.5)

When you pick up an animal or mob with CarryOn's carry feature, the Physics mod will, for some reason, recognize it as dead and play the mob physics death animation even though it didn't technically die.

Link to Mod: https://github.com/haubna/PhysicsMod/

**Comment by Tschipp** [comment]
Carry on marks the entities as dead. This seems like a bug of the PhysicsMod.
