### ISSUE TITLE
Whitelist Isn't Working

### ISSUE THREAD

**Issue by coryjreid** [Tschipp/CarryOn#288]
### Expected Behavior
Only be able to pickup `minecraft:chest` when enabling whitelist mode and whitelisting a chest.

### Actual Behavior
Cannot picking anything.

### Steps to Reproduce
1. Enable whitelist mode for `useWhitelistBlocks` , `useWhitelistEntities`, and `useWhitelistStacking` in config.
1. Add `"minecraft:chest"` to `allowedBlocks` in config.
1. Log into world which has edited config.
1. Attempt to pickup chest.

### Additional Notes:
- Tried placing `"minecraft:chest"` in `allowedEntities`, `allowedBlocks`, and `allowedStacking` in all combinations
- Tried enabling `pickupAllBlocks` which did not help
- When using blacklist mode picking up chests works as expected

### Version of Minecraft, Carry On, Forge
Minecraft: 1.16.4
Carry On: carryon-1.16.5-1.15.2.9
Forge: forge-35.1.36

### Screenshots encouraged
N/A

**Comment by coryjreid** [comment]
This seemed to be fixed... but in testing it is continuing to happen.

Version: carryon-1.16.5-1.15.3.11

Steps:
* Create a new world.
* Test picking up chest (works).
* Save/close world.
* Set useWhitelistBlocks = true.
* Test picking up chest - cannot pickup chest (expected).
* Save/close world.
* Add "minecraft:chest" to allowedBlocks.
* Test picking up chest (doesn't work).

This happens in isolation (with Carry On being the only mod) and inside our modpack.

A derpy video demonstration (HD still processing at time of post): https://www.youtube.com/watch?v=vm8rBZ3SBHA

**Comment by Tschipp** [comment]
Very strange. My workspace is on 1.16.5, maybe that has an impact? It shouldn't, but I'll test more

**Comment by Tschipp** [comment]
Interesting... the same version works perfectly on 1.16.5 but doesn't work on 1.16.4 on the same world. Very strange.

**Comment by Tschipp** [comment]
![image](https://user-images.githubusercontent.com/11649893/108132828-d0d4dc80-70b3-11eb-8554-47c23dffa2b2.png)
Interesting, this might be a forge bug.

**Comment by Tschipp** [comment]
Ok, I think I got it now. Tested it on 1.16.4 and it seems to work, even with hot reloading (editing the config while the world is open)

**Comment by coryjreid** [comment]
Just wanted to confirm that carryon-1.16.5-1.15.3.13 does work as intended and say thanks for the quick fix!

You saved my server a lot of crashes from my friends who like to try to picking up *anything and everything*. 👍🏻

**Comment by Tschipp** [comment]
Great to hear!
