### ISSUE TITLE
Can no longer pick up entities/tile entities with 1.15.3.11

### ISSUE THREAD

**Issue by enduum** [Tschipp/CarryOn#290]
### Expected Behavior:
Shift-right click to pick up mobs and tile entities.

### Actual Behavior:
Absolutely nothing happens. Tried cats, sheep, llamas, chests, sporelings from Creatures and Beasts, none worked.

### Steps to Reproduce:
-Install 1.15.3.11
-Try to pick up any critter
-Nothing happens.

### Versions:
Minecraft: 1.16.5
Carry On: 1.15.3.11
Forge: 36.0.42 (latest) and 36.0.22 (what I had been using)

Tested on a clean install with no other mods.

**Comment by Tschipp** [comment]
Could you record a video of this happening?

**Comment by enduum** [comment]
I have been unable to recreate this myself since opening the issue. I apologize for the bogus report.

I _did_ manage to record a different bug, though: Carrying any boat converts it into an oak boat regardless of what it was before. [[video link]](https://youtu.be/5N4mNEgLbas)

**Comment by Tschipp** [comment]
I see, could you create a new issue for that?
