### ISSUE TITLE
All boats become oak boats after being carried

### ISSUE THREAD

**Issue by enduum** [Tschipp/CarryOn#291]
### Expected Behavior
All boats retain their wood type after being picked up.

### Actual Behavior
Boats of any wood type become oak boats while carried and remain oak when placed again.

### Steps to Reproduce
1. Place a birch boat.
2. Pick up your birch boat.
3. It's oak.

### Versions
Minecraft: 1.16.5
Forge: 36.0.42
CarryOn: 1.15.3.13

[[Video link]](https://www.youtube.com/watch?v=5N4mNEgLbas)

**Comment by surfishs** [comment]
hi， I have too

**Comment by Tschipp** [comment]
fixed for 1.16,1.17 and 1.18
