### ISSUE TITLE
1.16 Lectern deletes book after being picked up

### ISSUE THREAD

**Issue by flwndev** [Tschipp/CarryOn#292]
### Expected Behavior
Not delete the book inside.

### Actual Behavior
Deletes the book on pickup of the lectern.

### Steps to Reproduce
Put a book inside a lectern and pick up the lectern, it then deletes the book.

### Version of Minecraft, Carry On, Forge
1.16.5 / carryon-1.16.5-1.15.3.13 / forge-36.0.42

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/26978520/108783260-71704400-756d-11eb-8753-a8a3e1bf9b6b.png)
![image](https://user-images.githubusercontent.com/26978520/108783294-83ea7d80-756d-11eb-9593-189a0cb58986.png)
![image](https://user-images.githubusercontent.com/26978520/108783309-8c42b880-756d-11eb-91e2-b3514f2f21c7.png)

**Comment by Tschipp** [comment]
Fixed with #287

**Comment by Aceplante** [comment]
still occurs on 1.18.2
