### ISSUE TITLE
1.16 Compability with Corpse mod

### ISSUE THREAD

**Issue by RHSD** [Tschipp/CarryOn#295]
### Expected Behavior
Carrying corpse entity should keep its properties like skin, items inside, armor, hand item etc.

### Actual Behavior
The entity is blank if carried. Skin gets replaced with default steve skin and inventory gets reset.

### Steps to Reproduce
Get corpse mod and carry corpse entity.

### Version of Minecraft, Carry On, Forge
1.16.5, 1.15.3.13, 36.0.45

**Comment by PastaRasta** [comment]
Just had this same issue happen to me! Picked up my corpse by mistake, all my items voided.

**Comment by Tschipp** [comment]
as far as I can tell, it doesn't void the items anymore in 1.19.2, but instead duplicates them... I should technically be cancelling the interaction with the entity, but it's not happening for some reason.

**Comment by Radon8472** [comment]
> as far as I can tell, it doesn't void the items anymore in 1.19.2, but instead duplicates them... I should technically be cancelling the interaction with the entity, but it's not happening for some reason.

We are currently using this mod in 1.20.1, 
interaction with the body seems to be successful disabled in that version.
