### ISSUE TITLE
Bug with waystones from waystone mod.

### ISSUE THREAD

**Issue by Kutomi1** [Tschipp/CarryOn#298]
I'm using MC 1.16.4, the latest version of Forge and Carry On.
I activated a waystone, decided to see if I can pick it up, and I picked it up, but it also broke so I had it in my inventory, and in my hands, but I couldn't place it, so I killed myself, retrieved my items from the Corail Tombstone mod's tombstone, then [this happened.](https://cdn.discordapp.com/attachments/789397758670667799/820762419810271302/2021-03-14_21.51.36.png)
This time I was able to place it, when I tried again, it became a weird half block when placed. (https://cdn.discordapp.com/attachments/789397758670667799/820762423090348052/2021-03-14_21.51.44.png)
(https://cdn.discordapp.com/attachments/789397758670667799/820762425920847942/2021-03-14_21.54.34.png)

**Comment by Kutomi1** [comment]
Also, I can't seem to find a config where I can blacklist blocks from being picked up. I'm sure there was one in the older versions.

**Comment by Tschipp** [comment]
The blacklist and whitelist configs are in the world's config folder. If you want to clear a carried item, do /carryon clear.

**Comment by Kutomi1** [comment]
So there isn't a config that applies to all worlds?

**Comment by Tschipp** [comment]
if you put it in the defaultconfigs folder it will apply to newly created worlds.

**Comment by Kutomi1** [comment]
All right, thanks.
