### ISSUE TITLE
[1.12] mobs fluctuate in size when picked up

### ISSUE THREAD

**Issue by lag42** [Tschipp/CarryOn#30]
they very quickly fluctuate in size and in first-person this looks like they just phase in and out of existance

**Comment by Tschipp** [comment]
What version of Forge are you using? Are you using any other mods than CarryOn?

**Comment by lag42** [comment]
i'm using forge 14.22.0.2463
with:
albedo
applied energistics 2
autoreglib
baubles
better builders wands
betterfps
botania
carryon
chisels & bits
chunk animator
codechickenlib 1.8+
cofh core
cofh world
crossroads mc
cyclic
dungeon tactics
emberroot zoo
extra utilities
flat colored blocks
floocraft
foamfix
guide-api
heroes expansion
hwyla
immersive engineering
immersive petroleum
journeymap
just enough items
llibrary
lucraft core
mcjtylib
mrcrayfish's furniture mod
quark
redstone flux
regeneration
rftools
runes of wizardry and classic dusts pack
shetiphiancore
tammodized
terraqueous
the lost cities
thermal expansion
thermal dynamics
thermal foundation
voidcraft
wearables

**Comment by Tschipp** [comment]
Is this still an issue with the latest version?

**Comment by lag42** [comment]
No
