### ISSUE TITLE
Server config still generated in /config in 1.15.2

### ISSUE THREAD

**Issue by ah-OOG-ah** [Tschipp/CarryOn#300]
### Expected Behavior
As far as I could tell from issue #235, `carryon-server.toml` shouldn't be generated in /config/ on launch. 

### Actual Behavior
Upon launching a new game, `carryon-server.toml` is generated in `/config/`. Nothing appears in `/defaultconfigs/`, and on loading a world without a `carryon-server.toml` in `/saves/<worldname>/serverconfigs/` one is made. If the `/config/` config is changed, the `/serverconfigs/` one is not updated, even if the `/serverconfigs/` is deleted. 

Pasting the `/serverconfig/` into `/defaultconfigs/` causes any new `/serverconfigs/` generated to match `/defaultconfigs/`. Old `/serverconfigs/` are not updated.

It appears that CarryOn now uses the `/defaultconfigs/` system normally, except it also generates a useless /config/ config.

### Steps to Reproduce
Open a new instance with CarryOn and Forge, then modify `/config/` and `/defaultconfigs/`, checking `/serverconfigs/` for changes.

### Version of Minecraft, Carry On, Forge
MC 1.15.2
Forge 31.2.49
CarryOn file carryon-1.15.2-1.13.0.5

**Comment by Tschipp** [comment]
This has been replaced by a common config in v2.0.0
