### ISSUE TITLE
Crash when attempting to open inventory while carrying mobs

### ISSUE THREAD

**Issue by ironsnake345** [Tschipp/CarryOn#301]
### Expected Behavior
Inventory opens normally, without crashing, or just doesn't open

### Actual Behavior
Game crashes when pressing the "open inventory" key while carrying a mob

### Steps to Reproduce
Step 1: pick up a mob
Step 2: press e
Step 3: crash

### Version of Minecraft, Carry On, Forge
Minecraft version: 1.16.5 (in a modpack, as stated below)
Carry On version: 1.16.5-1.15.3.13
Forge version: 36.0.42
Modpack: AutomationNation ver 1.3.0 (link: https://www.curseforge.com/minecraft/modpacks/automation-nation )

I'm not sure if this is an issue with this mod specifically, or with the modpack itself and how this mod interacts with the rest of the mods present. If I should be posting this to AutomationNation's issues page instead, please let me know, and if that's the case, sorry for the inconvenience.

### Screenshots encouraged
(Can't really screenshot the game crashing)

Link to crash log from NotEnoughCrashes: https://gist.githubusercontent.com/natanfudge/4503828f307846dc41b2667c6e70084e/raw/aa9dcced6dd4d9caadbdd24ddc8feea26f034e0f/crash.txt

**Comment by Tschipp** [comment]
Looks like an issue on the side of FancyMenu.

**Comment by ironsnake345** [comment]
Thanks for the input. I'll submit this to FancyMenu's mod page as an issue.

Sorry for not knowing how to read crash reports, haha
