### ISSUE TITLE
[1.16.5] Waystones Freeze Players when picking one up.

### ISSUE THREAD

**Issue by Cixon** [Tschipp/CarryOn#306]
### Expected Behavior
To carry waystone like a chest or perhaps not to at all.

### Actual Behavior
Frozen UI. Unable to open inventory and unable to place waystone.

### Steps to Reproduce
Install Latest Waystone mod and Carryon.
Place a waystone.
Try to pick it up.
See results.

### Version of Minecraft, Carry On, Forge
1.16.5
Forge: 36.0.42
CarryOn - v1.15.3.13

### Screenshots encouraged
![Screenshot (166)](https://user-images.githubusercontent.com/69068153/113488443-cc0d9180-9483-11eb-82c0-45dddd718149.png)

**Comment by belathus** [comment]
Intentionally getting myself killed helped a bit with this problem, but there is a phantom item I picked up that caused the problem again and I had to get myself killed again.

**Comment by Tschipp** [comment]
do /carryon clear

**Comment by Cixon** [comment]
> 
> 
> do /carryon clear

this is a good temporary fix. thank you.
