### ISSUE TITLE
Carried floor signs cannot be placed on walls, and vice versa

### ISSUE THREAD

**Issue by ChloeDawn** [Tschipp/CarryOn#308]
### Expected Behavior
Placing a carried sign should allow placing on the floor or a wall like regular sign placement

### Actual Behavior
A sign previously placed on the floor can only be placed on the floor when carrying, and vice versa

### Steps to Reproduce
Place a sign on the floor, carry it, attempt to place it on a wall

### Version of Minecraft, Carry On, Forge
Minecraft version: 1.16.5
Carry On version: 1.15.3.13
Forge version: 36.1.4

**Comment by Tschipp** [comment]
related to #287
