### ISSUE TITLE
TNT fuse is paused when carried

### ISSUE THREAD

**Issue by ChloeDawn** [Tschipp/CarryOn#309]
### Expected Behavior
Primed TNT to detonate when carried, continuing the fuse it had when it was picked up

### Actual Behavior
A primed TNT's fuse is paused until placed on the ground again

### Steps to Reproduce
Ignite a TNT block, immediately carry it

### Version of Minecraft, Carry On, Forge
Minecraft version: 1.16.5
Carry On version: 1.15.3.13
Forge version: 36.1.4

### Screenshots encouraged
![Screenshot of primed TNT being carried](https://i.imgur.com/LsE0MOe.png)

**Comment by ChloeDawn** [comment]
Furthermore, carrying TNT appears to reset the fuse upon placement

![Recording of primed TNT never detonating throughout multiple placements](https://i.imgur.com/7HCe710.gif)

**Comment by Tschipp** [comment]
That the fuse stops is intended, as I save the state of the entity when it was picked up, and don't tick the entity while carrying. However that the fuse resets upon placement seems strange. Probably smart to add primedtnt to the default blacklist.
