### ISSUE TITLE
[1.10.2] Incompatibility with Backport's Shulker Boxes

### ISSUE THREAD

**Issue by Wisecompany** [Tschipp/CarryOn#31]
I get an error while trying to pickup a Shulker Box from the [Backport](https://minecraft.curseforge.com/projects/backport) mod. 

Backport is only available for 1.10.2, so this shouldn't affect all versions of CarryOn. Just wanted to report the issue. 

Thanks for the great mod! Really helps with immersion.

**Comment by Tschipp** [comment]
Sadly, there is nothing I can do about that. CarryOn tries to find errors that happen during the removal of the TileEntity. If it finds any, it will not remove it. It's up to Backport to fix that.
