### ISSUE TITLE
Unable to config carriable blocks

### ISSUE THREAD

**Issue by WestPrime** [Tschipp/CarryOn#312]
### Expected Behavior

There is config that allows to blacklist carriable blocks

### Actual Behavior

Only client config without any useful settings

### Steps to Reproduce

Install the mod > Launch > Get disappointed

### Version of Minecraft, Carry On, Forge

Minecraft 1.16.4
Carry On 1.16.3-1.15.1.7
Forge 35.1.37

### Screenshots encouraged

![изображение](https://user-images.githubusercontent.com/69895016/115044523-0567e780-9eef-11eb-9c0f-f6a98648aedc.png)

**Comment by Tschipp** [comment]
The config is located in the world's config folder.
