### ISSUE TITLE
[1.16.5] Not being able to pick up Adjustable Crate from the Create Mod

### ISSUE THREAD

**Issue by ffuentesm** [Tschipp/CarryOn#313]
### Expected Behavior
Since the Adjustable Crate is a Tile entity, it should be able to be picked up.

### Actual Behavior
When I try to pick it up, it stays on the ground.

### Steps to Reproduce
Try to pick up the Adjsutabel Crate from the Create mod.

### Version of Minecraft, Carry On, Forge
Minecraft 1.16.5, carryon-1.16.5-1.15.3.13, Forge 36.1.4

**Comment by Tschipp** [comment]
I think create might be blacklisted, so that is intended, sorry.
