### ISSUE TITLE
Cutting Board dupe

### ISSUE THREAD

**Issue by FastHit** [Tschipp/CarryOn#314]
Pam's Harvestcraft Cutting Board is getting duped when picked up.
(the item is being carried but it also drop it on the ground, giving you additional 1 every time you pick it up)

that's the only block i found doing it, and i know that duping cutting board is pretty much useless, but i dont know what exactly causes it, so i reported it instead there is some other items that can be duped that way.

### Steps to Reproduce
1. place cutting board on the world.
2. pick it up with Shift Right-click.

### Version of Minecraft, Carry On, Forge
1.16.5 MC
36.1.2 Forge
1.15.3.13 Carry On

tested on Engineer's Life 2 and Stacia Expert modpacks.

**Comment by Tschipp** [comment]
How do you even place the cutting board? Can you give me the exact block registry name for it?

**Comment by smbarbour** [comment]
Cooking for Blockheads adds a block that uses the Pam's item for placement.
