### ISSUE TITLE
rainbow sheep jeb_ cycles through colors too quickly

### ISSUE THREAD

**Issue by Iguessthiswasinevitable** [Tschipp/CarryOn#317]
### Expected Behavior
rainbow sheep jeb_ cycles through colors at the same rate as usual

### Actual Behavior
rainbow sheep jeb_ cycles through colors very quickly, causing potential epilepsy risk

### Steps to Reproduce
name sheep "jeb_"
pick up sheep

### Version of Minecraft, Carry On, Forge
Minecraft 1.16.5
Forge 36.1.0
CarryOn carryon-1.16.5-1.15.3.13

**Comment by Tschipp** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/carry-on/files/3339297
