### ISSUE TITLE
Can't place Apothecary Cauldron

### ISSUE THREAD

**Issue by SSenZ0** [Tschipp/CarryOn#319]
### Expected Behavior

being able to place the apothecary cauldron from the reliquary mod

### Actual Behavior

Can't place apothecary cauldron from the reliquary mod

### Steps to Reproduce

pick up apothecary cauldron and try to place it down

### Version of Minecraft, Carry On, Forge

Minecraft 1.12.2
Carryon 1.12.3
Forge 14.23.5.2854
Reliquary 1.12.2-1.3.4.796

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/83184329/119066482-2afd7a80-b9e0-11eb-849b-1f0403ed70e1.png)

**Comment by Tschipp** [comment]
pls try updating carry on

**Comment by SSenZ0** [comment]
> pls try updating carry on

yup updating fixed.
