### ISSUE TITLE
Mod loading failure

### ISSUE THREAD

**Issue by PixusPanic** [Tschipp/CarryOn#321]
Hello; I think that the latest version of Carry On (1.15.4.14) is bugged since I've just downloaded it, and even without any other mods running, the game crashes; the previous version didn't do that, so I assume this might be an error with how it was compiled. An update to fix this would be greatly appreciated!

### Expected Behavior
The game loads up to the title screen.

### Actual Behavior
The game crashes upon loading the game with an error in load_registries.

### Steps to Reproduce
Download the latest version of Carry On, put it inside the mods folder and attempt to start up Minecraft.

### Version of Minecraft, Carry On, Forge
1.16.5, 1.15.4.14., 36.1.25

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/68515252/120904050-edbbfe00-c617-11eb-858e-19034f77c1f9.png)

**Comment by Tschipp** [comment]
Could you send me the full crash log?

**Comment by PixusPanic** [comment]
Sure thing!

[crash-2021-06-05_16.05.36-fml.txt](https://github.com/Tschipp/CarryOn/files/6603180/crash-2021-06-05_16.05.36-fml.txt)

**Comment by Corvus20** [comment]
Having the same issue

[crash-2021-06-05_16.18.59-fml.txt](https://github.com/Tschipp/CarryOn/files/6603181/crash-2021-06-05_16.18.59-fml.txt)

**Comment by Tschipp** [comment]
Alright I'll fix it asap

**Comment by Tschipp** [comment]
I've fixed it but curse is down, lol. Hopefully back soon
