### ISSUE TITLE
Carry On and First Person Models Incompatible

### ISSUE THREAD

**Issue by Hizakari** [Tschipp/CarryOn#322]
### Expected Behavior
Entities should show in hands when carrying, both in first and third person

### Actual Behavior
Doesnt show entities in first person when carrying them but does in third 

### Version of Minecraft, Carry On, Forge
1.16.5

**Comment by Tschipp** [comment]
what is the mod id of the first person mod?

**Comment by Meskino** [comment]
> what is the mod id of the first person mod?

firstperson

**Comment by Hizakari** [comment]
The mod ID is 274259

**Comment by Hizakari** [comment]
Oops, the mod id for firstperson is 333287

**Comment by surfishs** [comment]
> 

I have the same problem
