### ISSUE TITLE
Named animals' name tags don't rotate

### ISSUE THREAD

**Issue by WenXin20** [Tschipp/CarryOn#326]
### Expected Behavior
- Either the name tag shouldn't render, or it should rotate with the player

### Actual Behavior
- The name tag of a named mob doesn't rotate.

### Steps to Reproduce
- Name a mob with a name tag
- Pick it up
- Spin the player

### Version of Minecraft, Carry On, Forge
- `Minecraft v1.16.5`
- `Forge v36.1.32`
- `Carry On v1.15.5.15`

### Screenshot
![2021-06-21_22 32 27](https://user-images.githubusercontent.com/12000593/124858897-85dd3800-df74-11eb-99c9-59c151578c62.png)

**Comment by Tschipp** [comment]
Are you using any other mods?

**Comment by WenXin20** [comment]
Yes, the main one to mention would be Sodium Reforged.
