### ISSUE TITLE
How to Make The Cake Have The Right State After Being Put Down?

### ISSUE THREAD

**Issue by Charlobo** [Tschipp/CarryOn#327]
### Expected Behavior
The eaten cake will remain in its eaten state after it is picked up and put down again.

### Actual Behavior
The eaten cake returns to an uneaten state after being put down.

### Version of Minecraft, Carry On, Forge
Minecraft:1.16.5
Carry on:1.15.5.15
Forge:36.1.32
### Screenshots encouraged
![2021-07-13_20 58 40](https://user-images.githubusercontent.com/51576635/125455699-2736728d-53ec-4a82-ada6-72844a3e0c4b.png)
![2021-07-13_20 58 48](https://user-images.githubusercontent.com/51576635/125455706-5376504d-ed54-4ff3-a550-7daab006f945.png)
![2021-07-13_20 58 53](https://user-images.githubusercontent.com/51576635/125455723-8176a878-0c1d-44ee-b149-52024002daec.png)

**Comment by Tschipp** [comment]
This is essentially the same issue as #287, to which I have found no fix yet

**Comment by Tschipp** [comment]
Fixed with #287
