### ISSUE TITLE
Ability to pick up humanoid mobs

### ISSUE THREAD

**Issue by red1134** [Tschipp/CarryOn#329]
Humanoid mobs cannot be picked up and no option in the config seems to be able to allow this. This includes things like CustomNPCs, MCA villagers, and most other mobs that appear to use the player model. Is this by design somehow?

### Expected Behavior
The mob is picked up.

### Actual Behavior
The mob is not picked up.

### Steps to Reproduce
Try to pick up any humanoid mob.

### Version of Minecraft, Carry On, Forge
1.12.2, 1.12.4.16, unsure

EDIT: Missed the max height property in config

**Comment by 7eggert** [comment]
Thanks for posting the reason. It's not immediately obvious.
