### ISSUE TITLE
[Feature Request] Be able to push button or activate Waystones while carrying

### ISSUE THREAD

**Issue by danemorgan** [Tschipp/CarryOn#330]
It would be cool if we could push buttons while carrying something to open doors and the like. I'm not sure if this is even possible but thought I would ask. Additionally, when using Waystones, the Waystone is activated with the use button too, so you cannot go through the Waystone while carrying anything. Could the place button be remapped to allow for this?

**Comment by Tschipp** [comment]
I don't add specific behavior with other mods, so this is out of scope.
