### ISSUE TITLE
Mekanism wind generator bug

### ISSUE THREAD

**Issue by WizardlyBump17** [Tschipp/CarryOn#331]
### Expected Behavior
Use carry to replace the wind generator from Mekanism

### Actual Behavior
it crashes the game

### Steps to Reproduce
Too confusing to write here, please see the video

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On: 1.11.1
Forge: 14.23.5.2854

### Screenshots encouraged
https://www.youtube.com/watch?v=AtU_qTgFFMM

Also, I would to know if there is a way to fix that in a existing world because you cant join the world anymore (after the "loading terrain" the game crashes again) and I have a server that I play with a friend and I want to keep playing :3

**Comment by Tschipp** [comment]
hm so depending on what crashes, you might be out of luck. I assume the block has been placed in the world, and is now erroring. Sadly I think the only thing you can do is open the world in mcedit and remove the block there. Then, add the registry name (problably something like "mekanism:wind_generator" ) to the blacklist.
