### ISSUE TITLE
Unable to carry anything, modded nor vanilla, even after changing controls

### ISSUE THREAD

**Issue by LoreleiFox** [Tschipp/CarryOn#334]
### Expected Behavior
pick up a chest or mob

### Actual Behavior
does not pick up

### Steps to Reproduce
click LSHIFT on mob or chest, key does not conflict

### Version of Minecraft, Carry On, Forge
1.12.2; carryon-1.12.2-1.12.4.16; 1.12.2-forge-14.23.5.2855

**Comment by LoreleiFox** [comment]
![modlist](https://user-images.githubusercontent.com/88848647/129237238-c3ba6d5f-b8cb-4f11-9a2b-4d35b250ee33.PNG)

currently testing it on vanilla but here is my mods list

**Comment by Tschipp** [comment]
You need to press the carry key AND right click to pick something up. Are you doing that?

**Comment by LoreleiFox** [comment]
i didnt know i had to right-click too. thank u

**Comment by CuteChibiMoon** [comment]
hey it's not working for me idk what to do, when I shift and press the button for the carry on mod it just opens up the crate that I'm trying to pick up

**Comment by LordDarovit** [comment]
Yep. Using the mod as described, and it just doesnt work at all. It was working for hours before, now it just stopped. Not the first time I had this issue. Dont really know whats causing it. Entirely random.

**Comment by LordDarovit** [comment]
> hey it's not working for me idk what to do, when I shift and press the button for the carry on mod it just opens up the crate that I'm trying to pick up

Yep. Using the mod as described, and it just doesnt work at all now. It was working for hours before, now it just stopped. Not the first time I had this issue. Dont really know whats causing it. Entirely random.
