### ISSUE TITLE
1.12 first person rendering error when using optifine shader and replay mod

### ISSUE THREAD

**Issue by MW1Z** [Tschipp/CarryOn#335]
### Expected Behavior
First person rendering normal

### Actual Behavior
First person rendering error

### Steps to Reproduce
1.open with optifine shader and replay mod
2.carry on display error
### Version of Minecraft, Carry On, Forge
Minecraft 1.12.2
Carry On 1.12.4.16
Forge 14.23.5.2855
### Screenshots encouraged
![2021-08-19_13 45 56](https://user-images.githubusercontent.com/75073815/130041737-e377f24d-6972-4800-b165-c78c7921bb9e.png)
![2021-08-19_13 46 10](https://user-images.githubusercontent.com/75073815/130041748-fbfc00ba-d3f6-4eb7-a1ad-3cb5cac238a9.png)

**Comment by Gunner76th** [comment]
Does the issue happen if Optifine is present? If not, then this is not an issue with the author's mod, but an issue that needs to be reported to Optifine so they can work a fix into their code.

**Comment by Tschipp** [comment]
Yeah, no doubt that optifine is installed if they use shaders. It could also be an issue with replay mod. Does the issue occur with optifine installed but without shaders?
