### ISSUE TITLE
Serious bug after player die

### ISSUE THREAD

**Issue by Icenodb** [Tschipp/CarryOn#339]
### Steps to Reproduce
①Enter a server
②gamerule keepInventory true
③Pick up an animal
④Be attacked to death
⑤The arm disappeared
⑥log out the server
⑦Try to log in to the server again
⑦Unable to log in to the server

### Version of Minecraft, Carry On, Forge
1.16.5；1.15.5.15；36.2.2

**Comment by Tschipp** [comment]
This only happens on a server?

**Comment by rostikmak** [comment]
Hello, i has the same problem. Please fix it :(
This only server problem.
Help :c

**Comment by Tschipp** [comment]
Is there a log?
