### ISSUE TITLE
Not rendering entity/blocks on 1.12.2

### ISSUE THREAD

**Issue by bigshadowesp** [Tschipp/CarryOn#341]
### Expected Behavior
Pick up any block or entity and see it on 2rd or 3rd person.

### Actual Behavior
Is not rendering on 2rd or 3rd person.

### Steps to Reproduce
Pick up a block or entity and press F5

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
CarryOn: v1.12.2 or v1.12.4.16 (Exact issue)
Forge 14.23.5.2855
Optifine: 1.12.2 HD-U_G5

ModList:
buildcraftlib@7.99.24.8
cyclopscore@1.6.0
mclib@2.3.4
gokistats@1.2.8.3
zawa@1.12.2-2.1.3
creativecoredummy@1.0.0
openmods@0.12.2
buildcraftenergy@7.99.24.8
futuremc@0.2.6
betternether@0.1.8.6
ctm@MC1.12.2-1.0.2.31
evilcraft@0.10.78
neid@1.5.4.4
fencejumper@1.0.5
bookshelf@2.3.590
forgelin@1.8.3
atum@2.0.17
xreliquary@1.12.2-1.3.4.796
uteamcore@2.2.5.147
darkutils@1.8.230
morpheus@1.12.2-3.5.106
waila@1.8.26
props@2.6.3.7
carryon@1.12.2
emoticons@1.0.1
mcjtylib_ng@3.5.4
malisisdoors@1.12.2-7.3.0
architecturecraft@@VERSION@
mcwbridges@1.0.6
malisiscore@1.12.2-6.5.1-SNAPSHOT
torchmaster@1.8.4.84
usefulbackpacks@1.5.4.85
ptrmodellib@1.0.5
ambientsounds@3.0
buildcraftsilicon@7.99.24.8
openmodscore@0.12.2
msmlegacy@@VERSION@
toughnessbar@@VERSION@
mcwfences@1.0.0
vehicle@0.44.1
containerfix@1.0
gvc@1.2.5
evilcraftcompat@1.0.0
roguelike@1.8.0
buildcraftbuilders@7.99.24.8
buildcraftfactory@7.99.24.8
otgcore@1.12.2-v9.3
torchbandolier@0.1.1
FML@8.0.99.99
obfuscate@0.4.2
tombstone@4.4.7
customnpcs@1.12
buildcraftcompat@7.99.24.8
cfm@6.3.1
codechickenlib@3.2.3.358
geckolib3@3.0.0
playerrevive@1.0
buildcraftcore@7.99.24.8
heroicarmory@1.1.3
cucumber@1.1.3
trashslot@8.4.10
mca@6.1.0
ebwizardry@4.3.4
jei@4.16.1.301
buildcrafttransport@7.99.24.8
custommainmenu@2.0.9.1
justenoughbuttons@1.12-1.2
reap@1.5.2
artemislib@1.0.6
mcp@9.42
journeymap@1.12.2-5.7.1
comforts@1.4.1.3
artifacts@1.12.2-1.2.3
travelersbackpack@1.0.35
betteranimalsplus@9.0.1
harvestcraft@1.12.2zb
walljump@1.3.2
traverse@1.6.0
forge@14.23.5.2855
buildcraftrobotics@7.99.24.8
mysticalagriculture@1.7.5
openblocks@1.8.1
variedcommodities@1.12.2
minecraft@1.12.2
silentlib@3.0.13
baubles@1.5.2
stupidthings@1.1.6
creativecore@1.10.0
astikorcarts@1.12.2-0.1.2.7
extrautils2@1.0
securitycraft@v1.8.23.2
inventoryhud@3.4.0
opframe@1.4.0
tbintegration@1.0.1
appleskin@1.0.14
chisel@MC1.12.2-1.0.2.45
recipehandler@0.13
aether_legacy@1.5.3.2
bookworm@1.12.2-2.5.2.1
byg@1.7.1
cqrepoured@2.5.3B
chiselsandbits@14.33
immcraft@1.6.0

### Screenshots encouraged

![](https://i.gyazo.com/eb20cd5f5968d14885c8b3c0e9a17a9a.png)
![](https://i.gyazo.com/6ed118489b07486f73b7d9daa291901c.png)

**Comment by Tschipp** [comment]
Does it work without optifine? Also, does any of these mods replace the player model?

**Comment by xSmallJeffx** [comment]
> Does it work without optifine? Also, does any of these mods replace the player model?

Hello, I'm also having the same problem, I started to filter the mods and discovered that when I use the mod "Emoticons" (dancing emotes)makes objects invisible when grappled in third person and my friends can't see what another player grabs either

**Comment by ArchiveM** [comment]
Hello, a question has your problem fixed and if it is not fixed, I had the same problem and they are for 2 reasons 1. It could be because of the mod emoticons you would have to go to configurations from mod options or from the 0 button and look for the one Emoticons comes out and there you look for something that says: non stop animation and there you deactivate it and if you continue with the problem it could be for reason 2. What would it be if you had the kidnapp mod and if you have it you would have to delete it, those are the only solutions that I found ... this was translated by google so if it was not understood well you could comment on the doubt
