### ISSUE TITLE
Crash when try to carry a NPC

### ISSUE THREAD

**Issue by PabloAlbu** [Tschipp/CarryOn#342]
### Expected Behavior
We have the mod "Taterzens (Forge)". Im trying to carry a NPC to see what will hapen. But... the server crash from all the neares players.

### Steps to Reproduce
Try to carry a NPC from this mod. 

### Version of Minecraft, Carry On, Forge
FORGE 1.16.5

### Screenshots encouraged
Not needed.

Sorry for my bad english.

**Comment by Corbi** [comment]
Same problem here, and add taterzens:npc to the black list doesn't seem to work.
