### ISSUE TITLE
Suggestion: When you carry a spawner, it keeps spawning mobs

### ISSUE THREAD

**Issue by Porcy** [Tschipp/CarryOn#344]
As title says.
Just imagine you have both hands taken, so no swords, and you are slowed down. Would make carrying a spawner much more, hum, interesting :)
Maybe add this as a config option though.

**Comment by Tschipp** [comment]
This is a nice idea, but this is done by a mod similar to carry on (Charset), so I won't add it, sorry

**Comment by Porcy** [comment]
Charset's latest version is for 1.10.2 :( Oh well!
