### ISSUE TITLE
[1.12] Log spam after last update

### ISSUE THREAD

**Issue by Sereath** [Tschipp/CarryOn#347]
### Expected Behavior
No server log spam.

### Actual Behavior
Server is getting spammed with:
![image](https://user-images.githubusercontent.com/54506307/138431629-5120b019-894e-43a6-b257-4bf3e6477fda.png)

### Steps to Reproduce
Install last 1.12.2 update: 1.12.6.19

### Version of Minecraft, Carry On, Forge
1.12.2, 1.12.6.19, 2854

https://gist.github.com/Aeron216/fdee65b386e5b9378b5ec1264e5617c2

**Comment by Sereath** [comment]
I actually skipped version 1.12.5.18 so I just tried it and Im getting the same log spam. Previously I had been using 1.12.4.16.

**Comment by Tschipp** [comment]
Ah damn it

**Comment by Tschipp** [comment]
Fixed it
