### ISSUE TITLE
[help] Chest Slowness bug with Quark Oddities

### ISSUE THREAD

**Issue by SmithyWithy** [Tschipp/CarryOn#349]
### Expected Behavior

Chest is supposed to be given to player

### Actual Behavior

Chest is given to player but is invisible and cannot be removed.

### Steps to Reproduce
1. Have a friend carry a chest
2. Kill them while they are holding it
3. Hit their Totem of Holding once
now you have infinite slowness

### Version of Minecraft, Carry On, Forge
Valhesia 3, 1.16.5 
Forge 36.2.8
carryon-1.16.5-1.15.5.15
along with Quark Oddities

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/69119991/138581965-764faf73-9bf9-4806-8b17-133945927687.png)

**Comment by Tschipp** [comment]
Is this on a server?

**Comment by SmithyWithy** [comment]
> Is this on a server?

 my bad forgot about this issue
 but yeah, i managed to fix the issue 
 by dying and letting my friend hit my totem, the chest then appeared in his hands.
