### ISSUE TITLE
Compatibility with Tardis Mod

### ISSUE THREAD

**Issue by DrSigma4164** [Tschipp/CarryOn#350]
Hi! Could you tell me how to add a specific entity to a blacklist? In the Tardis Mod there is a entity "tardis:interior_door" and here it should not rise with Carry on.

### Version of Minecraft, Carry On, Forge
Minecraft: 1.16.5
Carry On: 1.15.5.15
Forge: 36.2.8

**Comment by Tschipp** [comment]
you need to find the serverconfig for carryon (in the world's config folder) and then add "tardis:interior_door" to the blacklist

**Comment by DrSigma4164** [comment]
Great, it worked, thank you. And is it possible to make this blacklist used for any world, that is, not to climb into the configuration file of each created world and not to change there, but for example to change it with a datapack or otherwise?

**Comment by Tschipp** [comment]
Yes, add that config file into the "defaultconfigs" folder which is located next to the configs folder.
