### ISSUE TITLE
Can´t pick chest

### ISSUE THREAD

**Issue by A-pashe** [Tschipp/CarryOn#351]
###Expected Behavior
pick up entities and chest
###Actual Behavior
I only can pick entities
###Steps to Reproduce
try carrying chest
### Version of Minecraft, Carry On, Forge
minecraft 1.12.2, forge 14.23.5.2855, carry on 1.12.6.20

**Comment by Fog7778** [comment]
Did you have both your main hand and off-hand empty, if not empty you cant pick up the chest.
