### ISSUE TITLE
Cant pick up spawners

### ISSUE THREAD

**Issue by Fog7778** [Tschipp/CarryOn#353]

**Comment by Ace-7642** [comment]
Im having the same problem and i think some mods dont work with carry on
But imma try to pick one up in vanilla and see if that works but im pissed that i cant pick up spawners rn

**Comment by Ameno-Sagiri** [comment]
It's configurable in the settings files for the mod. It's all on you, make it happen.

**Comment by Tschipp** [comment]
Are you using any other mods?
