### ISSUE TITLE
[1.16.5] Crash when going third person with held mob in armor.

### ISSUE THREAD

**Issue by Darkmega18** [Tschipp/CarryOn#354]
### Expected Behavior
I can look at myself in creative to lol at the mob that I'm holding.

### Actual Behavior
Instant crash when hitting F5. sadness.

### Steps to Reproduce
Go pick up a mob who has spawned decked out in armor. 
potentially enchanted armor. Not sure on the specifics there.
But when you do, it works fine. until you try to F5 and look at yourself holding the mob. which instantly crashes.

Only guessing that armor in the contributing factor based on the crash report and that it happens mostly when I go to pick up apotheosis bosses or mobs that have gear on them while in creative mode.

### Version of Minecraft, Carry On, Forge
MC 1.16.5
Forge: 36.2.8
Carry on: 1.16.5-1.15.5.15

Among lots of other things. It's done on my modpack: "Order of All Creation: Relic Hunters". There's probably some kind of incompatibility I'd have to guess?

### Screenshots encouraged
can't. but heres a full crash log
[crash-2021-11-24_20.59.13-client.txt](https://github.com/Tschipp/CarryOn/files/7594646/crash-2021-11-24_20.59.13-client.txt)
.

**Comment by Darkmega18** [comment]
that took a hot minute. lol.

**Comment by Tschipp** [comment]
yeah, heh. I only found the fix today when working on 1.19.2... 😅

**Comment by Darkmega18** [comment]
ah well, better late than never. Haven't come across the crash when looking at myself in 1.19.2 yet though. although I only did looked at myself a few times and they weren't enchanted/geared.

anyways, GG.
