### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dylan-jara** [Tschipp/CarryOn#356]
### Expected Behavior
Expected behavior is that minecraft does not crash

### Actual Behavior
Minecraft crashes, but the server does not, only the client and I don't know why it is caused but it says something about what Carry On is, according to what it says in the crash report.

### Steps to Reproduce
Enter the server and it just crashes

### Version of Minecraft, Carry On, Forge
1.16.5 / carryon-1.15.2-1.13.0.5 / Forge 36.2.4

### Screenshots encouraged
https://mcpaste.io/c18a650505d5f03

**Comment by Tschipp** [comment]
Seems the log is gone, if still relevant please repost with current log.
