### ISSUE TITLE
You can pick up tamed donkeys

### ISSUE THREAD

**Issue by ZebulanStanphill** [Tschipp/CarryOn#357]
### Expected Behavior

You can pick up neither horses nor llamas, so logically you shouldn't be able to pick up donkeys.

### Actual Behavior
You can pick up donkeys if you shift-right-click them. Notably, this only happens with donkeys - mules can't be picked up.

### Steps to Reproduce

- Tame a donkey.
- Stand very close to the donkey.
- Sneak-use (shift-right-click) the donkey.

### Version of Minecraft, Carry On, Forge
- Minecraft 1.16.5
- Forge 36.2.20
- Carry On 1.16.5-1.15.5.15

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/19592990/146707529-b20779b3-1279-4e05-a9ac-9ad29b602dfc.png)

**Comment by Tschipp** [comment]
This is not a quetion of logic, rather of config. It seems donkey are just small enough to be able to be picked up.
