### ISSUE TITLE
[1.18.1] Carry On Deletes Anything Inside Container When Picked Up

### ISSUE THREAD

**Issue by Darkosto** [Tschipp/CarryOn#359]
### Expected Behavior
I would like to keep my items please. 

### Actual Behavior
Your mod takes my items away from me and keeps them for itself. 

### Steps to Reproduce
-4. Be born into this world
-3. Invent a fusion reactor or borrow someone elses
-2. Buy or acquire electricity
-1. Turn on your computer
0. Put down chest or barrel
1.Put items in chest or barrel
2. Pick up chest with carry-on
3. ???
4. Open chest
5. Items gone!

### Version of Minecraft, Carry On, Forge
MC: 1.18.1
Forge: 39.0.8
Carryon: 1.17.03

No, but seriously this mod deletes anything picked up. I tested with only forge and carryon installed too.

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/10309699/147372961-d72b4860-4ade-429f-8c38-e9b5052ec1ef.png)

**Comment by Tschipp** [comment]
Oh no, that's bad
