### ISSUE TITLE
1.18.1 InterModComms does not work

### ISSUE THREAD

**Issue by Edivad99** [Tschipp/CarryOn#361]
Since 1.18.1 I cannot send the blocks to be put in denylist with InterModComms.
In 1.16 it worked, I don't know if anything has changed since 1.18. The code is called in the FMLCommonSetupEvent:
https://github.com/Edivad99/ExtraStorage/blob/26f7650a7dd3774edcc9e55322de10712b281236/src/main/java/edivad/extrastorage/setup/ModSetup.java#L64
This is where I send the info with InterModComms:
https://github.com/Edivad99/ExtraStorage/blob/26f7650a7dd3774edcc9e55322de10712b281236/src/main/java/edivad/extrastorage/compat/CarryOnIntegration.java

Minecraft version: 1.18.1
Forge version: 39.0.9
CarryOn version: 1.17.0.5

**Comment by Tschipp** [comment]
strange... I didn't change anything about that really. Did it work in 1.17?

**Comment by Tschipp** [comment]
Also, I didn't know anyone even used IMC for CarryOn :D This is the first time I'm hearing of it

**Comment by Edivad99** [comment]
I don't know, my mod is a refined storage addon that was not developed in 1.17, so I skipped 1.17 development

**Comment by Edivad99** [comment]
Ok, I fixed by using the tags

**Comment by hammertater** [comment]
CarryOn is using `FMLDedicatedServerSetupEvent` to process IMC stuff, but - according to the 1.19 docs - this event is called before `InterModEnqueueEvent`. Also I'm not sure whether dedicated server events are fired on integrated servers. IMC messages should be handled in `InterModProcessEvent` instead

> Also, I didn't know anyone even used IMC for CarryOn :D This is the first time I'm hearing of it

Thanks for adding the IMC stuff, I'm very happy it's there :) This thread gives me hope that maybe someone out there will ever use the API stuff I've been supporting, haha

edit: also, the wiki page https://github.com/Tschipp/CarryOn/wiki/IMC-support-for-Modders was super helpful! The 1.13 example "works" for 1.19 (for sending messages... hopefully in the future they will get processed)

**Comment by millennIumAMbiguity** [comment]
When calling `InterModComms.sendTo` from the `enqueueModComms` event, it does not work for me. But it does work when I call it from within the initialization. (1.19.2)
