### ISSUE TITLE
[1.16.5] I can open inventory in moment of taking block or entity

### ISSUE THREAD

**Issue by immails** [Tschipp/CarryOn#364]
### Expected Behavior
My inventory shouldn't open and i cannot take block or entity in offhand by pressing F

### Actual Behavior
My inventory opened and i can take block or entity in offhand by pressing F

### Steps to Reproduce
Pick up block or entity and then QUICKLY press E or F (for offhand swap). 

### Version of Minecraft, Carry On, Forge
1.16.5, 1.15.5.15, 36.2.20

### Screenshots encouraged

https://user-images.githubusercontent.com/45512165/149652188-34564ea7-b43b-4eb0-98f1-23de4c967fb7.mp4

**Comment by immails** [comment]
:(

**Comment by Tschipp** [comment]
This is a limitation of the current system.

**Comment by Tschipp** [comment]
This has been fixed on 1.19.2+
