### ISSUE TITLE
Crash when interacting with interface

### ISSUE THREAD

**Issue by ghost** [Tschipp/CarryOn#365]
### Expected Behavior
I expected to be unable to interact with interfaces [I thought his would be a feature of the mod]
OR, maybe be able to interact with interfaces, because it makes life much easier

### Actual Behavior
The game tries to open the interface anyway, crashing as a result.
- You might sometimes see the interface weirdly positioned at the side of your screen in a frozen state, followed by a crash report.

### Steps to Reproduce
Pick something up -  try to interact with a Crafting Table, Villager job-blocks, a Smoker or some other block with an ''interface'' - and it will crash the game.

### Version of Minecraft, Carry On, Forge
1.18.1 - latest versions, up to date with everything.

### Screenshots encouraged
Hard to get a screenshot of a crash, but hope this helps:
https://imgur.com/a/Dcsfcwi

Here is a link to the crash-report file:
https://drive.google.com/file/d/1ODpkQr1FM_PHJTiAeKhPx1unbyXSMTwh/view?usp=sharing

Hope this helps!

**Comment by CDAGaming** [comment]
Had this same issue, had to remove it from my server when several users crashed from this.
