### ISSUE TITLE
Cant pick up chests

### ISSUE THREAD

**Issue by jarocajavi** [Tschipp/CarryOn#366]
### Expected Behavior

I want move my items

### Actual Behavior

I can't move my items

BUT
Can pick up everything else
I don't see anything wrong in the config file.

### Steps to Reproduce

The config file is restarted to default, no changes

### Version of Minecraft, Carry On, Forge
Forge-1.18.1-39.0.64
Carryon-1.18.1-1.17.0.7]

Thanks for the help!

EDIT: I just found the issue comes to another mod, so is compatibility, when found it i tell wich mod is.

Found it! The problem is with [Ht's TreeChope](url=https://www.curseforge.com/minecraft/mc-mods/treechop)
Hope solve the uncompatibility

**Comment by jarocajavi** [comment]
https://github.com/hammertater/treechop/issues/105 just 3 hours ago haha, maybe the problem is the other mod.

**Comment by hammertater** [comment]
It's fixed on my end as of TreeChop 0.15.6. Sorry about that.

**Comment by Tschipp** [comment]
ok thanks, I was confused about this
