### ISSUE TITLE
Can't pickup blocks

### ISSUE THREAD

**Issue by PunkPun** [Tschipp/CarryOn#367]
I'm working on a 1.18.1 modpack and CarryOn doesn't seem to work for blocks (chests), at all. However I am able to pick up any mob I like

So my question is, are there mods that are known to be incompatible with CarryOn?

**Comment by Tschipp** [comment]
Please check out any of the issues I just closed recently and see if the apply here

**Comment by PunkPun** [comment]
It applies. Updating TreeChop fixed it.

A bug I just noticed gets fixed on the same day. What a time to be alive
