### ISSUE TITLE
Picking Up Custom NPCs Kills Them

### ISSUE THREAD

**Issue by RaliaTheWolf** [Tschipp/CarryOn#37]
I have this CNPC chicken and I wanted to carry it to a different pen and it died... I'm not sure if there's a way to fix that, but it would be pretty helpful if there is!

I'm in 1.11.2 if that helps.

**Comment by Tschipp** [comment]
Unfortunately no, CustomNPC's uses a different setDead method which is used to remove the entity from the world without drops & smoke and such.

**Comment by RaliaTheWolf** [comment]
Ah okay. Thanks for the explanation!
