### ISSUE TITLE
Can't see what I'm holding

### ISSUE THREAD

**Issue by Rusticz** [Tschipp/CarryOn#370]
### Expected Behavior
It's supposed to show what me or someone else is holding

### Actual Behavior
I can't see what anyone is holding. Only when I'm in first person and it's in my hands. Any other time I can't see it. I also can't see when it's on my head but I can see when it's on someone else's head. 

### Steps to Reproduce
Pick something up?

### Version of Minecraft, Carry On, Forge
1.16.5 using it on Better Minecraft [forge]

**Comment by Tschipp** [comment]
What other mods are you using? This sounds like a cross-mod conflict.
