### ISSUE TITLE
Aquaculture 2 I couldn't release fish

### ISSUE THREAD

**Issue by Ashtar084** [Tschipp/CarryOn#371]
### Expected Behavior

when I caught a fish from Aquaculture 2 I couldn't release it anymore, and my character was too slow with nothing to do... can you please take a look?

### 
### Version of Minecraft, Carry On, Forge
1.18.1

**Comment by Tschipp** [comment]
In case this happens again, you can do /carryon clear to remove it. You should be able to place it on solid ground though
