### ISSUE TITLE
Can I remove blacklisted Block and entities 

### ISSUE THREAD

**Issue by RetroWave1736** [Tschipp/CarryOn#375]
This isnt an issue but is there a way for me to make all blocks and entities white listed? Im just asking because this youtuber did it and he   
edited the files that turned off the black list https://www.youtube.com/watch?v=41g50oddlNk . SO if there is a way to do this, please tell me.

**Comment by Tschipp** [comment]
you just enable "pickupAllBlocks" in the server config
