### ISSUE TITLE
i can't carry villagers

### ISSUE THREAD

**Issue by MAXIS05** [Tschipp/CarryOn#376]
I can't lift the villagers or other entities that have trade, I play on a server with my friends and they can lift them, holding shift and right click what it does is open the trade interface

**Comment by KynLeg** [comment]
You need to change the settings for height to 3.5 and then you can pick them up

**Comment by Comm0ns** [comment]
> 

How do I do this?

**Comment by LegendaryLogan1** [comment]
if you have curseforge, then you go to C:users/[your user here]/curseforge/minecraft/instances/[profile name here]/config
then find the mods .cfg file there

**Comment by Tschipp** [comment]
To be able to pick up larger mobs, you need to set the maxEntityHeight in the config to something larger than 2, and smaller than 10. The config is located in CarryOn's server config (which is located inside of the world's serverconfig folder).
