### ISSUE TITLE
Carry On and FirstPeronModel

### ISSUE THREAD

**Issue by NightSharp** [Tschipp/CarryOn#377]
### Expected Behavior
To show arms and what I carry on when I hold up something with Carry On, In First-Person (F5 Default)

### Actual Behavior
Show nothing about arms and the carrying-on, just air in First-Person

In Third-Person it works properly.

### Steps to Reproduce
Install [FirstPersonModel](https://www.curseforge.com/minecraft/mc-mods/first-person-model), [NotEnoughAnimations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations) & CarryOn
Enter into a world and carry on - keep two hands empty, press SHIFT(Default) and Right Click traget - something (like chest)
Use F5 to switch Person-View

### Version of Minecraft, Carry On, Forge
MC 1.18.x (Both 1&2)
- For 1.18.2
Forge 40.0.32 & 39.1.2 (1.18.1)
Carry On 1.17.0.8
- For 1.18.1 
Forge 39.1.2
Carry On 1.17.0.7

### Screenshots encouraged
- Third Person (properly)
![2022-03-29_22 43 33](https://user-images.githubusercontent.com/9748063/160647014-ed489915-bc1f-4191-be4f-541b80d3b31c.png)
![2022-03-29_22 43 40](https://user-images.githubusercontent.com/9748063/160647077-a4fbff04-655a-4bdf-adcd-554021af2976.png)
- First Person (nothing but air)
![2022-03-29_22 43 53](https://user-images.githubusercontent.com/9748063/160647191-454ef11b-81e0-4252-a444-774d1c8d4148.png)

**Comment by Blunder-G** [comment]
Same issue, no solutions yet..
