### ISSUE TITLE
Carry On / Locks compatibility issue

### ISSUE THREAD

**Issue by Krampus69** [Tschipp/CarryOn#378]
Hello hello 👋 
My team and I are having an issue in our modpack, we'd like to add Carry On in it but it is not compatible with Locks for now (It IS but you can remove the lock on chests by picking it up, so that's kind of OP).
Just to be clear : Locks is a mod that adds locks to the game
[Locks page](https://www.curseforge.com/minecraft/mc-mods/locks)

### Expected Behavior

Locked chests shouldn't be able to be picked up to prevent cheese. If a chest has a lock on it, you shouldn't be able to pick it up.

### Actual Behavior

Locked chests can be picked up with Carry On, this will automatically remove the lock on it and allow the player to open the chest effortlessly.

### Steps to Reproduce

- Download Carry On 1.16.5
- Download Locks 1.16.5
- Put any lock on a chest (ctrl+right click on the front of the chest)
- Try to pick it up with Carry On
- Voila ! The lock will instantly break and drop on the floor.

### Version of Minecraft, Carry On, Forge

- Minecraft 1.16.5
- Forge 36.2.23
- carryon-1.16.5-1.15.5.22
- locks-1.16.5-3.0.3

### Screenshots encouraged

Here I even made you a gif to see how easy you can remove the lock 👍

[Here](https://media2.giphy.com/media/vnEBC5r37aSuIcmWmf/giphy.gif?cid=790b76111b08672a993f7e3c15d7b5954f316a64506e5d25&rid=giphy.gif&ct=g)

Just so you know, we are big fans of your mod we really love Carry On. Thanks for your amazing work, hope to see more of it soon :)
Have a nice day

**Comment by Tschipp** [comment]
Interestingly enough, it works out of the box with Locks in 1.12.2... I wonder what changed. I'll look into it.

**Comment by Krampus69** [comment]
Hello :wave:
I was wondering if there had been any improvements regarding this issue

**Comment by Krampus69** [comment]
Hello again 👋 
So this is gonna be kinda awkward but...It actually doesn't glitch on survival.
The "issue", if I could call it like that now, is only on creative, which means it's not really an issue at all.

I'm sorry for the bother, I think this issue can be closed now. Thank you for you work as always 🙏

**Comment by Tschipp** [comment]
Ah okay yeah that makes sense. Many restrictions only apply to survival players.
