### ISSUE TITLE
Blacklist Botania Stuff

### ISSUE THREAD

**Issue by tyler489** [Tschipp/CarryOn#38]
Botania mana pools cant be picked up and they lose all Mana. Botania flowers revert to a flower that says "Unobtanible Please report to the botania dev"

**Comment by Tschipp** [comment]
Ok, botania will be blacklisted by default.

**Comment by mbelrose** [comment]
Also had trouble with the Botania "mana enchanter" block, could not pick up, but I'm only on 1.7

**Comment by Tschipp** [comment]
Please update to the latest version

**Comment by mbelrose** [comment]
It's the Modern Skyblock modpack, so it's a bit ugly to do so. I'll just not do that again. Anyway, thanks for responding, and for the really useful mod
