### ISSUE TITLE
Crashes server when picking up Collapsible Block from FramedBlocks mod by XFactGD

### ISSUE THREAD

**Issue by KevinGliniecki** [Tschipp/CarryOn#380]
### Expected Behavior
Shift+Right Click to pick up block

### Actual Behavior
Shift+Right Click to picks up the block to yourself, but all mobs freeze as the sever hard crashes

### Steps to Reproduce
Place Collapsible Framed Block and shift + right click on it

### Version of Minecraft, Carry On, Forge
1.18.1, carryon-1.18.1-1.17.0.7.jar, Forge 39.1.2

**Comment by KevinGliniecki** [comment]
https://www.curseforge.com/minecraft/mc-mods/framedblocks

**Comment by KevinGliniecki** [comment]
Nevermind, we'll just blacklist the mod from it

**Comment by XFactHD** [comment]
Referencing this here for completeness sake: https://github.com/XFactHD/FramedBlocks/issues/92.

I currently cannot reproduce this issue on my end and have yet to receive a crash report to give me a hint on where to look.

**Comment by Tschipp** [comment]
Without a crash log there isn't really anything we can do anyway
