### ISSUE TITLE
crash on startup INdex out of bound

### ISSUE THREAD

**Issue by ZEROX7** [Tschipp/CarryOn#383]
mc 1.18.2
forge 40.1.0
carry on 1.17.0.8

[crash-2022-04-20_18.22.56-client.txt](https://github.com/Tschipp/CarryOn/files/8523364/crash-2022-04-20_18.22.56-client.txt)

**Comment by Tschipp** [comment]
Is it client or server startup?

**Comment by ZEROX7** [comment]
client
