### ISSUE TITLE
Can't pick up Tinkers' Construct blocks 1.18.1 version

### ISSUE THREAD

**Issue by RiverWillows** [Tschipp/CarryOn#384]
### Expected Behavior
I remember this mod being able to pick up and move the tinkers' construct casting tables/basins, which is why I'm trying to add it to a little private mod pack I'm working on.

### Actual Behavior
I'm able to pick up chests and mobs and things but I can't pick up the casting tables or basins.

### Steps to Reproduce
Idk, shift right click on tinkers' construct blocks in your own world? I'm not super mod-savvy, I usually just play modpacks. This is the first time I'm trying to make my own.

### Version of Minecraft, Carry On, Forge
Minecraft (1.18.1)
Carry On (1.17.0.7
Forge (3.9.10)

Other mods:
Tinkers' Construct (3.4.2.60)
Compact Machines 4 (4.1.0)
Simple Inventory Sorter (19.0.0)
The One Probe (1.18-5.0.4)
Mouse Tweaks (2.21)
Torch Slab Mod (1.7.5)
Just Enough Items (9.4.1.172)
AppleSkin (2.4.0+mc1.18)
Tom's Simple Storage Mod (1.2.23)
CreateFoodAdditions (1.0.8)
Flywheel (1.18-0.6.1.63)
Create: Alloyed (1.18.1)
Create: Steam Powered (1.18.1-2.0.-alpha)
Mantle (1.8.37)
Create (0.4f)
Controlling (9.0+15)
Create Crafts & Additions (1.18.1-20220125a)

### Screenshots encouraged
![2022-04-21_00 09 31](https://user-images.githubusercontent.com/104124302/164385819-b49b6cff-51ea-49f3-ab7d-c88fa2259868.png)

**Comment by MrTangoPIG** [comment]
By default, this mod has tinkers construct set to blacklist. Have you removed said blacklisting in the configs?

**Comment by RiverWillows** [comment]
Probably not. How would I do that?

**Comment by MrTangoPIG** [comment]
Going into the modpack, where it lists; installed mods, resource packs, and maps.
Select the 3 dots icon next to play.
Choose open folder.
Go to the following folder directory# \Curse\Minecraft\Instances\YourModPackName\saves\YourWorldName\serverconfig
#It should have taken you to YourModPackName
Open "carryon-server" or "carryon-server.toml"## using notepad or similar program.
##Same file, just with and without file extension viewing on.
Hit control & F (find function)
Search for "tconstruct", it should take you to a line refencing blacklisting.
Delete "tconstruct" within it's entire quotation marks, making sure to keep the same list format (no loose commas).
Save.
Done.

**Comment by RiverWillows** [comment]
Eyyyy, that did it! You're a legend

**Comment by Tschipp** [comment]
Closing this
