### ISSUE TITLE
client crash when interacting with a crafting table while holding a barrel (the rest of the storage blocks possibly too)

### ISSUE THREAD

**Issue by kuba26038** [Tschipp/CarryOn#385]
### Expected Behavior
nothing happens or the barrel is placed

### Actual Behavior
the crafting table is opened with  the player's inventory overlayed on top of it

### Steps to Reproduce
-use carry on 
-place down both a crafting table and a barrel
-pick up a barrel and without shifting try to place it on top of the crafting table

### Version of Minecraft, Carry On, Forge
mc- 1.18.2
co-  carryon-1.18.2-1.17.0.8
f- 40.1.0

### Screenshots encouraged
no screenshots, video instead:

https://user-images.githubusercontent.com/81324988/165147926-a0712a00-4efc-488f-b69e-6e4c6c64ab81.mp4

**Comment by kuba26038** [comment]
hope the video worked

**Comment by belathus** [comment]
Donno if this is an identical crash, but it is very similar; I didn't see a crash report attached to this, so I'm attaching mine: https://gist.github.com/belathus/2f8ddd5a5328bad84fa3981cad067699

Difference with mine is I was carrying a sign and clicked on a furnace.

**Comment by Lupus-the-Fallen** [comment]
I'm using version 1.17.0.8, the bug is still there (tried right-clicking on furnace while carrying chest).

**Comment by Tschipp** [comment]
Are you perhaps using Chisels & bits at the same time?
