### ISSUE TITLE
Very uncool bug that allows you to pick up multiple entities/containers 

### ISSUE THREAD

**Issue by kuba26038** [Tschipp/CarryOn#388]
Basically, a friend of mine has a gaming mouse. This gaming mouse specifically had two additional buttons on it, which he uses to access his last two slots in his inventory. He found out that if he bound any item slot to those buttons, picked something up and clicked said button, it would switch to that button, despite him carrying an entity/storage block already.

**Comment by Tschipp** [comment]
Last two slots? That sounds like some other mod

**Comment by kuba26038** [comment]
Are you saying you can't rebind the inventory slots in vanilla? 
By the last two slots i meant the 8th and the 9th ones

**Comment by Tschipp** [comment]
I see what you mean now. This is a problem that is hard to fix, because it's a non-standard input method. I can cancel the slot presses from a keyboard, but I can't do it on a mouse. So this would be hard to fix.

**Comment by kuba26038** [comment]
it hopefully doesn't mean it's too hard for you, though. best of luck in there!

**Comment by kuba26038** [comment]
i've noticed the bug still exists in the newest versions. i think that we shouldn't find a way to blacklist all buttons possible, but maybe make the slot that carries the entity/container the off hand? the bug works because you can switch off of the carried object to a slot that doesn't have it, but if it's done like this, switching to other slots wouldn't cause anything buggy to happen, since the player still has the carried object stuck in their offhand. but then there's the issue of the player being able to press f to switch the selected item with the carried item, which kind of makes the idea fall apart once again since blacklisting that button would once again do technically nothing, but isn't there a way to temporarily disable the offhand switching functionality? if so, please consider finally fixing it, i had to remove the mod since my players have also found a way to duplicate items that i can't reproduce

**Comment by Tschipp** [comment]
This is fixed in all future versions 1.19.2+, because I've rewritten how carrying works. So I'm gonna close this now.
