### ISSUE TITLE
Moving Minecraft's Bee Hives or Nests causes console to spam "Skipping Entity with id" every tick

### ISSUE THREAD

**Issue by mja00** [Tschipp/CarryOn#391]
### Expected Behavior
No spam when moving these blocks.

### Actual Behavior
Spam in the console every tick

### Steps to Reproduce
1. Find bee nest out in the wild.
2. Pick it up and move it back to your base. My player's may also be teleporting with this block in hand to bring it back to their base. 
3. Place the nest back down and notice server's console is being spammed.

### Version of Minecraft, Carry On, Forge
Minecraft 1.18.2 running Forge 40.1.47
Carry On 1.18.2-1.17.0.8

### Screenshots encouraged
Logs: 
![image](https://user-images.githubusercontent.com/11252574/173382341-3f0e4b63-7907-443d-9eea-cadbf7c8e3d2.png)

I'd send the logs themselves but they're multiple MBs and it's literally just the same thing repeated over and over.

**Comment by Tschipp** [comment]
I can't seem to be able to recreate this

**Comment by mja00** [comment]
Well yeah. It's almost a year old.
