### ISSUE TITLE
I can't find the config file on my server

### ISSUE THREAD

**Issue by 91leMAC** [Tschipp/CarryOn#395]
### Expected Behavior
Normaly I have to find a config file for carry on, on my server

### Actual Behavior
I don't see him. 
In : 
_\config_
### Steps to Reproduce
Install carry on on your server

### Version of Minecraft, Carry On, Forge
Forge : 36.2.23
Minecraft : 1.16.5
Carrry on  : carryon-1.16.5-1.15.5.22

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/89730221/177048894-ac6930ba-d5a5-4072-8bc6-26059e70ac10.png)
It is sort in **A** to **Z**

**Comment by 91leMAC** [comment]
It's possible to have the config file ?

**Comment by Tschipp** [comment]
Since 1.13, the config for most things is located inside of the world's serverconfig folder.
