### ISSUE TITLE
Can't pickup chests any more with CarryOn 1.5.1 / weird display when carrying baby animals

### ISSUE THREAD

**Issue by twoworlds** [Tschipp/CarryOn#40]
I can't carry chests any more with CO 1.5.1
MC 1.12.2 server
forge .2501

I don't know if this is with version 1.5.1 or prior, because I haven't tried to carry a chest for longer. I can carry entities like animania animals but chests don't work. Config file is untouched, i only changed the keys from shift - right click to alt - right click. With this and an older version of CO i could carry chest.

When I try to carry a baby animal from animania, it takes the whole screen and i can't look at where i am going. I have to switch to 3rd person to see the surrounding. In 3rd person everything looks good but in first person the baby animal takes the whole screen.

**Comment by Dasl0ki** [comment]
I have the same problem in "Modern Skyblock 2". Can't pickup chests and getting a lot of errors when starting the client/server. Might be a incompatibility with quark? Log: https://gist.github.com/Dasl0ki/8b8f4b54f9dd476a23b419e0fa7ec9f4

**Comment by Tschipp** [comment]
Uhh, did you all rebind the carry key to something other than shift?

**Comment by Dasl0ki** [comment]
When it stopped working i rebind to LMENU (Left Alt) to test if it's a possible conflict, but that didn't helped. I rebind it even to some unused keys like Numpad 1 or similar, didn't work with these either. Also i reinstalled the instances many times (due to some other testing) and sadly it didn't worked in any of these instances.

**Comment by acun1994** [comment]
Can confirm same issue in Modern Skyblock 2 v 2.5.1, with version Carry On 1.5.1.

Oddly enough, I remember it working in previous versions.

Did some further testing. It works on Modern Skyblock v2.5.0 with version Carry On 1.5.1. Checked configs, both modpack have the same configs, both running on Forge 2500.

Posting mod differences below (The non-working modpack has these, the working one does not):
- Added ae2stuff
- Added Environmental Materials
- Removed Better Placement

**Comment by EmosewaGamer** [comment]
Maybe it has to do with a change in a certain 1.12.2 forge version.

**Comment by acun1994** [comment]
Doubt it, since I tested both using the same Forge version. Suspecting a mod interaction issue

**Comment by Tschipp** [comment]
I'm gonna download the pack and check it out myself

**Comment by ashly138** [comment]
Carry On did not work for me to but after a bit of testing i found that its FTBlib and FTB Utilities that make carry on mod not work correct. :D

**Comment by acun1994** [comment]
Really? That's odd. Might be something to do with the Chunk Permissions thing in those mods

**Comment by twoworlds** [comment]
I have the FTB Utilities installed, but I can't remove them for testing purposes because I need them on my server. I will try in singleplayer without FTB Mods installed.

**Comment by EmosewaGamer** [comment]
I guess there was some change with FTB Utils that messed with Carry On's integration.

**Comment by acun1994** [comment]
These 2 commits of FTBUtils would be closest to the version change in the Modern Skyblock 2 pack
- [commit 1](https://github.com/LatvianModder/FTBUtilities/commit/eb591c17bfaa71fd7f3fa7c7ccaf948fc55104e5)
- [commit2](https://github.com/LatvianModder/FTBUtilities/commit/2cc07d2cde0660c5eca5e19656d697577e7b8be9)

**Comment by Tschipp** [comment]
That makes sense! Because when I tested it, I was able to pick up entities just fine, because they aren't handled by FTBUtils

**Comment by Tschipp** [comment]
Thanks for your assistance! I've fixed it in dev, hotfix rolling out soon!

**Comment by FullMetalMaster** [comment]
issue is happening in 1.18.2

**Comment by joeyjumper94** [comment]
to this day it still happens
