### ISSUE TITLE
Unlimited coal and charcoal in furnace after picking it up and putting it down

### ISSUE THREAD

**Issue by SM-I-LE** [Tschipp/CarryOn#400]
### Expected Behavior
The coal and/or charcoal item should run out of fuel.

### Actual Behavior
The coal and/or charcoal (can be coal blocks, tried it already) will never run out of fuel, but the fire animation on the furnace does turn off.

### Steps to Reproduce
Put coal or charcoal or coal block with smeltable item in furnace, pick up the furnace using preferred keybind, place the furnace back down. Stare at the fire as it literally never moves down a tick.

### Version of Minecraft, Carry On, Forge
Minecraft 1.19, CarryOn 1.19-1.18.0.1, Forge 41.0.62 on clients but 41.0.63 on server.

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/103612500/178160519-c4cbf28f-4bf1-44a6-a2ee-0bb39b4920e4.png)

**Comment by SM-I-LE** [comment]
P.S. wood items work just fine, it's just coal, charcoal, and coal blocks.

**Comment by Tschipp** [comment]
The fact that it's just coal items and nothing else sounds like a cross mod conflict. Do you have any mods that alter coal?
