### ISSUE TITLE
Not Loading on Newest Forge Release 1.19

### ISSUE THREAD

**Issue by 1-1037** [Tschipp/CarryOn#402]
### Expected Behavior
Minecraft launches sucessfully

### Actual Behavior
Minecraft crashes when launched; gives error
Carry On (carryon) has failed to load correctly
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityJoinWorldEvent

### Steps to Reproduce
1. Install latest 1.19 forge version (41.0.98)
2. Install Carry On
3. Launch Minecraft
4. Game crash (Doesn't even get to the main menu)

### Version of Minecraft, Carry On, Forge
Minecraft: 1.19
Carry On: carryon-1.19-1.18.0.1
Forge: 41.0.98

### Screenshots encouraged
Minecraft Screenshot: ![image](https://user-images.githubusercontent.com/77138306/178924153-c7413806-a21c-4bbb-b57d-be58ca9263a6.png)
Crash Log: [crash-2022-07-14_02.12.15-fml.txt](https://github.com/Tschipp/CarryOn/files/9109437/crash-2022-07-14_02.12.15-fml.txt)

**Comment by ladypluu** [comment]
exact same issue here, running on current forge. last update was June 11th though, and Forge has been updating pretty frequently so it probably broke something.

**Comment by Tschipp** [comment]
Should be fixed now with the latest carry on update, also use latest forge please
