### ISSUE TITLE
Won't Load in Forge 1.19: LivingUpdateEvent

### ISSUE THREAD

**Issue by theslimebee** [Tschipp/CarryOn#404]
### Expected Behavior
-install latest Forge (1.19.41.0.100)
-install latest Carry On (1.19-1.18.0.1)
-Load Game, Use Mod

### Actual Behavior
-game cannot boot to main menu: "Living Update Event" Error

### Steps to Reproduce
-exact unknown
=current mods, all functioning=
-EnderStorage 1.19-2.10.0.180
-TerraBlender 1.19-2.0.0.120
-CodeChickenLib 1.19-4.2.2.468
-Crayfish Furniture 7.0.0-pre33-1.19
-BiomesOPlenty-1.19-17.0.0.143
-Aquaculture 1.19-2.4.4

### Version of Minecraft, Carry On, Forge
see |Expected Behavior|, listed there

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/109551991/179607628-c6fa0175-d0d3-4f5a-8d2a-9ade75066cba.png)

crash log:
[crash-carryon-fml.txt](https://github.com/Tschipp/CarryOn/files/9135468/crash-carryon-fml.txt)
 

### Extra Notes
-All above mods and more work fine for me on the 1.18 release alongside Carry On

-Carry On will still not load when put in as a solitary mod, throws the same error.

**Comment by rush423** [comment]
me too

**Comment by AleFrech** [comment]
me too

**Comment by Baggytrousers27** [comment]
Problem with 41.0.94+.

**Comment by Tschipp** [comment]
Should be fixed now with the latest carry on update, also use latest forge please
