### ISSUE TITLE
the game crashes when I grab a mob or object, the game crashes for my friends, and me when I press F5 1.18.2 

### ISSUE THREAD

**Issue by MrPandoru** [Tschipp/CarryOn#407]
### Actual Behavior
when I grab an object/entity, the game crashes for my friends on the server, but not for me and when I press F5 it crashes.
### Steps to Reproduce
just grab an object or mob, and the game crashes my friends, and me when F5, this happens with all objects

### Version of Minecraft, Carry On, Forge
version 1.18.2, i runnig in a modpack:Better MC [FORGE] - 1.18.2

### Screenshots encouraged
![unknown](https://user-images.githubusercontent.com/63491953/182502280-c0fc43f1-a488-44f5-85d1-dfe4915c6740.png)

**Comment by Tschipp** [comment]
Are you on a server or LAN? Can you send a full log?

**Comment by SrRapero720** [comment]
Error isnt the same but also happens to me
When carry a entity (drawned zombie) with something in hand (trident) and carry and use third person hard-crash game (no crash report)

edit: Error sometimes its different


[latest.log](https://github.com/Tschipp/CarryOn/files/10325370/latest.log)
