### ISSUE TITLE
[1.18.2] Cannot carry Immersive Engineering crates

### ISSUE THREAD

**Issue by Nevrai** [Tschipp/CarryOn#408]
The wooden storage crate and reinforced storage crate from [Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering) can’t be carried.

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69 (latest for 1.18.2) (also tested on 40.1.68)
* **Carry On:** 1.17.0.8 (latest for 1.18.2)
* **Immersive Engineering:** 8.0.2-150 (latest)

**Comment by Tschipp** [comment]
immersive engineering blocks are blacklisted.
