### ISSUE TITLE
[Bug] Mobs Disappear When Picked Up, Movement Speed and FOV Changes Still Take Effect

### ISSUE THREAD

**Issue by danbikes** [Tschipp/CarryOn#409]
### Expected Behavior
-Use the keybind to pick up blocks and mobs, carry block/mob somewhere, then right click to place mob somewhere else.

### Actual Behavior
-Use keybind to pick up mob, mob disappears but the effects of picking up said mob still persist. Player movement speed and FOV change, even though nothing is in hands. 

Also cannot pick up blocks (anything that's not a mob/entity) at all anymore with Carry On. Was working fine until earlier today (been using this mod with the same group of mods for the last 3 weeks without issues).

The only way I've found to get rid of the movement speed/FOV change is to uninstall the mod from the server and client, and have client log in without the mod installed. There don't seem to be any errors/logs triggered by any of these actions either, so unfortunately I don't have any of those to post.

### Steps to Reproduce
-Attempt to pick up any object using Carry On.

### Version of Minecraft, Carry On, Forge
Minecraft version 1.19, Carry On version 1.2, Forge version 41.1.0.

**Comment by danbikes** [comment]
Found the issue, apparently the new version of Inventory Profiles Next was causing this bug. They added a new feature enabled by default that blocks items you pick up (normally, not using Carry On) from being placed in your hotbar, and puts them solely in your inventory. Guessing that causes Carry On to freak out since it probably tries to place the object/mob you pick up with Carry On into your inventory instead of your hotbar.

Solution is to either roll back to an earlier version of Inventory Profiles Next, or disable that feature client-side in the config for that mod.

**Comment by Juanma0186** [comment]
> Found the issue, apparently the new version of Inventory Profiles Next was causing this bug. They added a new feature enabled by default that blocks items you pick up (normally, not using Carry On) from being placed in your hotbar, and puts them solely in your inventory. Guessing that causes Carry On to freak out since it probably tries to place the object/mob you pick up with Carry On into your inventory instead of your hotbar.
> 
> Solution is to either roll back to an earlier version of Inventory Profiles Next, or disable that feature client-side in the config for that mod.

What is the option that you have to turn off in the InventoryProfilesNext??

**Comment by AlexCastel14** [comment]
> 
![CarryOnIssue](https://user-images.githubusercontent.com/53499354/187015341-6eaf1ad7-4412-401a-8f89-b4345d6de43b.png)

I solved it deactivating the option "Pick items directly into the inventory" on Locked Slots options.

Also, I reported this on Inventory Profiles Next github.
[https://github.com/blackd/Inventory-Profiles/issues/183](https://github.com/blackd/Inventory-Profiles/issues/183)

**Comment by Tschipp** [comment]
Since Inventory Profules seems to have fixed this on their end, I'll close this.
