### ISSUE TITLE
Dupe issues with Refined Storage

### ISSUE THREAD

**Issue by xAlicatt** [Tschipp/CarryOn#41]
I haven't had a chance to test this much, but I did notice that picking up my Refined Storage disk drive with Carry On and placing it back down somewhere else on my network duplicated everything inside it. It actually did it twice, so I then had 3 times the amount of stuff I had originally after picking it up and moving it two times. I moved it a 3rd time to test it because I noticed a weird amount of certain items from what i thought i had. After I placed it back down the 3rd time, it seems like the 2nd dupe went away somehow. So I was left with only twice the original items. 

BTW these aren't ghost items, as I was able to take out and use both copies of a duplicated item...one that I know for a fact I only had one of originally.

This was on multiplayer without op. Minecraft 1.10.2 version 1.2.26 of Refined Storage and v1.5.1 of Carry on. Server software includes Sponge 5.2.0-BETA-2691 & Grief Prevention 4.0.1.472

**Comment by Tschipp** [comment]
This shouldn’t be happening in latest... but it might be an issue with sponge

**Comment by xAlicatt** [comment]
I just added Refined Storage to the blacklist in the config, but I thought I would let you know.

**Comment by Tschipp** [comment]
Yeah that's probably the smartest thing to do. I added error handling a while ago that should automatically prevent picking up the disk drive...
