### ISSUE TITLE
Cannot Carry Villager

### ISSUE THREAD

**Issue by MiniRaptor** [Tschipp/CarryOn#411]
I added villager in entities whitelist by minecraft:villager
 But it not work.

**Comment by 91leMAC** [comment]
Hello 👋,
Can I have your whitelist file (just the text) please.

**Comment by Tschipp** [comment]
To be able to pick up larger mobs, you need to set the maxEntityHeight in the config to something larger than 2, and smaller than 10. The config is located in CarryOn's server config (which is located inside of the world's serverconfig folder).
