### ISSUE TITLE
Picking up a mob crashes other players in close proximity

### ISSUE THREAD

**Issue by CrankyScales** [Tschipp/CarryOn#412]
### Expected Behavior
Picking up a mob while near a friend.

### Actual Behavior
Doesn't crash the person who picks up the mob but crashes any player witnesses.

### Steps to Reproduce
Just pick up a mob while in multiplayer with a friend in close proximity (within the same chunk ideally) or have them pick up a mob

### Version of Minecraft, Carry On, Forge
Minecraft 1.18.2 Carry On 1.18.2-1.17.0.8

Edit: Picking up chests and other blocks is not a problem, it's only picking up mobs.

**Comment by FabPL-62** [comment]
The same problem happened to me, version of minecraft 1.18.2, using Carry On 1.18.2-1.17.0.8

**Comment by Tschipp** [comment]
Are you on a server or on a lan world?

**Comment by FabPL-62** [comment]
> Are you on a server or on a lan world?

In my case the error occurs on a server

**Comment by Plisko1** [comment]
This just happened on my 3 person 1.19.3 server.  Installed the mod.  Picked up my pet dog.  Both other players clients crashed.  One of them was not in close proximity.  If I am holding the dog and they try to log back in, they crash immediately.

**Comment by Tschipp** [comment]
Do you have a log?
