### ISSUE TITLE
When the jukebox is lifted, the music disc disappears from it.

### ISSUE THREAD

**Issue by ElyaCakePie** [Tschipp/CarryOn#413]
### Expected Behavior
When the jukebox is lifted, the music disc disappears from it.

### Actual Behavior
It is shown that supposedly the disk is inside, but it cannot be pulled out, but you can insert another disk and it will replace the previous one, which will disappear without a trace.

### Steps to Reproduce
You need to insert a disc, then raise the jukebox unit, put it in and check for the presence of a disc.

### Version of Minecraft, Carry On, Forge
1.19.1

 ### Screenshots encouraged
![2022-09-02_19 14 47](https://user-images.githubusercontent.com/112717118/188196821-3f1cd4e8-bdc9-4ceb-86cf-98c2d0cb8aa6.png)
![2022-09-02_19 14 55](https://user-images.githubusercontent.com/112717118/188196894-059f640e-1031-4dc8-a7be-4ce53dbdc4cd.png)
![2022-09-02_19 15 05](https://user-images.githubusercontent.com/112717118/188196978-a431b5f3-0f97-4ffe-8f32-2c84f648022b.png)
![2022-09-02_19 15 13](https://user-images.githubusercontent.com/112717118/188197078-9a75cf86-1095-4c54-8e83-6f56e99c4e61.png)
![2022-09-02_19 15 28](https://user-images.githubusercontent.com/112717118/188197259-fcb326f5-8bed-42d7-b68b-6bb89a7d0985.png)
![2022-09-02_19 15 46](https://user-images.githubusercontent.com/112717118/188197329-23cc8329-0f0b-484e-8008-4bdcb3d15125.png)

**Comment by Tschipp** [comment]
This has been fixed for versions 1.19.2+
