### ISSUE TITLE
The mod stopped working.

### ISSUE THREAD

**Issue by ElyaCakePie** [Tschipp/CarryOn#414]
### Expected Behavior
The mod does not work in one of my worlds, but it works in another.

### Actual Behavior
The mod worked before.

### Version of Minecraft, Carry On, Forge
1.19.1

**Comment by ElyaCakePie** [comment]
O! If you open the game for the network, after some time the mod works again. I don't even know if this thread should be closed.

**Comment by Tschipp** [comment]
I have no clue how this could be related, and without logs or reproducing procedures I can't do much. Closing, this, feel free to open a new issue if needed.
