### ISSUE TITLE
Mobs and blocks disappear upon death with all contents.

### ISSUE THREAD

**Issue by ElyaCakePie** [Tschipp/CarryOn#415]
### Expected Behavior
Mobs and blocks disappear upon death with all contents.

### Actual Behavior
If I pick up, no matter, a mob or a block with a bunch of resources in survival, suddenly die, maybe from a fall, maybe from monsters, then all this disappears without a trace, even without keepinventory.

### Steps to Reproduce
See screenshots.

### Version of Minecraft, Carry On, Forge
1.19.1

### Screenshots encouraged
![2022-09-02_23 51 32](https://user-images.githubusercontent.com/112717118/188233961-d04c8b8f-4359-409d-b558-d8db7951b978.png)
![2022-09-02_23 52 08](https://user-images.githubusercontent.com/112717118/188233999-e9d5816e-5b38-454f-9728-8dcc442a4d90.png)
![2022-09-02_23 52 40](https://user-images.githubusercontent.com/112717118/188234024-f85f9dde-bf2c-4df4-8377-3ff31d6fd57a.png)
![2022-09-02_23 52 53](https://user-images.githubusercontent.com/112717118/188234045-3a920a34-8746-41b8-965d-c7a15a328fed.png)
![2022-09-02_23 53 02](https://user-images.githubusercontent.com/112717118/188234066-a1c750b5-54ef-48bf-b69d-9965fec4d40e.png)
![2022-09-02_23 53 05](https://user-images.githubusercontent.com/112717118/188234101-18bcc2fe-5874-47bc-b76d-659c5eb62a8f.png)
![2022-09-02_23 53 17](https://user-images.githubusercontent.com/112717118/188241000-efdc539c-4a14-4e47-ac8a-3608e591c527.png)
![2022-09-02_23 53 25](https://user-images.githubusercontent.com/112717118/188234170-49782c32-3b8a-43b0-8a44-863eae02b2d0.png)
![2022-09-02_23 53 47](https://user-images.githubusercontent.com/112717118/188234198-0c65e74f-ef8c-45fd-96ef-ff01300607da.png)
![2022-09-02_23 53 57](https://user-images.githubusercontent.com/112717118/188234234-b4018100-f9be-451d-b785-0001d1d24dc2.png)
![2022-09-02_23 54 00](https://user-images.githubusercontent.com/112717118/188241092-7852dc6e-8a2c-4c22-a6ac-dcd17bbab8a6.png)

![2022-09-02_23 54 12](https://user-images.githubusercontent.com/112717118/188234288-af706437-9285-4116-8a2e-a48cc75e1662.png)

**Comment by ElyaCakePie** [comment]
It would be nice to receive at least notifications about the loss of a block or mob in chat.

**Comment by Tschipp** [comment]
I'm not sure what you mean or if I understand you correctly. What is the behavior that you expect?
The block/entity is supposed to spawn where you died, not where you respawned.
