### ISSUE TITLE
Picking up a Woot Perk Slot with a perk deletes the perk

### ISSUE THREAD

**Issue by Ashetf2** [Tschipp/CarryOn#416]
### Expected Behavior
The Perk Slot keeps the perk.

### Actual Behavior
The perk gets deleted.

### Steps to Reproduce
See screenshots

### Version of Minecraft, Carry On, Forge
1.16.5, latest Carry On version

### Screenshots encouraged
![javaw_wsdu3VKGmN](https://user-images.githubusercontent.com/63692647/188285846-17918359-6a35-47e6-bdf5-f9f9b71bf0da.png)
![javaw_hoIy0XmoBx](https://user-images.githubusercontent.com/63692647/188285862-8a0a0a33-07a0-4f94-adaf-78d0801e1688.png)
![javaw_Ra2YtNjgWI](https://user-images.githubusercontent.com/63692647/188285864-9dff6db4-ec6d-4e9a-a1b5-6e4081789c5e.png)

**Comment by Tschipp** [comment]
Add it to the blacklist, looks like they are saving their data in a strange way.
