### ISSUE TITLE
 any object or mob disappears

### ISSUE THREAD

**Issue by Insectoidemalebolo** [Tschipp/CarryOn#417]
every time I grab a mob or any object, it disappears, and I'm left with the slow effect, and I can't drop the object since it has disappeared, in a solo world it doesn't happen, but on the server it does.
mc:1.18.2
forge:1.40.74
carryon:1.17.0.8

**Comment by Ellysown** [comment]
hello! i have the same problem where i actually updated my server from 1.19 to 1.19.2 then tried to put my old world folder to a new server. i solved it by replacing the server config of the mod file with a fresh one. 

1.  go to filezilla and connect your server
2. go to your world folder then open serverconfig
3. replace the carryon-server.toml file with a fresh one
i hope this helps!

**Comment by Tschipp** [comment]
@Insectoidemalebolo, are you on a server or singleplayer?

**Comment by Porcy** [comment]
Happens on server also. All The Mod 7 - To The Sky. I'm stuck with permanent slowness, I lost a whole chest of valuables to this bug and can't even eat since I can't change my active hotbar slot. Help!

**Comment by Tschipp** [comment]
If your hotbar is stuck, perform /carryon clear

**Comment by gousisme** [comment]
I'm having the same issue here, not all the time, but sometimes the mob will disappear, tried delete the config as well but no luck, i'm on 1.19.2 server and all the players are facing this issue as well

Edit: not really a same issue, the mob disappear when i place it down

**Comment by Tschipp** [comment]
Have you tried using the v2.0.0 version? Make sure you're not carrying something while you upgrade.

**Comment by gousisme** [comment]
Sorry for the late reply, i finally found which mod cause it, removed this mod and everything is fine
https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-spawn
