### ISSUE TITLE
Custom Pickup not working

### ISSUE THREAD

**Issue by Schn1ek3** [Tschipp/CarryOn#418]
Hello,
the custom pickup function in the config does not work unfortunately. 
I want to have spawners on my server carried only by certain people. 
However, anyone can pick up a spawner whether OP or not. 
The required mod (game-stages) is also installed. 
Am I writing something wrong in the config? 

```
[custom_pickup_conditions]
	#Custom Pickup Conditions for Blocks
	customPickupConditionsBlocks = ["minecraft:spawner(spawner)", "minecraft:mob_spawner(spawner)"]
```

### Version of Minecraft, Carry On, Forge
MC: 1.18.2
Forge: 40.1.79
Carry On: 1.17.0.8

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/42380245/193022034-cce773cb-7798-4523-a781-4f510cbd73dc.png)

**Comment by Tschipp** [comment]
Strange... it could be that I didn't implement it for 1.18, because gamestages was not out then yet. I'll take a look.
