### ISSUE TITLE
Chests can be placed beneath double chests

### ISSUE THREAD

**Issue by Thyriel** [Tschipp/CarryOn#42]
As title. The placed chest becomes invisible but still useable.
1.12 v1.6.1

**Comment by Tschipp** [comment]
Could you provide a gif of what's happening?

**Comment by Thyriel** [comment]
Tried around a bit more. Seems to be a problem with chests from mods.
vanilla chest is working (not placeable beneath a double chest)

Chests from "Quark" (jungle, acacia, ...):
Place a double chest and a picked up quark chest (same type) like that:
XX
-Y
the Y chest becomes invisible and has inventory like a double chest. (shared inventory with the chest at the edge)
If the picked up chest is of a different wood type it still is placeable but doesn't become invisible.

**Comment by Tschipp** [comment]
The check is made by the block itself, meaning if you pick up flowers they can only be placed on dirt or grass. If modded chests don't override this check with their own, there's nothing I can do.

**Comment by Vazkii** [comment]
What check are we talking about here?

**Comment by Tschipp** [comment]
`Block#canPlaceBlockAt`. You are probably doing the placement check in the itemblock, right?
