### ISSUE TITLE
1.16.5 CANT PICK UP SPAWNERS

### ISSUE THREAD

**Issue by Deezer400** [Tschipp/CarryOn#420]
### Expected Behavior
pick up

### Actual Behavior
no pick up

### Version of Minecraft, Carry On, Forge
1.16.5 for all

## Screenshots encouraged
![2022-10-12_12 53 09](https://user-images.githubusercontent.com/115658421/195414504-5f71eb42-099c-4009-b8e5-6ea575d43970.png)

**Comment by Tschipp** [comment]
what modpack are you using?

**Comment by Tschipp** [comment]
Can't recreate this. I'm gonna close this issue, but feel free to reopen another one if it is still a problem.
