### ISSUE TITLE
Held Mob/Entity & Arms Won't Render in Third Person

### ISSUE THREAD

**Issue by ValdusAetherius** [Tschipp/CarryOn#424]
### Expected Behavior
Held entity via CarryOn should be visible, along with my arms, in third person.

### Actual Behavior
Both what I hold, and my player's arms, do not render in third person whilst carrying. If I make "renderArms = false" in the config, my arms show in third person, but the Entity does not. "facePlayer" changes none of this.

### Version of Minecraft, Carry On, Forge
Minecraft 1.18.2, Carry On 1.17.0.8.jar, Forge 40.1.84

![2022-11-01_17 22 46](https://user-images.githubusercontent.com/117151669/199180738-1f12b9ff-8880-482b-9614-9a6c858efecc.png)
![2022-11-01_17 22 57](https://user-images.githubusercontent.com/117151669/199180749-f700af97-1639-48fd-b35b-c9f4599f9e5d.png)
![2022-11-01_17 22 59](https://user-images.githubusercontent.com/117151669/199180759-add5cba0-9d6e-4782-a1bb-f1e7653d11b0.png)
![2022-11-01_17 23 09](https://user-images.githubusercontent.com/117151669/199180768-89ed2550-b2b6-4422-9b9d-5c801fdf0b18.png)

**Comment by Tschipp** [comment]
Some other mod is responsible for this

**Comment by ValdusAetherius** [comment]
So, turns out I forgot about this issue I posted, as it was due to a Graphics Setting, and I had resolved it by changing the settings some time ago.
