### ISSUE TITLE
[1.16] Mobs and hands is displaying incorectly on water

### ISSUE THREAD

**Issue by BoBkiNN** [Tschipp/CarryOn#425]
### Expected Behavior
Mobs and hands that holded are visible

### Actual Behavior
Mobs and hands are visible only in the water or air, depending where camera is

### Steps to Reproduce
* Install Oculus with Rubudium (If problem is not in this mods, i can share modpack)
* Join the world
* Pickup any mob
* step in water and place Sneak (or other way to go down up to falf) and see how water slices mob and hands. If you will be in water, hands and mob are completely invisible from air and reverse

### Version of Minecraft, Carry On, Forge
MC 1.16.5, Carry On 1.15.5.22, Forge 36.2.34

### Screenshots encouraged
![Screenshot_22](https://user-images.githubusercontent.com/78136575/200298246-fbd8c76a-37e6-4623-a274-933f0ba91069.png)
![Screenshot_21](https://user-images.githubusercontent.com/78136575/200298255-0abcecd2-be8d-4470-a3e4-2d461a2213ad.png)
![Screenshot_24](https://user-images.githubusercontent.com/78136575/200299698-8b4a764b-9ba6-49e4-9536-631a0704b5fd.png)
![Screenshot_23](https://user-images.githubusercontent.com/78136575/200299702-9a066bde-4aa3-471f-bfc2-f9a50fc561bb.png)

**Comment by Tschipp** [comment]
Should be better with 2.0.0, but can't be entirely prevented.
