### ISSUE TITLE
Clicking Crafting Table While Carrying Entity Crashes Game

### ISSUE THREAD

**Issue by LadyLucs** [Tschipp/CarryOn#428]
### Expected Behavior
Not to be able to use crafting table while carrying my cat 

### Actual Behavior
Opens crafting table GUI, which is wildly visually bugged, then proceeds to crash the game

### Steps to Reproduce
Grab pet cat then go to place it on the crafting table by right clicking.

### Version of Minecraft, Carry On, Forge
1.18.2, 1.18.2-1.17.0.8 ,FORGE 40.1.85

### Screenshots encouraged
[crash-2022-11-27_17.28.11-client.txt](https://github.com/Tschipp/CarryOn/files/10099460/crash-2022-11-27_17.28.11-client.txt)

**Comment by Tschipp** [comment]
Should be fixed with v2.0.0
