### ISSUE TITLE
1.19.2 Some villagers unable to be picked up

### ISSUE THREAD

**Issue by Wiseclone** [Tschipp/CarryOn#429]
### Expected Behavior
Villager is picked up

### Actual Behavior
No reaction

### Steps to Reproduce
Attempt to pick up a villager while empty-handed. Some villagers can be picked up, others cannot. Profession does not seem to matter. Added Villager* to the whitelist. No change.

### Version of Minecraft, Carry On, Forge
Minecraft 1.19.2
Forge 43.1.38
Carry On 1.18.2.5

**Comment by Tschipp** [comment]
Should always be possible, try v2.0.0
