### ISSUE TITLE
Picked up item causes crash when trying to place down

### ISSUE THREAD

**Issue by iepathos** [Tschipp/CarryOn#43]
Picked up an external storage item from refined storage mod and now game crashes whenever I try to place it down.  I load back in still holding it so can't continue playing.  Playing on the galactic engineers modpack.

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in ExtendedBlockState{block=refinedstorage:external_storage, properties=[direction, down, east, north, south, up, west]}

Any ideas how to fix without wiping my character data?

**Comment by Tschipp** [comment]
type /carryon clear. If you update to the latest version, you shouldn’t be able to pick up the external storage anymore.
