### ISSUE TITLE
The config can be accessed through an easy to use Config GUI from the Main Menu, and changes are recorded real-time

### ISSUE THREAD

**Issue by inikishev** [Tschipp/CarryOn#430]
where is it? can't find it...

**Comment by Tschipp** [comment]
Please tell me what versions... Also as far as I'm aware, the config GUI doesn't exist for both fabric and forge anymore.

**Comment by inikishev** [comment]
> Please tell me what versions... Also as far as I'm aware, the config GUI doesn't exist for both fabric and forge anymore.

latest fabric version. I found that in the mods description

**Comment by Tschipp** [comment]
I see. A fabric config gui is currently not supported.
