### ISSUE TITLE
crashed picking up a vanilla chest

### ISSUE THREAD

**Issue by monkeybee11** [Tschipp/CarryOn#432]
### Expected Behavior
hugging a chest

### Actual Behavior
crash to desktop

### Steps to Reproduce
shift clicked a chest (we are using a custom modpack so mite of been a conflic with something

### Version of Minecraft, Carry On, Forge
mc | 1.19.2
fabric | 0.14.10 for mc 1.19.2
carry-on | carryon-fabric-1.19.2-2.0.0.6

### Screenshots encouraged
no screenshot but heres a pastebin of the crash
https://pastebin.com/4cCH4vge

**Comment by V-lpen** [comment]
Experiencing the same crash on fabric 1.19.2
