### ISSUE TITLE
Crash in startup when trying to run under Fabric 1.19.3

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#433]
### Expected Behavior
Minecraft to load normally with Carryon installed.

### Actual Behavior
Minecraft actually crashes at startup with [this crash report](https://gist.github.com/vico93/8eb51a17c17e6087aa13baa5da95da12).

### Steps to Reproduce
- Install Fabric Loader 0.14.11 for Minecraft 1.19.3
- Install Fabric API 0.69.1 for 1.19.3
- Install CarryOn (Fabric port) version 2.0.0.6.

**Comment by Tschipp** [comment]
it's not yet on 1.19.3
