### ISSUE TITLE
Picking up a villager then going third person crashes the game

### ISSUE THREAD

**Issue by SirDoggyJvla** [Tschipp/CarryOn#434]
### Expected Behavior
After picking up a villager, I go in third person and I can see myself with the villager in hands.

### Actual Behavior
After picking up a villager, when I go in third person the game freezes and then crashes by itself

### Steps to Reproduce
Pick up a villager with shift + right click, once in hands, go in third person, game crashes.

### Version of Minecraft, Carry On, Forge
Minecraft 1.18.2 
On the modpack "Better Minecraft Plus 1.18.2 v41"
Version of Carry On: "carryon-1.18.2-1.17.0.8"

### Screenshots encouraged
https://youtu.be/9-Q62g8M9AQ

PS: Better Third Person mod is in the modpack, it might come from that

**Comment by NekoTZN** [comment]
The same happened with me, in my case it was caused by Shoulder Surfing mod (but not specifically using the shoulder surfing mode, were using vanilla 3rd person mode). What i did was remove the mod and reopen the game (for those that is looking for a solution).
