### ISSUE TITLE
Arms floating

### ISSUE THREAD

**Issue by SirDoggyJvla** [Tschipp/CarryOn#435]
### Expected Behavior
After picking up an entity like a parrot, I go in third person and see the parrot in front of me, in my hands.

### Actual Behavior
After picking up a different entity like a parrot, I go in third person and see the parrot in my hands but my arms are not attached to my body.

### Steps to Reproduce
Pick up an entity with shift + right click, once in hands, go in third person and hands are floating.

### Version of Minecraft, Carry On, Forge
Minecraft 1.18.2 
On the modpack Better Minecraft Plus 1.18.2 v41
Version of Carry On: carryon-1.18.2-1.17.0.8

### Screenshots encouraged
I'm picking up a frog from Quark in this exemple.
https://youtu.be/JV5ndVCzo1I

PS: Better Third Person mod is in the modpack, it might come from that

**Comment by Tschipp** [comment]
This is fixed or improved in the 2.0.0 versions, but won't be backported to 1.18.2
