### ISSUE TITLE
Aldeãos sumindo depois de uma certa distancia

### ISSUE THREAD

**Issue by SUB-ZERO-BR** [Tschipp/CarryOn#438]
### Expectative Behavior

Move the villager to X place and continue with the same spawn and unpawn rules.

### Current Behavior

After being moved the same adopts the spawn rules of a zombie for example (which requires nametag not to disappear).

## Steps to Reproduce

Change the villager's spawn rules.

### Version of Minecraft, Carry On, Forge

Minecraft Fabric 1.19.3-2.0.1.9

**Comment by Tschipp** [comment]
I don't understand what the issue is. Can you try to explain in a different way?
