### ISSUE TITLE
KeepInventory+CarryOn = Crash

### ISSUE THREAD

**Issue by JosEffigy** [Tschipp/CarryOn#44]

**Comment by JosEffigy** [comment]
the log is too large to send the whole thing
https://paste.ubuntu.com/25830090/

**Comment by Tschipp** [comment]
Strange. Is this happening only in one particular world, or everywhere?

**Comment by JosEffigy** [comment]
might be a false alarm. It sometimes crashes unexpectedly even while carrying vanilla mobs, so I stopped using it too much. 
from what I see it locks opening inventory and scrolling, carrying a mob turns it into an item. 
When you die while carrying it and keepInventory=true then scrolling/opening inventory crashes.

**Comment by Tschipp** [comment]
> When you die while carrying it and keepInventory=true then scrolling/opening inventory crashes.
Interesting, I've not thought about keepInventory. I'm gonna take a look at that

**Comment by Tschipp** [comment]
Ok, this has been resolved with a workaround: When dying with keepInventory, the Block/Entity still gets placed in the world, but at your respawn location instead of your death location
