### ISSUE TITLE
Issue with config

### ISSUE THREAD

**Issue by pocinhas** [Tschipp/CarryOn#440]
### Expected Behavior
Being able to pick up every entity

### Actual Behavior
Config ends up resetting the two values i change and I can't pick up every entity in survival

### Steps to Reproduce
1- Go to the config and change the values of
```   
    "//maxEntityWidth": "Max width of entities that can be picked up in survival mode",
    "maxEntityWidth": 1.5,
    "//maxEntityHeight": "Max height of entities that can be picked up in survival mode",
    "maxEntityHeight": 2.5,
```
to something like 100

2- launch minecraft and those same values reset to their default values
### Version of Minecraft, Carry On, Forge
1.19.2, Fabric 0.14.11

### Screenshots encouraged
The config after it's reset: https://pastebin.com/7Mnydmq8

**Comment by Tschipp** [comment]
This is actually because the max value is 10. Try setting it to something lower than that.
