### ISSUE TITLE
[Compatibility] Crash with Bits and Chisels Blocks rendering

### ISSUE THREAD

**Issue by xErrorAmelie** [Tschipp/CarryOn#445]
### Expected Behavior
It shouldn't crash when you pick up chiseled blocks 

### Actual Behavior
Client Crash when rendering the block while picked up

### Steps to Reproduce
Pick up a chiseled block. If it still doesn't crash there, it will crash when you change to third person perspective.

### Version of Minecraft, Carry On, Fabric
Minecraft: 1.19.2
Carry On: 2.0.2.3
Fabric Loader: 0.14.12

###Crash-report
https://mclo.gs/JEyLJsd

### Screenshots encouraged
The chiseled block:
![2023-01-09_15 05 57](https://user-images.githubusercontent.com/51492094/211792571-a076f6d2-8176-4429-9310-28fe7780c4de.png)

**Comment by Tschipp** [comment]
I'll call this one "fixed", even though it's not really fixed. I've changed it such that if all fails, it will just render nothing instead of crashing. I think this is a much better approach.
