### ISSUE TITLE
Pehkui incompatibility

### ISSUE THREAD

**Issue by EdoEquin0x** [Tschipp/CarryOn#446]
Expected Behavior:
To Work Properly

Actual Behavior:
Player model break

Steps to Reproduce:
Using this mod together with pehkui and increase the size of the player (even slightly, like 1.1 or 1.2)

Version of Minecraft, Carry On, Forge:
1.16.5, latest and latest

![image_2023-01-15_001325695](https://user-images.githubusercontent.com/69121197/212501105-bc6e7655-9079-4ae3-a1ac-386e2aae58e6.png)

**Comment by Tschipp** [comment]
Can you explain what it is supposed to look like?

**Comment by EdoEquin0x** [comment]
Well, I guess scaling the chest's size according to the player's size would fix the problem

**Comment by Tschipp** [comment]
Can you take a screenshot in better lighting conditions? Also, is the players hitbox changed or not?

**Comment by Tjmaxmillion** [comment]
This issue also occurs when scaling smaller, By default Pehkui dose scale the player hitbox to match the visual scale.
Though these values can be set separately i.e. A player that looks smaller but has a normal hitbox.

For this example my Height and Width are both 0.66 (Hitbox and Model), Shown below with hitboxes turned on.

![2023-01-27_19 04 52](https://user-images.githubusercontent.com/76654305/215239149-4aa46f66-1ce0-431a-bf31-ddb999e9a01d.png)
![2023-01-27_19 05 00](https://user-images.githubusercontent.com/76654305/215239158-822a6ecb-5105-4600-86d9-abe811cdfc9d.png)
![2023-01-27_19 05 13](https://user-images.githubusercontent.com/76654305/215239161-4ceae84b-1adf-4b9d-b188-6a98a63f8c89.png)

**Comment by Tschipp** [comment]
Hmmm... I'm not sure if I can support such model changing mods more... on 1.19.2+, this should no longer be a problem because I've rewritten this system from the ground up
