### ISSUE TITLE
Picking up entities plays "hellish" sounds

### ISSUE THREAD

**Issue by ghost** [Tschipp/CarryOn#448]
1.19.2, Fabric
[https://youtu.be/R_eEi8I_C9E](url)

**Comment by Elfrrik** [comment]
I believe that's a conflict with extra sounds. Go to options, then music and sounds, then to the cog next to extra sounds, and if you turn effects/potions all the way down, the hellish sounds go away. I can't source what effect that is meant to be however.

**Comment by esotericist** [comment]
if it's triggering off of potion effects, i'm betting it's reacting to carryon applying slowness.

**Comment by ghost** [comment]
It looks like you guys are right. It is the slowness effect. Is there a way I can disable the slowness effect? I'd rather have it off than the potion sounds off.

**Comment by Tschipp** [comment]
Don't know if this on me to fix, because all I'm doing is repeatedly applying an effect, which is quite a common thing.

**Comment by fluffyxox** [comment]
Use Sounds Begone and eliminate the two Extra Sounds labeled sounds it detects.
