### ISSUE TITLE
When I pick up Lecturn and accidentally right click villager It crash

### ISSUE THREAD

**Issue by mashironn** [Tschipp/CarryOn#450]
### Expected Behavior
Nothing should happen 

### Actual Behavior
Crash

### Steps to Reproduce
Picking up lecturn > attempt to picking up villager

### Version of Minecraft, Carry On, Forge
1.19.2
carry on v2.0.2.3
fabric 
### Screenshots encouraged

crashlog
[crash-2023-01-18_01.59.42-client.txt](https://github.com/Tschipp/CarryOn/files/10438527/crash-2023-01-18_01.59.42-client.txt)

**Comment by Tschipp** [comment]
Can't recreate. Likely the issue of another mod called "anti_ad" in the log
