### ISSUE TITLE
Latest 1.19.2 Crash on Startup

### ISSUE THREAD

**Issue by Reshirou** [Tschipp/CarryOn#455]
Latest version of 1.19.2 Forge crashes before starting up, here's a log

https://pastebin.com/emvXwWGk

Crash stops when reverting to previous update

EDIT: correction, reverting TWO version fixes it. The previous version also crashes the same way, only 2.0.2.3 does not crash.

**Comment by Tschipp** [comment]
Just to make sure, you're using version 2.0.4.6?

**Comment by Tschipp** [comment]
And what other mods are you using?

**Comment by Damdrara** [comment]
Same issue here. Modlist is very long, but maybe this log helps:

![image](https://user-images.githubusercontent.com/54811051/215285505-c5b70dc6-c372-45b0-a91b-51cf6116ad97.png)

**Comment by rafaelkai** [comment]
Happens to me too.

**Comment by Looodon** [comment]
Minecraft 1.19.2
Forge 43.2.3

Same is happening to me on Carryon versions:
2.0.4.6
2.0.3.4

**Comment by kubaxius** [comment]
It's possibly a problem with Artifacts, as stated here:
https://github.com/ochotonida/artifacts/issues/187

**Comment by Tschipp** [comment]
Should be fixed now.
