### ISSUE TITLE
death by sufication

### ISSUE THREAD

**Issue by TobiasWIntress** [Tschipp/CarryOn#460]
### Expected Behavior

i die with a chest in hand and when i die the chest should either appear in the last placed location or where i die 
### Actual Behavior

when i die the chest disappears probably due to it trying to spawn some where there is already blocks 
### Steps to Reproduce

suffocate in snow you can fall through while holding a chest
### Version of Minecraft, Carry On, Forge/Fabric

minecraft 1.19.3

to avoid this particular situation you could allow the placing the chest within this snow or break blocks as if i was punching them or at like half the speed or something

**Comment by Tschipp** [comment]
The chest actually does try to get placed around the player, in a 15x15x15 block area. So it's extremely unlikely that all blocks were filled. I would look around, maybe in caves beneath the surface too

**Comment by Tschipp** [comment]
I have now improved the system, so it should always pick the nearest possible block for placement.
