### ISSUE TITLE
Incompatability with Gargantuan

### ISSUE THREAD

**Issue by Leveler02** [Tschipp/CarryOn#461]
### Expected Behavior
Game should launch without issue

### Actual Behavior
Game crashes to launcher with exit code 1 and no crash report

### Steps to Reproduce
put Gargantuan and Carry On in the same mod folder and launch the game

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2, Carry On 1.19.2-2.0.4.6, Fabric Launcher 0.14.13, Fabric API 0.73.2+1.19.2, Gargantuan 1.3.0

### Screenshots encouraged
[latest.log](https://github.com/Tschipp/CarryOn/files/10610457/latest.log)
This is a follow up from issue #443

**Comment by Tschipp** [comment]
The source of gargantuan seems to not be public, so I can't see how they did it. However I rewrote my code to use WrapOperation from MixinExtras, described here: https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation.
This would chain if used by multiple people, so I think if Gargantuan were to fix this on their end it would work.
