### ISSUE TITLE
DragonSurvival Compat

### ISSUE THREAD

**Issue by TheButterbrotMan** [Tschipp/CarryOn#463]
### Expected Behavior

Not weird looking, when carrying something.
### Actual Behavior
![image](https://user-images.githubusercontent.com/64548098/219863079-011638ad-6858-4836-b030-91ef2592cc2a.png)

### Steps to Reproduce
Install Dragon Survival mod and carry something

### Version of Minecraft, Carry On, Forge/Fabric
1.18.2 Forge 40.0.2.1, 1.17.0.8 CarryOn

**Comment by Tschipp** [comment]
What is actually happening here? Are you riding the dragon?
