### ISSUE TITLE
[1.19.2 Forge] Crash on Launch with Debugify

### ISSUE THREAD

**Issue by BookerCatch** [Tschipp/CarryOn#464]
### Expected Behavior
Client launches to main menu.

### Actual Behavior
Client crashes upon launching with Debugify Reforged installed.

### Steps to Reproduce
Launch client with Debugify Reforged installed alongside CarryOn.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2; Carry On 2.0.5.10; Forge 43.2.4;

### Screenshots encouraged
[latest.log](https://github.com/Tschipp/CarryOn/files/10777399/latest.log)

**Comment by Tschipp** [comment]
Same issue as https://github.com/Tschipp/CarryOn/issues/474, which I've since fixed (at least to my knowledge),
so I think this is on the side of Debugify Reforged
