### ISSUE TITLE
Transparent entities with shaders on

### ISSUE THREAD

**Issue by pocinhas** [Tschipp/CarryOn#465]
### Expected Behavior
Not transparent entities when shaders on

### Actual Behavior
Entities transparent when picked up, shaders on

### Steps to Reproduce
Pick up an entity and look at it at direct sun light. I've reported this to the complementary dev and he said
 "Emin — Today at 12:15 AM
The entity isn't being drawn into the depth buffer then 😔
This is a problem that can't be fixed in the shader side" 

### Version of Minecraft, Carry On, Forge/Fabric
1.19.2, fabric 0.14.14, carryon 2.0.4.6 and a whole lotta other universal side mods, including iris 1.4.5 and sodium 0.4.4

### Screenshots encouraged
Issue goes away when I disable light shafts on complementary reimagined:

![2023-02-21_00 33 20](https://user-images.githubusercontent.com/101492556/220217903-2c891859-06cb-415d-9da2-4ab03f8da9ab.png)
![2023-02-21_00 33 27](https://user-images.githubusercontent.com/101492556/220217908-c0a8b304-670e-4c21-8e9c-05afae3fbc98.png)

**Comment by Gunseeker** [comment]
Also having this issue as of 5/6 when using Oculus on Forge using both versions of Complementary Shaders. The issue occurs with Carry On, Oculus, and Rubidium enabled.
(Oculus is the forge port of Iris, Rubidium is forge port of Sodium)

Edit: The transparency issue does not occur when using the same shaders with OptiFine, although held entities an the arms don't seem to have soft shading on them

Screenshots when using shaders + optifine
![2023-05-06_13 46 24](https://user-images.githubusercontent.com/42528699/236646016-f390bddf-96c7-403f-ae75-845319a97022.png)
![2023-05-06_13 46 28](https://user-images.githubusercontent.com/42528699/236646019-a740d8c3-2bfa-47e3-a19c-33f139defd1f.png)
The pig when not being carried for reference
![2023-05-06_13 50 06](https://user-images.githubusercontent.com/42528699/236646086-f0588815-0855-4cb8-8220-c8524227176f.png)

**Comment by Barerock** [comment]
Same issue with oculus using Nostalgia shaders.

**Comment by Felisinnn** [comment]
Same issue with iris photon v1 shaders

**Comment by Tschipp** [comment]
Yeah shaders aren't really supported, sorry.

**Comment by PGC48** [comment]
Same issue with iris derivative-shaders
