### ISSUE TITLE
Missing position update in some block entities

### ISSUE THREAD

**Issue by 0x000006** [Tschipp/CarryOn#466]
### Steps to Reproduce

- Place down a Sculk Sensor, Sculk Shrieker or a Sculk Catalyst.

- Move the block somewhere else using shift + right click.

- Run the command "/data get block <new position of the block> listener.source.pos".

### Expected Behavior

The command returns an int[] with the **new** position of the block.

### Actual Behavior

The command returns the **old** position of the block.

### Version of Minecraft, Carry On, Forge/Fabric

Minecraft 1.19.3, Carry On v2.0.4.15, Fabric

**Comment by Tschipp** [comment]
Since it's saved in NBT, and seems to be unique to sculk blocks, I'd need to hardcode it for them. How did you figure out that this data wasn't updated correctly?

**Comment by 0x000006** [comment]
> How did you figure out that this data wasn't updated correctly?

Vibrations were behaving weirdly, going to places where nothing existed
