### ISSUE TITLE
[1.10.2] Ticking memory connection when loading a world

### ISSUE THREAD

**Issue by ACGaming** [Tschipp/CarryOn#47]
- Forge 12.18.3.2511
- Carry On 1.6

Client crash: https://paste.ubuntu.com/25885474/
Server crash: https://paste.ubuntu.com/25885548/

It's quite inconsistent. Sometimes you can even log in and crash later on.

**Comment by Tschipp** [comment]
Yep, got it. Reason for the crash is that the player isn't holding an Item (and 1.10 ItemStack handling is shit).
