### ISSUE TITLE
[1.19.2] [fabric] incompatibility with another mod

### ISSUE THREAD

**Issue by 8Ascoth8** [Tschipp/CarryOn#470]
### Expected Behavior
being able to pick up

### Actual Behavior
not being able to pick up

### Steps to Reproduce
install the mod "quantum encapsulation", latest version

### Version of Minecraft, Carry On, Forge/Fabric
1.19.2, 2.0.4.6, 0.14.13

**Comment by Tschipp** [comment]
What are you trying to pick up? You might need to change some config settings, to be able to pick up all blocks.
