### ISSUE TITLE
[1.19.2 Forge] Crash upon picking up an Ars Elemental summoned skeletal steed

### ISSUE THREAD

**Issue by CreatedorMade** [Tschipp/CarryOn#471]
### Expected Behavior
Expected to be able to pick up summoned skeletal steed

### Actual Behavior
Server crashes, nearby players crash as well
Malformed CarryOnData tag saved in the player's data causes the server to crash again with the same error when they log in again, and must be removed with an NBT editor before they can rejoin
![image_2023-02-25_211614302](https://user-images.githubusercontent.com/34165090/221392037-d85ae942-0454-4696-862d-2a6b1c5cfb5d.png)
![image](https://user-images.githubusercontent.com/34165090/221392160-dc285ef5-9111-42db-bf75-e13c67697982.png)

### Steps to Reproduce
Install Ars Noveau and Ars Elemental, find and use a Skeletal Steed tome, then try to pick up the summoned skeleton horse

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2
Forge 43.2.0
Carryon 2.0.5.10

**Comment by Tschipp** [comment]
patched this to fail quietly, instead of crashing the server
