### ISSUE TITLE
Unable to pickup and carry villagers 

### ISSUE THREAD

**Issue by Henzilla728** [Tschipp/CarryOn#475]
### Expected Behavior
Pick up with Shift + Rclick villagers and drop them with Rclick

### Actual Behavior
Unable to pickup villagers no matter how close or with nothing in inventory, able to pick up all other items and entities 

### Steps to Reproduce
Walk up to villager Shift + Rclick on villager 

### Version of Minecraft, Carry On, Forge/Fabric
Better MC [FABRIC] 1.19.2 v16.5

**Comment by chorbintime** [comment]
we disabled villager pickup in v16, as mentioned in the changelog. this isnt a bug.

**Comment by juandavidkincaid** [comment]
Yeap ok, but why?, unfortunately I was unable to find that changelog.

**Comment by ciqven** [comment]
I was also looking for the answer to this, and after clicking on each file marked for a v16.* on CurseForge, I could not see anything about disabling villagers. Would anyone in the know be so kind to provide a pointer to the relevant changelog?
