### ISSUE TITLE
Fabric 1.19.2, game stopped working out of nowhere

### ISSUE THREAD

**Issue by Larkygal420** [Tschipp/CarryOn#480]
### Expected Behavior
The game was running fine 

### Actual Behavior
Suddenly the game started crashing and now it won't launch at all, citing Carry On as the issue

### Steps to Reproduce
i am unsure how this happened

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2, Carry On 4.0.2.6, Fabric 0.14.18

### Screenshots encouraged
[crash-2023-03-26_21.27.42-client.txt](https://github.com/Tschipp/CarryOn/files/11074157/crash-2023-03-26_21.27.42-client.txt)

**Comment by Tschipp** [comment]
somehow the config is corrupted... try deleting it. I'll add some safeguards for this
