### ISSUE TITLE
Carry On 1.19.3 with 1.19.4 Forge Crash Report

### ISSUE THREAD

**Issue by Nimportance** [Tschipp/CarryOn#488]
[crash-2023-04-13_09.22.40-fml.txt](https://github.com/Tschipp/CarryOn/files/11223204/crash-2023-04-13_09.22.40-fml.txt)

[latest.log](https://github.com/Tschipp/CarryOn/files/11223224/latest.log)

![Screenshot 2023-04-13 092852](https://user-images.githubusercontent.com/125213279/231791397-229be407-d674-4d27-9f0b-aa376b272498.png)

All you need to know within those two files. I am trying to use the Carry On 1.19.3 latest version for 1.19.4 but I get a Check Spawn error. The other errors may be leaking too.

**Comment by Tschipp** [comment]
Update for 1.19.4 will be out shortly
