### ISSUE TITLE
Crash on Fabric 1.19.4 when trying to get a chest

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#489]
### Expected Behavior
When pressing Carry Key (for me set to Left Alt) + Right Click, the chest would start being carried and the player should be rendered with the chest on hands.

### Actual Behavior
When i try to carry the chest, the game immediately crashes.

### Steps to Reproduce
1. Start a survival world on LargeBiomes
2. Craft a chest or get from a village
3. Place that, fill with items and try to carry it.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.4
Carry On: carryon-fabric-1.19.3-2.0.4.15
Fabric Loader: 0.14.19
Fabric API: fabric-api-0.78.0+1.19.4

### Screenshots encouraged
I don't have a screenshot to share, but i have [a crash report](https://gist.github.com/vico93/0bddd1addbe5d62e9370a28286c0fcd0).

**Comment by Tschipp** [comment]
Update for 1.19.4 will be out shortly
