### ISSUE TITLE
My game crash on new version

### ISSUE THREAD

**Issue by Notimagination** [Tschipp/CarryOn#490]
### Expected Behavior

I update the mod from 2.5.0.10 to 2.5.0.11

### Actual Behavior

My game just cransh on start, only happens with the 2.5.0.11 version

### Steps to Reproduce

As soon as I start the game, it crashes

### Version of Minecraft, Carry On, Forge/Fabric

Minecraft 1.19.2

Carry On 2.5.0.11

Forge 43.2.8

**Comment by Tschipp** [comment]
Do you have a log?

**Comment by Thysium** [comment]
Hello, i also have this mistake.

I don't have any error reports because it happens during the game launch.

![Capture d’écran 2023-04-26 092134](https://user-images.githubusercontent.com/25851859/234500499-fa0ed411-2926-4223-82c8-75201e61a825.png)
The previous version of this mod works.

**Comment by Tschipp** [comment]
Please go to the logs directory of your minecraft installation and send me the latest.log

**Comment by Thysium** [comment]
I hope this will be useful to you.

[latest.log](https://github.com/Tschipp/CarryOn/files/11330199/latest.log)

**Comment by Silba93** [comment]
> Do you have a log?

I have the same issue(same mc, forge and carry on versions), no real error message and it crashes before much even loads. Previous version is fine.
Just thought i'd chime in with my log.

Good luck, and thanks for the awesome mod :)

[2023-04-26-3.log.gz](https://github.com/Tschipp/CarryOn/files/11337987/2023-04-26-3.log.gz)

**Comment by HumanF91R** [comment]
[latest.log](https://github.com/Tschipp/CarryOn/files/11347182/latest.log)
having the same problem as well

**Comment by 2ndkirbyever** [comment]
[latest.log](https://github.com/Tschipp/CarryOn/files/11349210/latest.log)
I am also having the same issue.

**Comment by Tschipp** [comment]
Should be fixed now, rolling out an update.
