### ISSUE TITLE
Invisible bells with LambaBetterGrass

### ISSUE THREAD

**Issue by SplendidAlakey** [Tschipp/CarryOn#491]
### Expected Behavior

The bell rendering in 1st and 3rd person when carried.

### Actual Behavior

The bell is invisible when carried. More blocks might be affected, but from my personal testing I could only find bells, that are bugged.

### Steps to Reproduce

Simply install [LambdaBetterGrass](https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass/files/3834055) and Carry On, then pick up a bell.

### Version of Minecraft, Carry On, Forge/Fabric

**MC** 1.19.2
**Fabric** Loader 0.14.19 + API 0.76.0
**Carry on** 2.0.5.11

### Screenshots encouraged

![2023-04-26_08 37 28](https://user-images.githubusercontent.com/86702831/234490248-3ca45b5c-293a-454a-9072-95a611f6e930.png)
![2023-04-26_08 37 38](https://user-images.githubusercontent.com/86702831/234490261-55bc0954-913a-44f0-a58e-52900d08e207.png)

Logs: https://gist.github.com/SplendidAlakey/454affda76da11683ed1d986d85ec557

**Comment by Tschipp** [comment]
Yeah, I think I implemented this "fix" as opposed to crashing, so I think this is as good as it's gonna get, sorry.
