### ISSUE TITLE
1.18.2 [Forge] Hard Crash MC Client

### ISSUE THREAD

**Issue by DemonSeedxp** [Tschipp/CarryOn#492]
### Expected Behavior
When carrying entity, pressing shift should still perform normal functionality such as preventing other inventory's from opening if clicked.    

### Actual Behavior
With entity in hand, holding shift while placing down chest next to crafting table allows inventory to open, resulting in a hard crash of the client

### Steps to Reproduce
Place entity against face of crafting bench

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.18.2, Carryon 17.1.11, Forge 40.2.1

### Screenshots encouraged
[crash-2023-04-26_14.21.33-client.txt](https://github.com/Tschipp/CarryOn/files/11336329/crash-2023-04-26_14.21.33-client.txt)

**Comment by Tschipp** [comment]
Do you have any other mods? I can't recreate this with just carry on

**Comment by DemonSeedxp** [comment]
Oh yes a bunch, I added this to a FTB Stone block 3 world so yeah, like 234 mods in the mods folder.

It also seems that theres no getting back into the world as the player is still holding the chest on reload and it just crashes again
[crash-2023-04-26_14.50.30-client.txt](https://github.com/Tschipp/CarryOn/files/11336369/crash-2023-04-26_14.50.30-client.txt)

**Comment by DemonSeedxp** [comment]
dont know if it matters but I was carrying a crystal chest

**Comment by DemonSeedxp** [comment]
is there any way to remove the item from my players possession through the world files level. dat? 
I seriously don't want to roll back an hour of gameplay. I'd rather sacrifice the chest and its contents if I had a choice in the matter.

**Comment by DemonSeedxp** [comment]
![Screenshot 2023-04-26 153331](https://user-images.githubusercontent.com/11554194/234683578-f02086a6-afa8-43c9-a833-36c7d8fff8c2.png)
Ok, so I located it in my player data through NBTExplorer, only problem now is I don't know what edits to make to either have it put in my inventory or removed completely.

Any assistance would be greatly appreciated!

**Comment by Tschipp** [comment]
Remove any entry that has "carryon:tile_item" or "carryon:entity_item"

**Comment by DemonSeedxp** [comment]
Sweet, that worked! Bonus, I was even able to save the chest and its contents from being deleted!  I'm calling that a win and backing away slowly because rarely do things pan out in my favor. So I'm just waiting for the other shoe to drop and something awful happening, like a singularity spontaneously forming and voiding my entire world or something... lol 

Thanks for the assistance!

**Comment by Tschipp** [comment]
Sorry about the trouble... I really don't know why the crafting gui is opening...

**Comment by DemonSeedxp** [comment]
yeah idk, it too was a modded block, so I guess it could just as easily been that mods fault as it was this one's. I don't know what mod the other block belongs to, but it was the cobble crafting bench the FTB team replaced the vanilla one with if that helps narrow it down any.

**Comment by Tschipp** [comment]
that helps, thanks!

**Comment by Tschipp** [comment]
I still cannot reproduce this... could you record a short clip of the problem happening?

**Comment by DemonSeedxp** [comment]
I can if you still need it, but I see you tagged as fixed so just let me know. I'll leave this tab open for a while to catch your response quicker

**Comment by Tschipp** [comment]
Yeah I think I've managed to fix a related bug, that should also fix this.
