### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [Tschipp/CarryOn#495]
In version 1.19.3 2.0.4.15 the game crashes when I try to move villagers with professions.

[rei.log](https://github.com/Tschipp/CarryOn/files/11357500/rei.log)
[rei-issues.log](https://github.com/Tschipp/CarryOn/files/11357501/rei-issues.log)
[latest.log](https://github.com/Tschipp/CarryOn/files/11357502/latest.log)
[crash-2023-04-29_00.45.44-client.txt](https://github.com/Tschipp/CarryOn/files/11357503/crash-2023-04-29_00.45.44-client.txt)

**Comment by Tschipp** [comment]
Sorry, I don't think I will push more updates to 1.19.3

**Comment by Rogenar** [comment]
I told you the bug in the mod, it's up to you whether to fix it or not.
