### ISSUE TITLE
Entities stacking.

### ISSUE THREAD

**Issue by Aceplante** [Tschipp/CarryOn#496]
Why do entities stack? If this is intentional, can it at least be configurable?

### Expected Behavior
Entities to be placed on the ground next to the existing one

### Actual Behavior
Entities stack if you accidently click on their hitbox

### Steps to Reproduce
Make a pen
Fill it with pigs
Try to put another one it
It will be almost impossible to not have it stack on an existing pig

### Version of Minecraft, Carry On, Forge/Fabric
Forge 1.18

**Comment by SplendidAlakey** [comment]
Not sure about Forge 1.18, but on 1.19 versions we have lots of config options to alter stacking, such as `maxEntityStackLimit` to specify how many entities can be stacked at once, `useWhitelistStacking` + `allowedStacking` to let only whitelisted entities stack, `stackableEntities` can disable the feature altogether, `entitySizeMattersStacking` defines whether the size of the entity matters and `forbiddenStacking` lets you blacklist mobs without using a whitelist. All of these are located in `carryon-common.json`

**Comment by Aceplante** [comment]
It appears to have world specific config files. Thanks. Perhaps it should be off by default?
