### ISSUE TITLE
Sound when opening a double chest placed with CarryOn sounds like two different chests at the same time.

### ISSUE THREAD

**Issue by akai-hana** [Tschipp/CarryOn#500]
### Expected Behavior
Opening a double chest sounding normally, like a single chest.

### Actual Behavior
Opening it sounds like two different chests are opening at the same time.

### Steps to Reproduce
- Place a chest (by hand or with carryon, doesn't matter)
- Use carryon to carry a chest and place it at the right/left of the previously placen chest, so that both chests connect together.
- Now this double-chest will sound wrong.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2, lastest version of Carry On `(carryon-fabric-1.19.2-2.0.5.11)`

### Screenshots encouraged
I can´t screenshot a sound. Either way, it looks exactly the same as a double chest, so no issues on the visual side.

**Comment by Tschipp** [comment]
Can't recreate this. Are you on a server or singleplayer world?

**Comment by akai-hana** [comment]
it happened to me on both a singleplayer world, and on a server.

im going by memory, since this was some time ago, but if you place a chest with your cursor facing to another chest, it won't make that double sound, but if you place it on the ground, lets say, or anywhere where your cursor isnt directly touching the other chest, it will make that sound.

try putting items on the chest too, idk.
if no matter what, you can't reproduce it, idrk. Ive long since lost the files of my modpack instance (which didnt have a ton of mods) and my world, so not even I can reproduce it anymore.

**Comment by akai-hana** [comment]
sorry for closing. missclick.

**Comment by vico93** [comment]
I have the same issue on 1.20.1 with 2.1.1.3. Actually i remember having this issue in 1.19.4 as well.

If @Tschipp have interest i can send to him via Discord my profile folder (with all the mods and packs i use) and a save to him to test.

**Comment by vico93** [comment]
Ah, of course, here's a video proof of the issue:

https://github.com/Tschipp/CarryOn/assets/3485505/2d9370af-e8ab-40ae-a365-19f490872e7d


If you pay attention the first time i picked one of the chests it actually start making no sound (only the other part did), and placing it back start the double sound issue. The second time i picked the chest it did the normal sound when single, but when placing both together the double sound happened again - to fix that one needs to normally break one of the chests and then place it alognside the other.

**Comment by darkwiz666** [comment]
I've been able to replicate this too, singleplayer world, except for mine if you place the chest and open it it's playing the sound twice at the same time...you can tell by how much more depth it has on top of being slightly louder.

**Comment by Tschipp** [comment]
still cannot reproduce this... maybe a recent change that I did fixed it. I'll mark this as fixed, can be reopened if it still persists. It may also be a cross-mod conflict.
