### ISSUE TITLE
Beehives lose honey level

### ISSUE THREAD

**Issue by Aceplante** [Tschipp/CarryOn#502]
### Expected Behavior
beehives should maintain their honey level when moved

### Actual Behavior
they do not

### Steps to Reproduce
Wait for a beehive to be full.
Move it

### Version of Minecraft, Carry On, Forge/Fabric
1.18.2

**Comment by Tschipp** [comment]
This is the same problem as with music disks. Fixed in 1.19 and up, but I will not backport it to 1.18.
