### ISSUE TITLE
[1.18.2] Consistent memory leak

### ISSUE THREAD

**Issue by MisterEffWord** [Tschipp/CarryOn#512]
Using the latest version of 1.18.2, whenever this mod is active I notice a gradual but consistent memory leak. When not active, said memory leak goes away.

**Comment by Tschipp** [comment]
What do you mean with "active"? How have you measured the memory leak? I don't really see how memory is supposed to leak in a pure java game

**Comment by MisterEffWord** [comment]
> What do you mean with "active"? How have you measured the memory leak? I don't really see how memory is supposed to leak in a pure java game

By active I meant installed. I've noticed in task manager that the memory usage in javaw.exe gradually increases until it caps out my system memory usage and I have to close and restart the game, only for it to begin to gradually increase again after loading a world.

**Comment by Tschipp** [comment]
Does this happen when only carry on is installed? Have you compared it to vanilla or unmodded forge?

**Comment by Tschipp** [comment]
related to https://github.com/Tschipp/CarryOn/blob/e1da67a2505324f685d7a83344d6364fd1945a86/src/main/java/tschipp/carryon/client/event/RenderEvents.java#L331-L337
