### ISSUE TITLE
Question about 1.20

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#514]
Sorry to sound annoying (not my intention), but is an 1.20 update in the plans?

Thanks a lot for this mod (essential to me)

**Comment by vico93** [comment]
any news?

**Comment by OBS3SS1ON** [comment]
x2 any new about update to 1.20.1 forge?? :(

**Comment by Trickstyr** [comment]
I second this, I really want to be able to continue using this!
However I don't see any activity from this mod since April so it might be a while if an update even comes.

**Comment by vico93** [comment]
I asked on [this Discord server](https://discord.gg/T5WaaSDate) if somebody could PR/fork an update for 1.20.1. Lets see if something happens!

**Comment by FAKHORII** [comment]
the other similar mod to this called [carrier](https://www.curseforge.com/minecraft/mc-mods/carrier) for 1.20/1.20.1 got released yesterday, although this one is better and still waiting for an update

**Comment by OBS3SS1ON** [comment]
> the other similar mod to this called [carrier](https://www.curseforge.com/minecraft/mc-mods/carrier) for 1.20/1.20.1 got released yesterday, although this one is better and still waiting for an update

[carrier](https://www.curseforge.com/minecraft/mc-mods/carrier) is a fabric mod if it's not bad, but i want one to forge 1.20.1

**Comment by FAKHORII** [comment]
ah but I play on fabric cus its way more optimized, and we both gotta wait for carry on mod anyways

**Comment by OBS3SS1ON** [comment]
yes just have to wait to fabric, I have 154 mods on last forge, not bad :) oculus + rubidium

**Comment by Tschipp** [comment]
I'm working on it

**Comment by Tschipp** [comment]
It is finished, should be up on curse and modrinth soon.

**Comment by FAKHORII** [comment]
> It is finished, should be up on curse and modrinth soon.

yeah well, its only for 1.20.1 and not for 1.20, as my most mods are I just cant update yet, dang... unlucky
