### ISSUE TITLE
Incompatibility with Rats mod

### ISSUE THREAD

**Issue by CircusSeal** [Tschipp/CarryOn#515]
### Expected Behavior
Rats should be placed on head/shoulder when I sneak and right-click them. 

### Actual Behavior
The Carry On mod interferes, causing the game to use Carry On's carrying system instead of Rats'. Therefore, I can't put rats in cages.

### Steps to Reproduce
Try to pick up a rat with both these mods installed

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.16.5, Carry On 1.15.5.22, Forge 36.2.34

**Comment by ElNico56** [comment]
just rebind carryon to any key but shift, maybe alt

**Comment by Tschipp** [comment]
>  just rebind carryon to any key but shift, maybe alt


This is correct, or blacklist the rats from carryon
