### ISSUE TITLE
Why is there no release of fabric for 1.18.2?

### ISSUE THREAD

**Issue by Hhaha233** [Tschipp/CarryOn#519]
### Expected Behavior
I really like this mod. I expect the mod to have a fabric release for 1.18.2.

### Actual Behavior
I don't see any fabric release for 1.18.2 and below in those websites like CurseForge.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft:1.18.2    Carry On: Any    Fabric    

### --------------
_I don't know how to compile by myself._
I'm sorry, this question may seem to be a little silly here. But I really need it and I believe many people also need it.

**Comment by Tschipp** [comment]
I rewrote the mod for 1.19.2, I'm not gonna make versions for 1.18.2 for fabric, sorry
