### ISSUE TITLE
Blacklist broken on integrated servers

### ISSUE THREAD

**Issue by moonfather1** [Tschipp/CarryOn#520]
### Expected Behavior
I should not be able to pick up blacklisted blocks (parts of a multiblock structure).

### Details
Carry on currently processes blacklist messages (IMC) in "dedicated server start" event instead of "process imc" event. As a result, blacklist does not work at all on integrated server (in singleplayer).

### Version of Minecraft, Carry On, Forge/Fabric
mc 1.18-1.20, forge

**Comment by copygirl** [comment]
I believe this is still broken. My current guess is that config loads after IMC is processed, causing `initConfigLists` to clear out any of the added entries and replacing them with *only* the ones from the configuration file. The workaround appears to be to instead add the blocks to the `#carryon:block_blacklist` tag.

**Comment by moonfather1** [comment]
huh? there is a tag? since what version?

on that note, @Tschipp , both neoforge and fabric have standardized block tag for this - `c:relocation_not_supported` - carryon should use that.

**Comment by copygirl** [comment]
> huh? there is a tag? since what version?

It was mentioned in the other issue (#361), so at least a couple of years.

> both neoforge and fabric have standardized block tag for this

`c:relocation_not_supported` is blacklisted by default [in the config](https://github.com/Tschipp/CarryOn/blob/de388366cac75df0077c4cd96941d8518c2400a8/Common/src/main/java/tschipp/carryon/common/config/CarryConfig.java#L250).
