### ISSUE TITLE
Carryon crashing xaero's worldmap when scrolling

### ISSUE THREAD

**Issue by SxRHunter** [Tschipp/CarryOn#522]
### Expected Behavior
Zooming in/out

### Actual Behavior
Crashing

### Steps to Reproduce
Carry on with both xaero's worldmap and minimap
Enter world open map and use the scroll

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1, carryon 2.1.0.1, Fabric

**Comment by SxRHunter** [comment]
[crash-2023-07-07_04.23.19-client.txt](https://github.com/Tschipp/CarryOn/files/11973761/crash-2023-07-07_04.23.19-client.txt)

**Comment by Tschipp** [comment]
This mentions amecs, but carry on only has a soft dependency on it. So I don't think it's carry on.

**Comment by Tschipp** [comment]
Nevermind.... #523 seems to be the same issue so there probably is some problem of carry on here...
