### ISSUE TITLE
New Version for 1.19.2 results in instant crash on world load.

### ISSUE THREAD

**Issue by NolanHewitt** [Tschipp/CarryOn#524]
Version 2.0.5.17 for Fabric 1.19.2 crashes instantly when loading a world. Version 2.0.5.11 works just fine.

**Comment by noncom** [comment]
Confirming. Some critical injection failure for amecsapi.

**But not on world load. For me it crashes on client load, 1.5 seconds into the red Mojang loading screen.**

No crashlog is generated but there's an exception in the normal log.
Attaching the log.

[latest.log](https://github.com/Tschipp/CarryOn/files/11986314/latest.log)
