### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [Tschipp/CarryOn#525]
There is a bug like not being able to overflow chests. Typo fixed*
[latest.log](https://github.com/Tschipp/CarryOn/files/11981795/latest.log)
[rei.log](https://github.com/Tschipp/CarryOn/files/11981799/rei.log)
[rei-issues.log](https://github.com/Tschipp/CarryOn/files/11981807/rei-issues.log)

**Comment by Tschipp** [comment]
Vanilla chests? What do you mean with barrels?

**Comment by Rogenar** [comment]
The mod is not working properly.
