### ISSUE TITLE
1.19.2 Fabric - Opening the keybind menu crashes the game

### ISSUE THREAD

**Issue by graytonio** [Tschipp/CarryOn#526]
### Expected Behavior
Opening the keybind menu works as expected

### Actual Behavior
Opening the keybind menu crashes the game

### Steps to Reproduce
- Install only carry on and fabric
- Open keybind menu

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft - 1.19.2
Carry On - 2.0.5.17
Fabric API - 0.76.0
Fabric Loader - 0.14.21

**Comment by graytonio** [comment]
Confirmed changing the version of the mod to 2.0.5.11 resolved the issue.
Seems like this commit has something to do with it.
https://github.com/Tschipp/CarryOn/commit/1ca409c43d19c2a452f09f3de15e318dc72c1fa6#diff-153d20c41d71a638a5f51dc4aa16dbd00b1ff22e39334ea71864c028b1d04a77R17

**Comment by inikishev** [comment]
https://gist.github.com/stunlocked1/2a8e16febad27fd739485281c514f31a same issue it mentions amecs api but i tried it both with and without amecs and it crashes

**Comment by ScoutTheSaneless** [comment]
can also confirm this issue

**Comment by whatamaniac** [comment]
Facing the same issue on 2.0.5.17. I don't have amecs but still Crashing when opening Keybinds Menu.

**Comment by capasseidk** [comment]
had this issue as well i also tried going to an older version and it works now i dont know how to crash report
