### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [Tschipp/CarryOn#528]
the mod is not working properly, not fully working. i can't move storage units that come with another mode manually
for example; iron chests mode

**Comment by Tschipp** [comment]
What version? What launcher? What are your keybinds? What is your config?

**Comment by Rogenar** [comment]
Mod versiyon; carryon-fabric-1.20.1-2.1.1.2
Fabric loader versiyon; 0.14.21-1.20.1
[rei.log](https://github.com/Tschipp/CarryOn/files/12001998/rei.log)
[rei-issues.log](https://github.com/Tschipp/CarryOn/files/12002005/rei-issues.log)
[latest.log](https://github.com/Tschipp/CarryOn/files/12002006/latest.log)

**Comment by Tschipp** [comment]
These logs do not really help me, I need the other information as well

**Comment by Rogenar** [comment]
ok i solved the problem.
