### ISSUE TITLE
Crash when picking up any mob.

### ISSUE THREAD

**Issue by ItzNatsu** [Tschipp/CarryOn#529]
### Expected Behavior
Carrying any mob should work as expected but it causes a crash. server doesn't crash though. and when re-entering the server, the mob is carried and the game continues to function normally until you carry another mob.

### Actual Behavior
The mob should pop into the player's hands without a crash.

### Steps to Reproduce
1. Install Carry On 2.1.1.2 Fabric 1.20.1 with the mods listed in my logs
2. Enter a server and try picking up a mob
### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.20.1
Fabric 0.14.21
Carry On 2.1.1.2

Logs: https://paste.ee/p/oQWap

**Comment by papamaionise** [comment]
I have the same issue with way few mods I can pick chests with out the game crashing but it crashes when picking mobs.

**Comment by papamaionise** [comment]
It's because of solid mobs mod removing the mod fixes the issue 
I reported this to their discord
I hope it gets fixed :(

**Comment by papamaionise** [comment]
@ItzNatsu  Carry on mod works perfectly fine issue is completely because of Solid Mobs mod game crashes when you shift click a mob if you want to use both mods together just **assign another key for picking stuff up anything besides shift**
