### ISSUE TITLE
Ability to pick and place chests on boats and minecarts

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#530]
Basically, when trying to pick a boat or minecart with chest (actually with any block that can be picked normally when placed), first attempt to extract the chest, only its empty (or with another non-pickable block/entity) the mod will allow to pick the boat/minecart itself.

Conversely, of one attempts to place a chest (or other block that can be placed on) on a boat/minecart, actually assemble a 'boat/minecart with chest/other block'. That would greatly allow transportation of stuff without need to transfer between a placed chest to the embedded chest on the boat/minecart.

**Comment by Tschipp** [comment]
duplicate #503

**Comment by vico93** [comment]
I'm a little bit embarassed seeing that i make a almost exact copy of a previous issue without realizing. So much sorry for that.
