### ISSUE TITLE
Objects and mobs are invisible in third person

### ISSUE THREAD

**Issue by BR77K** [Tschipp/CarryOn#532]
### Expected Behavior
![Expected Behavior](https://github.com/Tschipp/CarryOn/assets/97665983/c61ef16b-5c62-4c06-ad28-c9ad4e09ab07)

### Actual Behavior
![Actual Behavior](https://github.com/Tschipp/CarryOn/assets/97665983/12652517-4ebd-4397-a959-ff71fff14567)

### Steps to Reproduce
Pick up any object or mob that the mod allows and put third person (or look to another player picking something up)

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 - carryon-fabric-1.20.1-2.1.1.2

**Comment by Tschipp** [comment]
any other mods?

**Comment by BR77K** [comment]
This is my mods folder 
![image](https://github.com/Tschipp/CarryOn/assets/97665983/19183b6a-155c-4164-8ab8-3e188c774042)

**Comment by BR77K** [comment]
> any other mods?

This is my mods folder 
![image](https://github.com/Tschipp/CarryOn/assets/97665983/9125cfe0-6ea8-479a-8f91-d4c2a42a49f0)

**Comment by Tschipp** [comment]
yeah probably optifine, sorry.
