### ISSUE TITLE
Barrels return their previous facing direction when opened

### ISSUE THREAD

**Issue by Clarthen** [Tschipp/CarryOn#535]
### Expected Behavior
Barrel retains its new facing direction when placed with different facing direction.

### Actual Behavior
Barrel returns to its previous facing direction (before it was picked up) when opened, unless you rejoin the world.

### Steps to Reproduce
1. Place a barrel
2. Pick it up
3. Place it down with different facing direction
4. Open it

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft: 1.20.1
CarryOn: 2.1.1.2
Fabric Loader: 0.14.21
Fabric API: 0.86.0

**Comment by sdarkwell** [comment]
This also affects Minecraft v1.19.2 and the Forge mod loader.
