### ISSUE TITLE
Stuck Holding Entities

### ISSUE THREAD

**Issue by Levgacy0515** [Tschipp/CarryOn#540]
### Expected Behavior
Picking up a campfire causes a failure to render the block and crashes the game until the mod is disabled. After disabling no inventory can be opened, and hotbar cant be changed. Dying in attempt to drop the block results in the in-ability to respawn. 

Picking up a witches altar on accident results in being unable to set it back down.

Finally on my third account I picked up a celestium chest from the mythic metals mod and am now unable to set it back down.

### Actual Behavior
Unable to set the blocks back down after carrying them resulting in either the game crashing, or the disability of only being able to move around and essentially spectate.

### Steps to Reproduce
Pick up a campfire to crash the game.
Pick up a witches altar from the bewitchment mod to forever get stuck holding it.
Pick up a mythic metals chest and also get stuck holding it.

### Version of Minecraft, Carry On, Forge/Fabric
carryon-fabric-1.19.2-2.1.0.19.jar

### Screenshots encouraged
[crash-2023-08-09_15.44.52-client.txt](https://github.com/Tschipp/CarryOn/files/12310894/crash-2023-08-09_15.44.52-client.txt)

**Comment by Levgacy0515** [comment]
I am using the Medieval MC Fabric modpack. https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric-mmc1

**Comment by whatzittuuyah** [comment]
i've experienced the same issue with the bewitchment Elder Door in the same modpack. I can't put the door down. Relogging makes the glitched item behave as though it's not in my hands anymore (slowness and sound remaining) until I right click or crouch. 

EDIT: I picked up the top half of the door, which is what broke it. I had to die to drop it, now the top half of that door just exists in-world on the floor. 

In the state where I relogged into the server, gaining temporary access to my hand and menus, if I had an item in my hand before right clicking, I would not have the door put in my hand when right clicking. I could fight, and cast Archon spells, but i could not "use item" interact with any block or inventory item, including eating or drinking. 

EDIT 2: fixed typos

**Comment by Tschipp** [comment]
Is it a vanilla campfire? In general, multiblocks shouldn't be picked up. For all these blocks, they should be added to the blacklist by the modpack creator. 
FYI: if you're ever left with an unplaceable block/entity, you can run `/carryon clear` to remove it
