### ISSUE TITLE
Whitelisted item tags not registering until refresh of config

### ISSUE THREAD

**Issue by Duxtorm** [Tschipp/CarryOn#544]
"When I start a world, anything where I've whitelisted the tag for the item in the config won't work; can't pick it up..
I can only fix it by altering the config, saving it, then changing it back and saving it again..
Ultimately not actually changing the config, just allowing it to register by re-saving it.. it just doesn't seem to properly read the config when I start a world."

Carry On: 2.1.0.1
Forge: 47.1.30

**Comment by Tschipp** [comment]
Are you editing the tags themselves, or the carry on config?
