### ISSUE TITLE
Normal Chests Are Not Picked Up

### ISSUE THREAD

**Issue by Shananiganeer** [Tschipp/CarryOn#546]
### Expected Behavior
Pick up chests with Shift+Right click

### Actual Behavior
Chest inventory is opened. Trapped Chests, Ender Chests, and Entities are picked up as expected.

### Steps to Reproduce
Attempt to Shift+Right click a normal chest

### Version of Minecraft, Carry On, Forge/Fabric
MC: 1.18.2
Forge: 40.2.0
CO: 1.17.1.12
All other mods were removed to verify the issue is with Carry On.

### Screenshots encouraged
![2023-08-22_02 24 30](https://github.com/Tschipp/CarryOn/assets/20528114/743952c9-c07c-481c-802f-3f6ff85db61c)
![2023-08-22_02 24 34](https://github.com/Tschipp/CarryOn/assets/20528114/55d17012-120d-4894-8151-4968e5bdc7f7)
![2023-08-22_02 24 56](https://github.com/Tschipp/CarryOn/assets/20528114/fbea1d26-4bb1-4d56-b8c5-bb029b075be8)

**Comment by Shananiganeer** [comment]
I re-tested this with version 1.17.1.11 and it works correctly for normal chests.

**Comment by DeshiDesu** [comment]
Im having the same issue. Cannot pickup chests

**Comment by SnowBerryZ** [comment]
Same on our 1.18.2 Server with Forge 40.2.10! Only can Pickup Mobs.

**Comment by TheGag96** [comment]
Modded the `mods.toml` to be able to use with newer Forge versions on 1.20.1, cannot pick up chests there either.

**Comment by B4CKU** [comment]
Fabric version 1.20.1 here, can't pick them up either.
