### ISSUE TITLE
Can pick up mobs but not blocks

### ISSUE THREAD

**Issue by KilaxYT** [Tschipp/CarryOn#548]
### Expected Behavior

pick up blocks

### Actual Behavior

cant pick up blocks

### Steps to Reproduce

try to pick up a block

### Version of Minecraft, Carry On, Forge/Fabric

1.20.1, 2.1.1.3, fabric

### Screenshots encouraged

https://github.com/Tschipp/CarryOn/assets/118944285/bb4e0f3c-f786-40d0-aa49-06c685e41a80

**Comment by Tschipp** [comment]
you can only pick up non-blockentity blocks if enabled in the config. Can you pick up things like chests?

**Comment by KilaxYT** [comment]
yeah i can. but how do i access the config? mod menu says it doesnt have an in game config

**Comment by KilaxYT** [comment]
there isnt a config folder in the config folder

**Comment by Tschipp** [comment]
it doesn't create a folder, it creates a file (carryon-common.json) or something like that

**Comment by KilaxYT** [comment]
ah i found it. thank you!
