### ISSUE TITLE
carryon-forge-1.20.1-2.1.2.5 requires forge 46<x<47.1.3 (inclusive), but the previous version carryon-forge-1.20.1-2.1.0.1 could use the latest forge versions 47.1.44 and 47.1.46

### ISSUE THREAD

**Issue by Daltaxy** [Tschipp/CarryOn#549]
I don't know if it is intended that it can't run with the latest forge version yet, but it sounds odd, precisely because the mod was updated, and that the previous mod version ran without issues on the latest version of forge (47.1.44 at the time) for me

### Steps to Reproduce
Update to the latest version of CarryOn mentioned in the title and below

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.20.1
Forge 47.1.46 and 47.1.44

### Screenshots encouraged
![image](https://github.com/Tschipp/CarryOn/assets/111076631/7783d907-3ee8-477e-ba65-625c9369b758)
latest carryon version carryon-forge-1.20.1-2.1.2.5

![image](https://github.com/Tschipp/CarryOn/assets/111076631/7e041d37-9745-4b6d-aa2b-fd165156c3b5)
previous carryon version carryon-forge-1.20.1-2.1.0.1

**Comment by Tschipp** [comment]
It is actually intended. In case you don't know, forge has been forked into NeoForge and the old Forge is only really being maintained by the owner. He is just merging code randomly which has made newer forge versions unstable. The last stable forge version is 47.1.3.
Check this out: https://neoforged.net/news/theproject/
