### ISSUE TITLE
*SlownessMultiplier seems to have little to no effect

### ISSUE THREAD

**Issue by Jomik** [Tschipp/CarryOn#55]
### Expected Behavior
Slows down considerably.

### Actual Behavior
No noticable slow down

### Steps to Reproduce
I tried to set the SlownessMultiplier to both 0.1 and 1000, as there is no documentation on it.
But neither seem to have any considerable effect on the player's movespeed.

### Version of Minecraft, Carry On, Forge
MC 1.12.2
CarryOn MC1.12 v1.7
1.12.2-forge1.12.2-14.23.0.2545

**Comment by Tschipp** [comment]
`return (int) (i * CarryOnConfig.settings.blockSlownessMultiplier);`
The potionLevel is multiplied with the multiplier, meaning if the multiplier is 0 (as it is with empty chests for example), the multiplier get multiplied with 0, resulting in, of course, 0, so not changing the effect. Try it with a somewhat filled chest!

**Comment by Jomik** [comment]
Oh, you're right. Works!

So I guess my concern is more with https://github.com/Tschipp/CarryOn/blob/ecfe850a9934b6f13baf6031518820ae044933ac/src/main/java/tschipp/carryon/common/item/ItemEntity.java#L212

I'd think you should either call ceil or round on this. As a big is now "free" to move, since the height * width converted to an integer is 0.
And the same for the return statements in both your methods, rather than just discarding the float, why not use round it? :)

**Comment by Tschipp** [comment]
Remember, amplifier 0 means Slowness I ;)

**Comment by Jomik** [comment]
Hardly noticeable though. I'd prefer being able to set a higher base in that case. Hmm. But then again, it gets super slow with a full chest 👍
