### ISSUE TITLE
Version 2.1.2.5 incompatible with recent versions of Forge

### ISSUE THREAD

**Issue by grouNDfx** [Tschipp/CarryOn#553]
### Expected Behavior
Version 2.1.2.5 to run on Forge >47.1.3 like 2.1.0.1

### Actual Behavior
CarryOn throws an error requiring a version of Forge between 46 and 47.1.3

### Steps to Reproduce
Install the latest version of Forge for 1.20.1 (47.1.46 at time of writing)

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft: 1.20.1
Forge: 47.1.46
CarryOn: 2.1.2.5

### Screenshots encouraged
(Screenshot is with Forge 47.1.39 but it effects all versions over 47.1.30)
![image](https://github.com/Tschipp/CarryOn/assets/17791799/530fe11d-02f8-4c3a-a342-e195a16eade8)

**Comment by Tschipp** [comment]
It is actually intended. In case you don't know, forge has been forked into NeoForge and the old Forge is only really being maintained by the owner. He is just merging code randomly which has made newer forge versions unstable. The last stable forge version is 47.1.3.
Check this out: https://neoforged.net/news/theproject/

**Comment by cking** [comment]
I am using PrismLauncher, and PrismLauncher doesn't have NeoForge added just yet. This makes it a small annoyance

https://github.com/orgs/PrismLauncher/discussions/1509#discussioncomment-6684289
though 8.0 is still at 84% for release: https://github.com/PrismLauncher/PrismLauncher/milestone/9

i had to downgrade carryon for prism.
just wanted to report.

**Comment by thijsi123** [comment]
> It is actually intended. In case you don't know, forge has been forked into NeoForge and the old Forge is only really being maintained by the owner. He is just merging code randomly which has made newer forge versions unstable. The last stable forge version is 47.1.3. Check this out: https://neoforged.net/news/theproject/

may I ask where I can get 47.1.3? using 47.1.30 and lower (official forge) doesn't work either.

**Comment by Fundryi** [comment]
@Tschipp 
You are making us choose for either using old forge version or old Carry On version that has the support tag for newer versions? 

Can you not just add the support version tag to your mods? :( 
See Sophisticated Mods need now at least 47.1.5 and your mod only supports 1.3 so now I have to choose which one I use outdated and stuff.

**Comment by Fundryi** [comment]
FYI: I can understand your stands on this, but could you do a workaround like taging it as "BETA" or smth as long as CurseForge doesn't have NeoForge in their installer?

**Comment by TheCraftyCoder** [comment]
@Tschipp, I understand what you're trying to do, but the reality is that this change to only support 47.1.3 is hurting modpack maintainers. Also, this breaking change wasn't noted in the changelog :(

**Comment by thijsi123** [comment]
oops. I accidentally removed my comment.
You can change it yourself if anyone is wondering, I have no problems so far on NeoForge 47.1.76

**Comment by jojofenin99** [comment]
> oops. I accidentally removed my comment. You can change it yourself if anyone is wondering, I have no problems so far on NeoForge 47.1.76

how?

**Comment by cking** [comment]
In the jar (open as zip), go into the `META-INF` folder, open the `mods.toml` and remove the `47.1.3` text
