### ISSUE TITLE
Carryon should disable picking of autopath blocks by default

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#554]
During a chase of a couple of chicks that flee their pen, i got startled by this bizarre incident:

![2023-09-03_21 36 24](https://github.com/Tschipp/CarryOn/assets/3485505/38aee3e4-f345-494a-b325-bf13a16d0b50)

Basically, it accidentally picked up one of the @lebonq's [Autopath](https://github.com/lebonq/Automatic-Path) (mod that add grass block degradation depending of the amount of entities walking over it) blocks.

Honestly, i don't know exactly how to blacklist certain blocks of other mods (or the entire rooster of blocks of a specific mod id), but i think it would be a good thing regardless to the mod by default deny picking those blocks, since the BE they have is just for internal purposes (track the amount of wear) and not something meant to directly interact with the player (like inventories).

**Comment by Tschipp** [comment]
Imo, since it causes no problems, this is up to each user if they wanna blacklist it
