### ISSUE TITLE
[Feature Request] Ability to unlock hotbar selection

### ISSUE THREAD

**Issue by Dweblenod** [Tschipp/CarryOn#555]
It would be great to have a way to give the player normal use of their inventory even if the held item hasn't been put back down.

**Context**
There is a mod Minestuck which allows selected items to be stored in a secondary storage system on a keybind press. Since CarryOn stores the held object as an item they synergize well for the most part.

**Issue with context**
However CarryOn still believes the carried item is in selected slot. Until another object is picked up and put back down, the player cannot change which hotbar slot is selected which can be a frustration. This has been the case since at least 1.14

**Ideas**
Could come in the form of a config that checks whether the held item is no longer in the selected and frees up the hotbar or perhaps a command which could be accessible via advancement datapack. I imagine this could have use for additional mods!

**Comment by Tschipp** [comment]
No, this is intended.
