### ISSUE TITLE
Not compatible with current version of Forge for 1.20.1

### ISSUE THREAD

**Issue by brianfreud** [Tschipp/CarryOn#557]
[16Sep2023 22:35:15.452] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'carryon', Expected range: '[46,47.1.3]', Actual version: '47.1.46'

**Comment by drkhodakarami** [comment]
Plus one on this, If there is no breaking change in forge (I don't think there is?), you should leave the upper version open ended and not close the versioning like that. With your current setting, the moment forge goes one level up with a suggested versioning, people will have issue with your mod !

[    versionRange="[46,47.1.3]" #mandatory](https://github.com/Tschipp/CarryOn/blob/dbb7e59b21c2b86a8b205e77cf9e3ce4f4a70a3d/Forge/src/main/resources/META-INF/mods.toml#L22)

although it says it's mandatory, but it's exactly the problem I think?!

**Comment by zekeflynn** [comment]
+1

2 weeks for this simple fix?

**Comment by ZEROX7** [comment]
just use the older version of carry on that works with newer forge version just fine

**Comment by Tschipp** [comment]
Will be next version
