### ISSUE TITLE
Picked up blocks are instantly placed.

### ISSUE THREAD

**Issue by Jomik** [Tschipp/CarryOn#56]
### Expected Behavior
Picked up chest gets "carried"

### Actual Behavior
Chest gets picked up and immediately dropped again, if it can be placed.

### Steps to Reproduce
Look down as you pick up a chest.
As seen in the GIF, I can pick it up if I angle it precisely so that I can't place the chest after I picked it up.

### Version of Minecraft, Carry On, Forge
MC 1.12.2
CarryOn MC1.12 v1.7
1.12.2-forge1.12.2-14.23.0.2545

### Screenshots encouraged
https://i.gyazo.com/05e10f645a64653c5a555ad746d9f9e1.gif

**Comment by Tschipp** [comment]
Are you clicking once, holding or spamming? 
Clicking once picks it up normally, holding places it again but not instantly.
https://i.gyazo.com/a0c5e5471fde379a1bfe98cccf64f0a3.gif

**Comment by Jomik** [comment]
Single shift + right click.
