### ISSUE TITLE
[1.18.2 - Forge 40.2.10 - Carry On 1.17.1.2] Cannot pick up vanilla oak chest.

### ISSUE THREAD

**Issue by Rhyssia** [Tschipp/CarryOn#562]
### Expected Behavior
Ability to pick up vanilla oak chest

### Actual Behavior
Chest opens instead of picking up.

### Steps to Reproduce
Use assigned modifier key and right click on the chest ( Left shift and Left Control tried )

### Version of Minecraft, Carry On, Forge/Fabric
MC - 1.18.2
Forge - 40.2.10
Carry On - carryon-1.18.2-1.17.1.12.jar

### Screenshots encouraged
Not Applicable

### Additional Information
Using a custom mod pack, tried removing mods until it would work, gave up after removing 20-30 mods.

Tried rolling Carry On version back to [carryon-1.18.2-1.17.1.12.jar] seemed to fix the issue and mod working as intended.

Can attach a modlist.html upon request.

**Comment by Rhyssia** [comment]
Related to... #546

**Comment by Amangel0** [comment]
Able to reproduce it on 18.2 using Forge 40.2.10 and Carry On 1.17.12, without any other mod.
It does work properly on any other chest (trapped chest, ender chest, minecart with chest...). Changing the mod version to 1.17.11 fixes the issue completely.
