### ISSUE TITLE
Can't place down Entities

### ISSUE THREAD

**Issue by MLGMagicHoodini** [Tschipp/CarryOn#563]
### Expected Behavior
Be able to right click on the ground and place down any entity that has been picked up

### Actual Behavior
Getting stuck with entity on me (using /carryon Place works)

### Steps to Reproduce
Pick up any, modded, vanilla, anything entity
Attemp to place down
Fail

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1
Forge 47.1.3
CarryOn 2.1.2.5

### Screenshots encouraged

**Comment by Kaiwawa** [comment]
Try try place the mob on another mob's head, works for me. Looks like rats and carry ony are calling the same function, something like that:
![image](https://github.com/Tschipp/CarryOn/assets/50468096/696b832d-7d31-481d-be22-6bb941a60266)

and making this:
![image](https://github.com/Tschipp/CarryOn/assets/50468096/6dcdbfc2-61ac-48c2-9419-2cb0b875261d)
