### ISSUE TITLE
[Bug] Picking up mob while sitting causes the mob to spin around player

### ISSUE THREAD

**Issue by Ricenami** [Tschipp/CarryOn#566]
Not really necessary to fix, but I thought I should let you know:

![image](https://github.com/Tschipp/CarryOn/assets/107516246/e093b6c9-d8d3-4023-a14b-a01fa31383a3)
I can't get a screenshot to show what I'm talking about, but whatever mob I pick up while sitting spins around my player.

Fabric 1.19.2

carryon-fabric-1.19.2-2.1.0.20

**Comment by Ricenami** [comment]
![image](https://github.com/Tschipp/CarryOn/assets/107516246/3c41a2b4-bb33-492b-8a24-dd291a2977ab)

**Comment by Ricenami** [comment]
![image](https://github.com/Tschipp/CarryOn/assets/107516246/33a0e4bb-6fd6-4595-a72f-d1e14b80903b)

**Comment by Ricenami** [comment]
![image](https://github.com/Tschipp/CarryOn/assets/107516246/5c50d692-652e-4310-a22f-38f3e805af2b)

**Comment by Ricenami** [comment]
As soon as I stop sitting the mob stops spinning

**Comment by Tschipp** [comment]
yeah... I haven't quite figured out transformations that work in all cases... I know this is an issue but unsure how to fix it, sorry.
