### ISSUE TITLE
Requires Forge between 46 and 47.1.3, doesn't run on Forge 47.1.79

### ISSUE THREAD

**Issue by NanoAi** [Tschipp/CarryOn#568]
### Expected Behavior
Expecting this to work with Forge 47.1.79, specifically the version that NeoForged reports itself as.
![image](https://github.com/Tschipp/CarryOn/assets/3096584/21c792cb-8378-4221-a4dc-e9a13b37536e)
^ Discord Contact: `paint_ninja` @ <https://discord.gg/neoforged>

There is currently a suggested fix at https://github.com/Tschipp/CarryOn/pull/560#pullrequestreview-1695861397
![(screenshot from the linked page)](https://github.com/Tschipp/CarryOn/assets/3096584/819bcde0-cdbc-4efb-8cd8-29221f5420d9)

### Actual Behavior
The version check fails and my game fails to run.
```
[24/10/2023 16:48:49 p.m.] [main/ERROR] Missing or unsupported mandatory dependencies:	Mod ID: 'forge', Requested by: 'carryon', Expected range: '[46,47.1.3]', Actual version: '47.1.79'
```
![image](https://github.com/Tschipp/CarryOn/assets/3096584/94194271-50f5-490d-a299-8f09b3af4603)

### Steps to Reproduce
Install the current version of NeoForged for 1.20.1, install Carry On, try to launch, it fails.

### Version of Minecraft, Carry On, Forge/Fabric
ATLauncher Version: 3.4.34.2
CarryOn Version: carryon-forge-1.20.1-2.1.2.5
Minecraft Version: 1.20.1
Forge (NeoForged): 47.1.79

**Comment by NanoAi** [comment]
A temporary fix for the above can be done by manually changing the specified line in the Jar file using a program like 7zip.

**Comment by Devilswarchild** [comment]
im also having the same issue, however in my instance the temp fix wont work due to the simple fact im a modpack author and the changes wont apply when I upload the pack. im also using forge 47.2.1

also the devs at neoforge have also stated that its nolonger necessary to stay on 47.1.3 to remain compatible with neoforge. latest recommended version of forge that is compatible with neoforge is 47.2 or newer

**Comment by NanoAi** [comment]
> im also having the same issue, however in my instance the temp fix wont work due to the simple fact im a modpack author and the changes wont apply when I upload the pack. im also using forge 47.2.1
> 
> also the devs at neoforge have also stated that its nolonger necessary to stay on 47.1.3 to remain compatible with neoforge. latest recommended version of forge that is compatible with neoforge is 47.2 or newer

As of posting, for modpacks you have 1 of 3 options.

- Wait for the mod to be updated by the creator.
- Create a script that patches the jar file and add instructions to run it before playing.
- Ask users to edit the jar file themselves after downloading your pack.

**Comment by Devilswarchild** [comment]
and which file inside the jar am I supposed to be editing?

**Comment by Devilswarchild** [comment]
figured it out and tried it, that totally didnt work cause now its just crashing

**Comment by NanoAi** [comment]
> and which file inside the jar am I supposed to be editing?

You need to update the file mentioned in https://github.com/Tschipp/CarryOn/pull/560#pullrequestreview-1695861397 specifically `META-INF/mods.toml`, in the Jar file you can open the Jar file and edit it with 7zip.

I confirmed that it is indeed working on `Minecraft 1.20.1 @ Forge 47.1.79 (NeoForge)`.
