### ISSUE TITLE
Crash on load 1.20.1

### ISSUE THREAD

**Issue by Wolris** [Tschipp/CarryOn#570]
Loading the game with this mod crashes the game.  Revert this mod to previous version prevents this, but retains placement issues.

Minecraft 1.20.1 
Forge 47.2.1
CarryOn 2.1.2.5

Large amount of other mods.  No crash logs, Latest logs contain nothing of note.  Including the log for mod list.
[latest.log](https://github.com/Tschipp/CarryOn/files/13207828/latest.log)

**Comment by Wolris** [comment]
Looks like the problem is that it won't run in Forge 47.2.1

**Comment by NanoAi** [comment]
Yeah it won't run in anything after `47.1.43` see https://github.com/Tschipp/CarryOn/issues/568

Couldn't find anything of note in your crash logs but I noticed that you have Oculus + Embeddium installed. For some reason this crashes your game when there's a Forge version conflict.

Please create an instance with just CarryOn, Oculus, and Embeddium and post the crash logs.

**Comment by Devilswarchild** [comment]
with only those 3 enabled dont even get a crash log. so here's the debug and latest logs.

debug- https://mclo.gs/sHfzuZ7

latest - https://mclo.gs/I9DCdXN
