### ISSUE TITLE
FOV dosnt change view of the picked up block

### ISSUE THREAD

**Issue by Rav115** [Tschipp/CarryOn#574]
### Expected Behavior
Changing FOV should change the size it takes up
or atleast add option in config files so we can change so blocks dont take up almost half the screen

### Actual Behavior
It stays same no matter what

### Version
carryon-fabric-1.20.1-2.1.2.7

FOV 30
![2023-11-22_00 09 16](https://github.com/Tschipp/CarryOn/assets/39887530/894073a9-65ed-4fe4-868c-f6c4fe8f407d)
FOV 110
![2023-11-22_00 09 29](https://github.com/Tschipp/CarryOn/assets/39887530/25ef8b81-59b0-41dc-83d3-dd0ea58b204c)

**Comment by Tschipp** [comment]
This is intended
