### ISSUE TITLE
1.20.4?

### ISSUE THREAD

**Issue by StistkoHraje** [Tschipp/CarryOn#581]
will thare be a version for 1.20.4?

**Comment by Zorklis** [comment]
Yes! We need 1.20.4 support

**Comment by vico93** [comment]
I third that! CarryOn is one of my staple mods!

**Comment by vico93** [comment]
To make this issue more useful to @Tschipp, i decided to try 2.1.2.7 for 1.20.1 in my 1.20.4.

Obviously it crashed, and [here's the crash report](https://gist.github.com/vico93/b14df2c2b59344a2650cb4cf6dc2c7e3). I hope this could give an insight in the update process.

**Comment by vico93** [comment]
@Tschipp any news about it?

**Comment by GoldenFurredFox** [comment]
Also 1.20.2 and 1.20.3 please. XP
