### ISSUE TITLE
Stuck - Can't drop the carried entity

### ISSUE THREAD

**Issue by Narkesha** [Tschipp/CarryOn#582]
### Expected Behavior
To be able to drop the carried entity/block - The carried entity/block is a Cable from Powaah mod

### Steps to Reproduce
Carry a Powaah Cable, you will be stuck with said cable for eternity, haven't figure out how to drop it yet.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft - Medieval Minecraft [Fabric] 1.19.2

**Comment by FRsave** [comment]
Just had the same issue with same mod pack, but on 1.20.1. I was stuck carrying a painting entity. 

**Fix for being stuck**
Remove CarryOn from the mods folder, then launch the game without it. **This will delete the entity/item**, but you'll be free. You can put back CarryOn afterwards and relaunch.

**Comment by Tschipp** [comment]
You can also just run /carryon place or /carryon clear
