### ISSUE TITLE
1.18.2  can't pick up chests

### ISSUE THREAD

**Issue by GameKanna** [Tschipp/CarryOn#583]
### Expected Behavior
Can pick up chests 

### Actual Behavior
Can't pick up chests 

### Version of Minecraft, Carry On, Forge/Fabric
MC 1.18.2, forge 40.2.14

**Comment by DragonSlayer696** [comment]
I am having the same problem as well.

**Comment by Exovi** [comment]
Ditto, same issue - playing FTB Inferno 1.18.2

**Comment by DragonSlayer696** [comment]
I found out at the time of writing this the latest version 1.17.1.12 is the cause rolling back to the previous version 1.17.1.11 fixes the issue. I verified this by removing all other mods i was using and had the same issue until i downgraded

**Comment by Tschipp** [comment]
Oops... I had left debug code in there... fixed in next release.
