### ISSUE TITLE
I picked up a door and now it does'nt leave my hand lol

### ISSUE THREAD

**Issue by Gabitil** [Tschipp/CarryOn#586]
### Expected Behavior
put the door on the ground

### Actual Behavior
the door dont leave my hand

### Steps to Reproduce
Pick up the top of the door or the bottom (don't remember)

### Version of Minecraft, Carry On, Forge/Fabric
Mine 1.20.1, carry on 2.1.2.7, forge 47.2.0

### Screenshots encouraged
![image](https://github.com/Tschipp/CarryOn/assets/61718293/c34333d8-b5cc-4deb-a106-b1d169549834)

I will uninstal and instal the mod so that the entity is deleted

**Comment by Tschipp** [comment]
What mod is that door from?

**Comment by Gabitil** [comment]
Chipped:

![image](https://github.com/Tschipp/CarryOn/assets/61718293/fdccc5d9-bb6b-4567-8da0-ea14cd46315a)
