### ISSUE TITLE
The stonecutter is not taken in hand 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [Tschipp/CarryOn#589]
The stonecutter is not taken in hand
Forge 43.3.5
Minecraft 1.19.2
Carryon-forge-1.19.2-2.1.1.22.jar
![2024-02-04_14 50 37](https://github.com/Tschipp/CarryOn/assets/106809386/9cf09367-ed81-493f-b637-912f9d79c60b)

**Comment by Tschipp** [comment]
You need to enable pickupAllBlocks in the config.
