### ISSUE TITLE
unable to pick up half of a double chest

### ISSUE THREAD

**Issue by Aceplante** [Tschipp/CarryOn#590]
### Expected Behavior
I should be able to

### Actual Behavior
I cannot seem to pick up half of a double chest, and sometimes random other chests too

I also cannot pick up chests when there is a block above them?

### Steps to Reproduce
Place two chests next to each other

### Version of Minecraft, Carry On, Forge/Fabric
Forge 1.18.2
Carry on Forge 1.17.1.12

### Screenshots encouraged
I also cant pick up this:
![this one too](https://github.com/Tschipp/CarryOn/assets/101857505/a1a49299-8203-4753-8648-2b6d8daa6658)

**Comment by Arasarhood** [comment]
Same, same, and same
