### ISSUE TITLE
[Feature Request] To carryon players at 1.18.2

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [Tschipp/CarryOn#595]
### Expected Behavior
Carry a player at 1.18.2 like carryon did at 1.19& higher

Also, i'd like to ask if you can detect Yes Steve Model mod, and automatically disable Carryon's rendering arm setting.   
Duplicated arms rendering :(

**Comment by Tschipp** [comment]
Sorry, won't add new features to 1.18.2
