### ISSUE TITLE
Block Parsing Error. Invalid Name: cheese_mold

### ISSUE THREAD

**Issue by mankra** [Tschipp/CarryOn#60]
### Expected Behavior
No errors in fml-client-latest.log

### Actual Behavior
https://pastebin.com/TEHY1nWv

### Steps to Reproduce
- install Forge
- install Animania
- install Carry On
- start game

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On: 1.7
Animania: 1.4.2
Forge: 14.23.1.2555+

**Comment by PhoenixRiver** [comment]
Just wanted to note that I've noticed the same error on:

Version: CarryOn MC1.12 v1.7.jar
Forge Version: 1.12.2-forge1.12.2-14.23.1.2587

Mod list (though it's probably unnecessary here?)
AIImprovements-1.12-0.0.1b3.jar
animania-1.12.2-1.4.3.jar
AppleCore-mc1.12.2-3.1.0.jar
CarryOn MC1.12 v1.7.jar
Chameleon-1.12-4.1.3.jar
chameleoncreepers-1.4.1-1.12.jar
chickens-6.0.3.jar
CookingForBlockheads_1.12.1-6.3.17.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
DynamicTrees-1.12.2-0.7.2c.jar
Erosion-2.2.1.jar
GiacomosFishingNet-1.12.2-1.6.1.jar
hatchery-1.12.2-2.1.2.jar
Hwyla-1.8.23-B38_1.12.jar
iceandfire-1.3.1-1.12.2.jar
ImmersiveEngineering-0.12-76-core.jar
ImmersiveEngineering-0.12-76.jar
japaricraftmod-1.12-3.6.0.jar
jehc-1.12-1.3.1.jar
jei_1.12.2-4.8.5.132.jar
jeiintegration_1.12.2-1.5.1.36.jar
journeymap-1.12.2-5.5.2.jar
llibrary-1.7.9-1.12.jar
Mantle-1.12-1.3.1.21.jar
morechickens-1.12.2-3.0.0.jar
natura-1.12.2-4.3.2.42.jar
OptiFine_1.12.2_HD_U_C8.jar
Owls-1.12.2-1.0.1.jar
Pam's HarvestCraft 1.12.2f.jar
simplytea-1.4.jar
SpiceOfLife-mc1.12-1.3.11.jar
StorageDrawers-1.12.1-5.3.3.jar
Waddles-1.12.2-0.5.6.jar
WailaHarvestability-mc1.12-1.1.12.jar

Hope this helps.

**Comment by Tschipp** [comment]
Yep - I apparently can't even write configs properly

**Comment by PhoenixRiver** [comment]
At least it's an easy fix if it's just configs! :) - I could have
given you a fix if I knew what the correct name should have been!
Thank you :)
