### ISSUE TITLE
Cant pick up block

### ISSUE THREAD

**Issue by ProGmr1337** [Tschipp/CarryOn#601]
### Actual Behavior
I might be dumb and it might not be a tile entity, but when playing with AE2, I cant pick up budding certus quartz blocks (i tried enabling in the config, pick up all blocks, still no. I am also playing on a server)

### Expected Behavior
To pick up the budding certus quartz

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1, 2.1.2.7, Forge

### Screenshots encouraged
Before Right click:
![2024-03-02_19 34 51](https://github.com/Tschipp/CarryOn/assets/100386776/60672d78-d189-4817-ae13-5f7ebefb59aa)
After Right click:
![2024-03-02_19 34 52](https://github.com/Tschipp/CarryOn/assets/100386776/a13e3b7e-ed96-4a52-b81b-b3ecd3e47e5f)

**Comment by Tschipp** [comment]
I think all of ae2 might be on the blacklist

**Comment by ProGmr1337** [comment]
No, i can pickup growth accelerators and fluix cables

**Comment by ProGmr1337** [comment]
Update: doesn't work in single player either

**Comment by ProGmr1337** [comment]
Another update: Checked in another world, not the same cause it has different mods, it worked, there's just a mod in my modpack counteracting the picking up of budding certus quartz
