### ISSUE TITLE
Carryon dupes with powah cables

### ISSUE THREAD

**Issue by Wyrena** [Tschipp/CarryOn#605]
### Expected Behavior
Pick up and place a powah energy cable

### Actual Behavior
Picks up the cable, everytime you try to place said cable it dupes in your hand leaving a blank slot with the item and unable to place down item, leaving you infinetly placing the same cable. dying and trying to respawn makes your character unable to respawn cause its holding the item in hand.
Character is now hardlocked in a state of unable to respawn, making the world no longer playable.
### Steps to Reproduce
use carry on mod with powah energy cables.

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 MC
47.1.99 Forge
2.1.2.7 Carry on
### Screenshots encouraged
![cable1](https://github.com/Tschipp/CarryOn/assets/163410149/bb53f6f2-4910-4e0c-846f-19fee4f1239c)
![cable2](https://github.com/Tschipp/CarryOn/assets/163410149/2bb4f34e-aee0-4d67-9012-fdaee17fd341)

**Comment by Silsas0987** [comment]
got the same issue with a alchemist cauldron from irons spells and spellbooks mod

**Comment by Tschipp** [comment]
please reset your config, powah should be on the default blacklist
