### ISSUE TITLE
Crash Dupe

### ISSUE THREAD

**Issue by HorizonsMC** [Tschipp/CarryOn#61]
If you pickup an item and immediately crash the client it allows you to dupe entitys.

This was found with a crash that has been fixed in dev from Buildcraft: https://github.com/BuildCraft/BuildCraft/issues/3877

### Steps to Reproduce
1. Pickup item and immediately crash the client.
2. When you log back in you will have the entity in your hands and a copy where you picked it up

### Version of Minecraft, Carry On, Forge
1.12.2
CarryOn MC1.12 v1.7
Forge 14.23.1.2559

**Comment by Tschipp** [comment]
Interesting... So from what I've read from Buildcraft, is this even still an issue or has the whole thing already been fixed on their side? 
Also what exactly are you picking up? An Entity or a TileEntity (Block)? And from what mod?

**Comment by Tschipp** [comment]
Also, I think this might be an Issue with vanilla MC. The world gets saved after the player data does, so it's possible that items can be duplicated.
