### ISSUE TITLE
Supplementaries Urn Dupe when placed midair with Carryon

### ISSUE THREAD

**Issue by MCXPStudios** [Tschipp/CarryOn#612]
(This was mentioned on the Supplementaries repo, but they said it was most likely a problem with Carryon, so I'm bringing it up here.)

### Expected Behavior
Placing the urn should either shouldn't remain in hand when placed, or should have an error saying that it cannot be placed midair.

### Actual Behavior
The Urn remains in-hand and places to fall, dropping whatever loot comes from them infinitely, until the urn is placed directly on the ground.

### Steps to Reproduce
-Run a modpack that combines Carry on, and Supplementaries
-Open a world (This bug was found in survival, but most likely works in creative too.)
-Go underground and locate any Supplementary Urn
-Pick it up, then find a wall
-Attempt to place the urn on the wall 3+ blocks up
-The Urn will remain carried, and place and fall, and after one will shatter on the first duped urn, fountaining out loot and mobs  

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft: 1.20.1
Carry on: 1.20.1-2.1.2.7
Forge: 47.2.0

### Screenshots encouraged
![image](https://github.com/Tschipp/CarryOn/assets/55472940/865df4cb-c74e-48c8-ba0d-08f38b59e24c)

**Comment by Tschipp** [comment]
the urn gets placed just fine for me... do you have anything weird in the log?
