### ISSUE TITLE
[Forge 1.20.1] Tab-based blacklist doesn't work

### ISSUE THREAD

**Issue by lcy0x1** [Tschipp/CarryOn#617]
### Expected Behavior
Blocks blacklisted by `carryon:block_blacklist` will not be able to be picked up.

### Actual Behavior
The block can still be picked up

### Steps to Reproduce
Add any tiles in the tag, start game, try to pick it up

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.20.1
Forge 47.1.3
Carry On 2.1.2.7

### Problem
`blocktag` is always empty in line 
https://github.com/Tschipp/CarryOn/blob/75ca33bb8de8f3a825affc40877aff4666f0ed63/Common/src/main/java/tschipp/carryon/common/config/ListHandler.java#L127
Because it's called before tags are loaded.

**Comment by Tschipp** [comment]
This is fixed in more recent versions of 1.20
