### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#620]
I'm not opening this as a "please do this urgently" type of thing, instead just as a way to mark it's not compatible yet.

**Comment by vico93** [comment]
@Tschipp any updates about it?

**Comment by rasosha** [comment]
![tenor 1](https://github.com/Tschipp/CarryOn/assets/50449824/b4e27be7-7e09-451d-837c-ce7ae69fe782)

**Comment by Zorklis** [comment]
Yeah I hope for update to 1.20.6 too.

**Comment by vico93** [comment]
I think in this pace a straight port to one of the 1.21 pre releases would be smarter to do (update once instead of twice in a short timeframe), since the full release is dropping last week anyway...

**Comment by vico93** [comment]
Since 1.21 is going to be dropped in next Thursday, i hope we will see an update straight to that version instead, since 1.20.6 date passed by.

**Comment by Zorklis** [comment]
I hope 1.21 support comes out

**Comment by xihui520** [comment]
I hope 1.21 support will soon come out

**Comment by vico93** [comment]
Last Tschipp comment about the update process (things like the new component system are being obstacles to the update):
![image](https://github.com/Tschipp/CarryOn/assets/3485505/893fd35d-b022-41fb-abaf-066fd2cd1a6e)

**Comment by SunGod** [comment]
vico93 thanks for providing the update.

**Comment by Bendycrate** [comment]
hoping for a 1.21 port, i dont know anything about modding but im sure its more difficult than what appears on the surface

**Comment by vico93** [comment]
![image](https://github.com/user-attachments/assets/eb731dab-dc31-40a4-ac25-7df63bb8385c)

THANK YOU SO MUCH TSCHIPP!
