### ISSUE TITLE
Simple Pipes/ carry on mod incompatibility

### ISSUE THREAD

**Issue by Hiratlas** [Tschipp/CarryOn#621]
### Expected Behavior

Shift right clicking on a block or cover in the Simple BC pipes should not pick the item up, as it should be identified as a block

### Actual Behavior

f you pick up any of the pipes or covers using the carry on mod, the item will vanish from inventory. It cannot be placed or seen, and you cannot scroll as if holding an item. only way to fix is to die (whiping inventory will not fix it, ive tried)

### Steps to Reproduce

1) install any version of Carryon, Simple BC pipes, and dark utilities (as dark utils is a needed dependency of Simple pipes)

2) place any pipe or pipe cover from Simple pipe test in the mod (AKA simple pipes)

3) shift right click on the pipe or pipe cover.

### Version of Minecraft, Carry On, Forge/Fabric

Any (seen and replicated in 1.20.1 mc, 2.1.2.7 carryon, 0.11.0 Simple BC pipes)

**Comment by Kneelawk** [comment]
One thing to note is that all multi-part blocks, such as pipes or facades, are block entities which means that CarryOn can carry them.

Now why they glitch out when picked up? I have no idea. Multi-parts aren't particularly special as far as block entities go. They do rely on fabric custom level data to render properly. However, placing *should* work.

Also, here is a link to the SimplePipes issue to make navigation easier: https://github.com/AlexIIL/SimplePipes/issues/70

**Comment by Kneelawk** [comment]
Also, side note: Dark Utils should not be needed by SimplePipes, though I doubt that's what's causing this issue.

**Comment by TED-inc** [comment]
You can add "libmultipart:*", to blacklist forbiddenTiles, as temporary fix
