### ISSUE TITLE
Lootr Compat

### ISSUE THREAD

**Issue by SafeOfArsenal** [Tschipp/CarryOn#622]
### Expected Behavior
The chest stays blue when picking it up

### Actual Behavior
the chest goes back to being yellow (pre-looted) when picked up but it does go back to being blue when placed down

### Steps to Reproduce
Pick up a lootr chest with carry on

### Version of Minecraft, Carry On, Forge/Fabric
1.19.2 Forge 43.3.13, Carry on Version is 2.1.2.23

### Screenshots encouraged
![2024-05-03_21 21 01](https://github.com/Tschipp/CarryOn/assets/66153781/c4204300-153d-4a25-b0aa-5d66293320ad)
![2024-05-03_21 21 03](https://github.com/Tschipp/CarryOn/assets/66153781/c8b0cf9c-650e-4e97-ad88-2191833ec255)

**Comment by Tschipp** [comment]
lootr has special rendering, carry on can't capture that. Since this is only visual tho, I'm closing this.
