### ISSUE TITLE
Crash with essential mod 1.20.1

### ISSUE THREAD

**Issue by JaxX27** [Tschipp/CarryOn#627]
Ass the essential mod creates a new instalation for minecraft 1.20.1 (forge 47.1.29) I just cant use this mod as this version of forge isnt supported by your mod.  Any ideas?

Failure message: Mod carryon requires forge between 46 and 47.1.3 (inclusive), 47.1.43 or above
		Currently, forge is 47.1.29
	Mod Version: 2.1.2.7

**Comment by Tschipp** [comment]
update forge
