### ISSUE TITLE
arms invisible 1.17

### ISSUE THREAD

**Issue by Aceplante** [Tschipp/CarryOn#628]
### Expected Behavior
They should not be. I should see the item I'm carrying.

### Actual Behavior
I cannot. I also noticed the texture of the armor I was wearing continued down the arms as it would if I was not carrying anything. This is vanilla iron armor, simply with a texture pack.

### Steps to Reproduce
Carry something. Perhaps this is due to better first person?

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.17.1, forge 37.1.1, carry on 1.16.0.6

### Screenshots encouraged
![2024-05-19_16 01 31](https://github.com/Tschipp/CarryOn/assets/101857505/55e0c648-b79e-4638-b59d-2281e18df618)

**Comment by Tschipp** [comment]
not gonna work on 1.17 anymore, sorry
