### ISSUE TITLE
Ad Astra steel cables get duplicated when carried

### ISSUE THREAD

**Issue by dendo1234** [Tschipp/CarryOn#633]
### Expected Behavior
Carrying ad astra steel cables should work. Shouldn't be possible to place the cables on already occupied blocks.

### Actual Behavior
Trying to place the carried cable on the ground duplicates it. It's impossible to get rid of the carried cable without commands. Depending on the way the cable is placed, a block can be deleted.  

### Steps to Reproduce
1- Pick up an ad astra steel cable 
2- Try to place it on the ground (duplicates it)
3- Place the cable in a block that is already occupied (deletes the block)

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.20.1
Carry On 2.1.2.7
Fabric 0.15.11
Ad Astra 1.15.18

### Screenshots encouraged

https://github.com/Tschipp/CarryOn/assets/37016869/02781233-6300-4f0a-8fd5-2191879a2a09

**Comment by Tschipp** [comment]
can't recerate, places just fine for me

**Comment by dendo1234** [comment]
Well, that is weird. I did some more testing and found out that the bug got introduced in Ad Astra version 1.15.7 since the previous version, 1.15.5, works without any problems. During my testing, I also found that the bug affects the forge versions as well. I guess this is a Ad Astra issue?

**Comment by Tschipp** [comment]
I'm unsure, but if it changes based on the ad astra version, I would say yes.

**Comment by Peperehobbits01** [comment]
On 1.15.18 of Ad Astra whit latest of Carry on it works

**Comment by Peperehobbits01** [comment]
And it's whit all cables, at least desh cables to
