### ISSUE TITLE
Crash when attempting to carry a Daylight Sensor, opening the same world after results in crash

### ISSUE THREAD

**Issue by HarumiAme** [Tschipp/CarryOn#64]
### Expected Behavior
To be able to carry the daylight sensor

### Actual Behavior
Game saved and crashed to desktop. After this, attempting to open the same world results on the game crashing. 

### Steps to Reproduce
1) Place daylight sensor.
2) Set it to give output at night.
3) Attempt to carry it.
4) Crash to desktop.
5) Open the game again.
6) Open the same world again.
7) Crash to desktop.
Additional notes:
Carrying the daylight sensor on it's first configuration (to give output at daylight) works as expected. 
Deleting the mod and opening the world where the crash occurred results in the sensor disappearing.

### Version of Minecraft, Carry On, Forge
Minecraft 1.10.2
Carry On: CarryOn MC1.10.2 v1.7
Forge: forge1.10.2-12.18.3.2185

Crash log with other mods: https://pastebin.com/MwJ2yHmz
Crash log with only Carry on: https://pastebin.com/LqhJ6FHU

**Comment by Tschipp** [comment]
This is probably a 1.10 issue, I'll look into it.
