### ISSUE TITLE
changes to config not registering with bean's backpacks

### ISSUE THREAD

**Issue by VEGAT0N** [Tschipp/CarryOn#644]
### Expected Behavior

Upon entering "beansbackpacks:*" into the config file, saving and loading into my world, I should NOT be able to pick up any backpacks from Bean's Backpacks using Carry On's functionality.

### Actual Behavior
The config change does not stick and the backpack is picked up. This is a problem as Bean's is one of the good backpacks mods where you can place and pick up backpacks to and from the world using the same keybind as Carry On. A temporary workaround called changing the keybind has been used for now. 

### Steps to Reproduce

1. See that the two mods are clashing
2. Enter "beansbackpacks:*", into the blacklist section in the config file
3. Attempt to put the backpack on your back

### Version of Minecraft, Carry On, Forge/Fabric

Minecraft: 1.20.1
Carry On: 2.1.2.7
Forge: 47.3.0

### Screenshots encouraged

![notepad_KUWr5eIQjJ](https://github.com/Tschipp/CarryOn/assets/57297667/c38e8f3f-814d-4c20-85ef-4399b827da84)

Might I mention that I had also put the config file in the world's config folder, which didn't work, sadly. I also did per-item specifications in the blacklist, which was unfortunately fruitless.

**Comment by Tschipp** [comment]
Are you sure you got the name of the block correct? When you hover over it placed in the world when F3 is active, you should see the full id of it.

**Comment by VEGAT0N** [comment]
Hello Tschipp! 

After much research, turns out the dev for bean's backpacks has implemented the version of the backpack that sits in the world as an **entity**, how wild is that? Now fixed using the correct blacklist after using /summon to figure out the entity name.

Thank you so much for your help and amazing mod, keep on keeping on!

**Comment by VEGAT0N** [comment]
Hi, 

Unfortunately I got carried away by the fact that it didn't pick up the backpack. 

Does the mod interact at all with the entity even if it's told not to? It seems to be stopping the backpack mod from picking up the backpack, though this could be some funk with the backpack mod itself.

Thanks!
