### ISSUE TITLE
Sophisticated Storage loosing items from double chest

### ISSUE THREAD

**Issue by l0py2** [Tschipp/CarryOn#646]
### Expected Behavior

- Pick up the first part of an upgraded double chest and place it
- The second part should remain with half of the items

### Actual Behavior

- Pick up the first part of an upgraded double chest and place it
- The second part looses all the items

### Steps to Reproduce

- Pick up the first part of an upgraded double chest and place it
- Place it
- Pick up again
- Place it

### Version of Minecraft, Carry On, Forge/Fabric

- Minecraft 1.20.1
- Forge 47.3.0
- Carry On 2.1.2.7
- Sophisticated Core 0.6.22.611
- Sophisticated Storage 0.10.25.804

### Screenshots encouraged

Fist state of an upgraded double chest:
![Fist state of an upgraded double chest](https://github.com/Tschipp/CarryOn/assets/81564961/35111373-ba62-48da-90ab-287e5de58363)

State of the first part of an upgraded double chest after picking it up one time:
![State of the first part of an double chest after picking it up one time](https://github.com/Tschipp/CarryOn/assets/81564961/28f13f46-794b-42d4-82f1-4ca7545fb3fc)

State of the first part of an upgraded double chest after picking it up two times:
![State of the first part of an upgraded double chest after picking it up two times](https://github.com/Tschipp/CarryOn/assets/81564961/cdb8cef1-e46c-4630-b7f6-c994b01d7999)

State of the second part of an upgraded double chest after picking up the first part multiple times:
![State of the second part of an upgraded double chest after picking the first part multiple times](https://github.com/Tschipp/CarryOn/assets/81564961/0248746f-b688-408a-9d0c-7684bf3e558f)

Example video:

https://github.com/Tschipp/CarryOn/assets/81564961/a92211c7-6105-4c8f-8294-1ea7b0de9994

[Example video in YouTube with better resolution](https://www.youtube.com/watch?v=fQbwWxyywRg)

**Comment by l0py2** [comment]
I can report the issue to Sophisticated Storage too if needed

**Comment by Tschipp** [comment]
I am not sure why sophisticated storage is handling chests in a different way than vanilla does it... I'm just gonna blacklist
