### ISSUE TITLE
Crash when carrying block carved with mod "literal ascension"

### ISSUE THREAD

**Issue by HarumiAme** [Tschipp/CarryOn#65]
### Expected Behavior
To be able to carry a carved block

### Actual Behavior
Game saves and crashes to desktop. Attempting to load same world again results in another crash.  

### Steps to Reproduce
1) Carve a block using the carving tool from literal ascension.
2) Try to carry it.
3) Crash to desktop.

### Version of Minecraft, Carry On, Forge
Minecraft 1.10.2
Carry On: CarryOn MC1.10.2 v1.7
Forge: 1.10.2 - 12.18.3.2511

**Comment by Tschipp** [comment]
Most likely linked to #64 and also fixed now.
