### ISSUE TITLE
[1.21] [Neoforge] Freezes the game on launch

### ISSUE THREAD

**Issue by ffuentesm** [Tschipp/CarryOn#653]
### Expected Behavior
The game should launch or crash

### Actual Behavior
IT freezes on the loading screen

### Steps to Reproduce
Launch game with 

### Version of Minecraft, Carry On, Forge/Fabric
carryon-neoforge-1.21-2.2.0.jar
neoforge 21.0.95

### Screenshots encouraged
Log: https://pastebin.com/yZiqtnAV

**Comment by Leiriad** [comment]
Same issue with same Neoforge and Carry On version

**Comment by Tschipp** [comment]
fixed

**Comment by xbox0** [comment]
this happens when im on 1.20.6

**Comment by xbox0** [comment]
it stays on the loading screen, everything is functional, but i cant see anything
