### ISSUE TITLE
on aternos server carryon:sync_scripts

### ISSUE THREAD

**Issue by leventbaris3535** [Tschipp/CarryOn#654]
### Expected Behavior
login to server

### Actual Behavior
i cant enter the server

### Steps to Reproduce
download carry on mod to aternos server

### Version of Minecraft, Carry On, Forge/Fabric
fabric

### Screenshots encouraged
![WhatsApp Görsel 2024-07-16 saat 14 17 38_12b0f5b7](https://github.com/user-attachments/assets/53d84a98-a0fd-4865-a50e-f4aa302f375b)

**Comment by vico93** [comment]
Got the same issue here, to expand the information, here's the lines that appeared on both my client and server `latest.log`s:
https://gist.github.com/vico93/e7ddc54230c94a8fad1cdac4c62e671c

@Tschipp

**Comment by papercut-real** [comment]
This is an issue on all servers. Same exact error, and the only mod causing an error out of 100 other mods being used. Not sure if isolated to fabric 1.21, but it definitely causes errors and might have something to do with it's config file.

**Comment by kalevaz** [comment]
hi, i have the exact same problem on a personal fabric server i host

**Comment by Vrylex** [comment]
same goes for me

**Comment by JonasBlank** [comment]
fixed in next release on 1.21

**Comment by Tschipp** [comment]
fixed on next 1.21 release
