### ISSUE TITLE
[1.21 - 2.2.0] Error Loading mod with NeoForge

### ISSUE THREAD

**Issue by ms-daniel** [Tschipp/CarryOn#655]
### Expected Behavior
Game Menu

### Actual Behavior
Error loading mod

### Steps to Reproduce
Just launch the game with NEOFORGE 1.21 v82 beta (i tried with v98 too)

### Version of Minecraft, Carry On, Forge/Fabric
M -v: 1.21
Mod -v: 2.2.0
NeoForge -v: v82-98

### Screenshots encouraged
![image](https://github.com/user-attachments/assets/06ebeb5a-f577-4853-8380-26c26a8cd486)

**Comment by Periam** [comment]
I have the same exact issue.

![Screenshot 2024-07-17 121604](https://github.com/user-attachments/assets/f13d6fef-3dad-428a-94e2-27475d4d7e8d)

**Comment by Tschipp** [comment]
fixed in next release
