### ISSUE TITLE
duplication glitch with farmers delight cutting board

### ISSUE THREAD

**Issue by LiamHaste** [Tschipp/CarryOn#657]
### Expected Behavior
no duplication

### Actual Behavior
duplication of item on cutting board
( i just blacklisted the cutting board and it fixes it, so you guys should probably just make it blacklisted always)

### Steps to Reproduce
pick up cutting board with carry on

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 forge

**Comment by mayornii** [comment]
ghost item, not a dupe !!
