### ISSUE TITLE
Interaction entities are not forbidden, breaking data packs

### ISSUE THREAD

**Issue by GrantGryczan** [Tschipp/CarryOn#659]
### Expected Behavior
Interaction entities should not be movable by players, as they are technical entities used by data packs to detect interactions in certain volumes. In fact, Carry On overriding their crouch + right-click behavior voids any crouch + right-click behavior implemented by the data pack that manages the interaction entity.

### Actual Behavior
Interaction entities can be carried by players by default, causing data packs using them to break.

### Steps to Reproduce
Enter `/summon minecraft:interaction`. With the mod installed, crouch and right-click on the entity hitbox created by the command. (If you don't know where it is, you can see it by pressing F3+B.)

### Version of Minecraft, Carry On, Forge/Fabric
This applies to all versions of Carry On where interaction entities exist: Minecraft 1.19.4 and up (Forge and Fabric).

**Comment by Arschpirat** [comment]
GrantGryczan saved my life

**Comment by Tschipp** [comment]
Good point, thank you. I am not 100% up to date with the latest datapack methods so I didn't even know that entity existed. In the same spirit, display entities should probably also not be moveable.

**Comment by GrantGryczan** [comment]
Is it possible this could be patched for older versions as well? The issue occurs in 1.19.4+, and every week we receive new reports from users of our Graves data pack ([Vanilla Tweaks](https://vanillatweaks.net/)) that they can't open their grave to retrieve their items anymore because they accidentally shift+clicked it. Then we have to explain how they can use commands to fix the broken grave entity and get their items back, and how they need to add `minecraft:interaction` to their Carry On config. This is very time-consuming, and I don't foresee people leaving these old versions for a very long time. Given the fix is just a tiny configuration change, I don't think it would be impractical to simply apply that change to older versions as well.

**Comment by GrantGryczan** [comment]
@Tschipp Just had another user report to us that they won't be using our data packs anymore because of this bug. Would you consider my above request? I would really appreciate it.
