### ISSUE TITLE
Signs should render when being carried

### ISSUE THREAD

**Issue by ZoidBB** [Tschipp/CarryOn#66]
### Expected Behavior
Signs should render when being carried

### Actual Behavior
Local view shows weird wooden block, view from other users on server shows air.

### Steps to Reproduce
Pick up a sign

### Version of Minecraft, Carry On, Forge
1.12.2, 1.7, 14.23.1.2555

### Screenshots encouraged
Later maybe, debugging a modpack

**Comment by capnkirok** [comment]
I don't believe this is possible without a complicated custom render.

**Comment by Tschipp** [comment]
Yep, what @capnkirok said.
