### ISSUE TITLE
Sophisticated Storage Compatibility issue

### ISSUE THREAD

**Issue by LioxAcc** [Tschipp/CarryOn#661]
### Expected Behavior

When holding chests, the contents inside should not fall out.
When repositioned on the floor they should be usable
And should be able to be placed next to another chest to make a double chest.

### Actual Behavior

When holding the chests all their contents fall out
When put back on the floor they are not usable (at least not at the first try)
And cannot be placed next to another chest to make a double chest.

### Steps to Reproduce

https://imgur.com/ktrfk8G

### Version of Minecraft, Carry On, Forge/Fabric

Minecraft 1.20.1
Forge 1.20.1 - 47.3.5

sophisticatedcore-1.20.1-0.6.22.611
sophisticatedstorage-1.20.1-0.10.25.804
carryon-forge-1.20.1-2.1.2.7

(All mods are in their latest version)

**Comment by SRHTNIN** [comment]
Could you please fix this issue in 1.20.1? The latest Carryon version for 1.20.1 was released back in 2023.. Meaning that this issue still exists in 1.20.1.

![image_2025-01-11_180531193](https://github.com/user-attachments/assets/213a2d89-2d5d-44f4-b1a6-9176116b5674)

Also, let me know if you can fix this, or if I'm being stupid and forgetting some other factor. Thank you in advance!

**Comment by CynSolveroftheAbsolute** [comment]
@Sarah2nin it's just a config to blacklist sophisticated storage chests in carryon-common.toml, just copy the blacklist from the updated version to the 1.20.1 version and it should work just fine
