### ISSUE TITLE
Picking up Mo' Creatures: Extended entities causes game crash

### ISSUE THREAD

**Issue by Omegapsychosis** [Tschipp/CarryOn#664]
### Expected Behavior

Shift+Right clicking a Mo' Creatures: Extended mob should pick it up.

### Actual Behavior

Shift+Right clicking a Mo' Creatures: Extended mob crashes the game with the error "Failed to load entity NBT" and the server cannot be rejoined again by that player until Carry On is removed from the mod list of both server and client.

### Steps to Reproduce

  1. Install Carry On and Mo' Creatures Extended
  2. Shift+Right click on a Mo' Creatures Extended mob

### Version of Minecraft, Carry On, Forge/Fabric

Minecraft: 1.12.2
Carry On: 1.12.7.23
Forge: 14.23.5.2860

I hate to drum up an old issue, especially on an obsolete MC version, but the same issue occurs with the remake Mo'Creatures: Extended for 1.12.2 that was occurring with the original mod and was fixed here...

[Picking up Mo' Creatures entities causes game crash #229
](https://github.com/Tschipp/CarryOn/issues/229) 

I know getting an update would be a lot to ask but if you are still working on older versions this would be great.

**Comment by Tschipp** [comment]
That mod should be on the blacklist, you can do that by adding "mocreatures:*" (I think).

**Comment by Tschipp** [comment]
I see, since the modid hasn't changed, adding "mocreatures:*" to the blacklist should do the trick
