### ISSUE TITLE
Dupe bug with Functional Storage (also reported to Functional Storage)

### ISSUE THREAD

**Issue by Penrosian** [Tschipp/CarryOn#668]
### Expected Behavior
Cabinet will de-link from controller or the controller will pull from the moved cabinet.

### Actual Behavior
Cabinet moves while link remains linked to nothing, allowing items to be pulled from the controller without decreasing the number in the actual cabinet

### Steps to Reproduce
Place down a storage controller and a cabinet of any type
Link the cabinet to the storage controller
Use carry on to move the cabinet
Pull items out of the controller with hoppers/item cables/etc.

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.19.2, Carry On 2.1.2.23, Functional Storage 1.1.10, Forge 43.3.9

### Screenshots encouraged
https://youtu.be/K83Hsuzq2Jo video of dupe

**Comment by Penrosian** [comment]
To quote @richie3366 on discord:

"The issue is occurring most likely because Carry On removes the BlockEntity first, [here](https://github.com/Tschipp/CarryOn/blob/1.21/Common/src/main/java/tschipp/carryon/common/carry/PickupHandler.java#L141), before removing the block in the next line of code.

And the problem is: since Functional Storage uses an intermediary class to improve performance (by not accessing/checking block entities every time an item has to be added/removed), it doesn't know the tile entity has been removed because it relies on Block.onRemove and [checks for BlockEntity inside](https://github.com/Buuz135/FunctionalStorage/blob/1.19/src/main/java/com/buuz135/functionalstorage/block/DrawerBlock.java#L332), but at the time the method is called, it's already too late: the tile entity was removed just earlier.

In 1.20 / 1.21 versions of Functional Storage, it stills does the same thing but in another class (Drawer instead of DrawerBlock), but [it behaves the same way whatsoever](https://github.com/Buuz135/FunctionalStorage/blob/1.21/src/main/java/com/buuz135/functionalstorage/block/Drawer.java#L255).

I wouldn't know for sure which mod is "misbehaving" since Carry On is one mod of its kind, but I'd be more inclined to suggest Functional Storage to also handle removal inside the BlockEntity.setRemoved method by overriding it in their extending class(es). It's the best way to fix the issue once & for all.
I think Carry On couldn't have done a better job than what they did, but that's my non-expert opinion."

**Comment by Penrosian** [comment]
Another quote from the same guy: Although! Now that I look at the MC code, it seems that calling level.removeBlock subsequently calls level.removeBlockEntity inside the  BlockBehavior.onRemove code (note: Block extends BlockBehavior) shown in the joined screenshot. That means Carry On could remove [this line](https://github.com/Tschipp/CarryOn/blob/1.21/Common/src/main/java/tschipp/carryon/common/carry/PickupHandler.java#L141) without any side-effect (that I know of), and that would solve the dupe issue as well. It would also possibly solve other related issues with other mods relying only on Block.onRemove to detect & handle block/tile removal.

**Comment by Tschipp** [comment]
> it seems that calling level.removeBlock subsequently calls level.removeBlockEntity inside the BlockBehavior.onRemove code

Sadly, that's not universally true. For example, removing the line as you show makes it so that container blocks (like chests) spill all their items into the world.
This would undoubtedly be the case for many more modded entities. Removing the Tile Entity is a bad solution, but the best one if I need to prevent the regular "block broken" code to be called.
So it's not the fault of Functional Storage inherently, as this is unexpected behavior that Carry On is doing. 
The right approach would be for Carry On to blacklist Functional Storage blocks. Ideally, Functional Storage can add all their critical blocks to the common tag `c:relocation_not_supported`, which indicates that the block cannot be moved. Carry On respects this tag and will deny the pickup.
