### ISSUE TITLE
 Players pick up the bug of 'Alchemist Cauldron'

### ISSUE THREAD

**Issue by 1-weibai-1** [Tschipp/CarryOn#674]
### [CarryOn](https://github.com/Tschipp/CarryOn) and [irons-spells-n-spellbooks](https://modrinth.com/mod/irons-spells-n-spellbooks) players pick up the bug of 'Alchemist Cauldron'
**Game version** : Minecraft Forge 1.20.1
### Problem
The 'Alchemist Cauldron' held by the player can allow the player to place unlimited 'Alchemist Cauldron' on the ground, but the' Alchemist Cauldron 'held by the player cannot be cleared, only death can solve it.
### Screenshot
![b8b087d4e88468b78e78237985d374b7](https://github.com/user-attachments/assets/fdd4c94e-06e3-4bb5-934a-c18137fe9034)

**Comment by flinglo** [comment]
Having a similar issue, picked up the Alchemist Cauldron accidentally, and ended up placing a few accidentally. Since an item is being carried, you can't open your inventory or switch hotbar slots. Also, in my case, relogging and dying repeatedly did nothing to solve the issue.
