### ISSUE TITLE
Cant pick up camel

### ISSUE THREAD

**Issue by Plasman888** [Tschipp/CarryOn#679]
### Expected Behavior

Pick up camel
### Actual Behavior

opens camels inventory
### Steps to Reproduce
try to pick up camel

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1, Carry On 2.1.2.7, Fabric 0.16.2

**Comment by Tschipp** [comment]
The camel is likely too big, so you can edit the default config values.
