### ISSUE TITLE
Stairs are being placed in the wrong orientation

### ISSUE THREAD

**Issue by stefan7080** [Tschipp/CarryOn#68]
### Expected Behavior
Lowered part of stair is being placed towards the player.

### Actual Behavior
Opposite side of the stair faces the player.

### Steps to Reproduce
- Shift + Right-Click on any stair
- Right-Click on a block to place stair

### Version of Minecraft, Carry On, Forge
MC: 1.12.2
Forge: 14.23.1.2564
Carry On: 1.7

### Screenshots encouraged
![2018-01-02_17 44 16](https://user-images.githubusercontent.com/23392891/34491664-954b36bc-efe4-11e7-948a-be9cc9e7c658.png)
![2018-01-02_17 43 21](https://user-images.githubusercontent.com/23392891/34491666-9707fabc-efe4-11e7-88c5-40aa270515b1.png)
![2018-01-02_17 43 31](https://user-images.githubusercontent.com/23392891/34491671-9a03b33c-efe4-11e7-82cb-9a15c1908c12.png)

**Comment by Tschipp** [comment]
Yep.. I've noticed that too, I think I'm gonna write an exception for the staris
