### ISSUE TITLE
I can't carry things. Probably a mod but I don't know which one.

### ISSUE THREAD

**Issue by CryoNine** [Tschipp/CarryOn#686]
### Expected Behavior
To pick things up with crouch and right click

### Actual Behavior
Doing so just opens the chest/shulker/crafting table

### Steps to Reproduce
Crouch, right click, opens chest
### Version of Minecraft, Carry On, Forge/Fabric
Fabric 1.19.4

### Screenshots encouraged
My list of mods:

![Screenshot 2024-09-15 170138](https://github.com/user
![Screenshot 2024-09-15 165907](https://github.com/user
![Screenshot 2024-09-15 165815](https://github.com/user-attachments/assets/903259f1-1f68-4f38-bccc-e6681417370d)
-attachments/assets/c4a97d92-95cd-464f-a114-aa6ce61133f6)
### Screenshots encouraged
![Screenshot 2024-09-15 165950](https://github.com/us
![Screenshot 2024-09-15 165921](https://github.com/user-attachments/assets/27f36381-7714-41c2-8da8-1ebe448b07cf)
er
![Screenshot 2024-09-15 165938](https://github.com/user-attachments/assets/dc9fe592-1a4f-424e-87a8-2ad1111a5c63)
-attachments/assets/07686ddd-ae90-4ab6-b5c1-34b251188c31)
-attachments/assets/dd85400e-07fd-4a79-a9dd-afd6d7d31
![Screenshot 2024-09-15 170051](https://github.com/user
![Screenshot 2024-09-15 170007](https://github.com/user-attachments/assets/ff9b9add-813d-4634-83b3-6ceccbd67a65)
### Screenshots encouraged
![Screenshot 2024-09-15 170020](https://github.com/user-attachments/assets/9c1643e4-e5f5-4f85-94c1-9a299e735981)
-attachments/assets/b7a608a1-fdc7-4723-a8dd-1
![Screenshot 2024-09-15 170040](https://github.com/user-attachments/assets/be57a04f-75a0-4453-8f33-9c9fd8de517e)
f826adcf89d)
825)

### Screenshots encouraged
![Screenshot 2024-09-15 170111](https://github.com/user-attachments/assets/cb665ea1-afef-4abe-ab48-5fbee3b024d9)
![Screenshot 2024-09-15 165803](https://github.com/user-attachments/assets/0c8952fc-e4a5-40de-ae3f-c80227f5629f)

![Screenshot 2024-09-15 170125](https://github.com/user-attachments/assets/be72ca8c-9f41-42c8-a9b2-1efe69fc4d64)

**Comment by Tschipp** [comment]
sorry but this is impossible to debug

**Comment by CryoNine** [comment]
> sorry but this is impossible to debug

Dam oh well I'll just do the ol' "adding one mod at a time to find the problem child" method then
