### ISSUE TITLE
Crash on Create/Load Game - carryon-forge-1.21.1-2.2.2.11 (Forge 52.0.10 & 52.0.16)

### ISSUE THREAD

**Issue by Sweek9** [Tschipp/CarryOn#687]
### Expected Behavior
Game loads into world.

### Actual Behavior
Game crashes.

### Steps to Reproduce
Create/Load world in Singleplayer.

### Version of Minecraft, Carry On, Forge/Fabric
MC: 1.21.1
Carryon: 2.2.2.11
Forge: Both 52.0.10 & 52.0.16

### Screenshots encouraged
A screenshot would be pointless. Here's the crash log:
[crash-2024-09-18_14.16.22-client.txt](https://github.com/user-attachments/files/17050485/crash-2024-09-18_14.16.22-client.txt)

**Comment by micaj38** [comment]
Having the same issue, did you ever figure out the fix?
