### ISSUE TITLE
Carry on (Keybind problem)

### ISSUE THREAD

**Issue by NoobRobloxdev** [Tschipp/CarryOn#689]
### Expected Behavior
Dosnt work to grab anything (Even moded block)

### Actual Behavior
Does nothing

### Steps to Reproduce
I just go to the Carry on Keybind and i saw it a "B" key. i want to repear it but it dosnt work

### Version of Minecraft, Carry On, Forge/Fabric
Favric

### Screenshots encouraged
![image](https://github.com/user-attachments/assets/b9c6c362-43ed-4ea6-8df8-d6f5fe312f17)

**Comment by CryoNine** [comment]
I have the same problem

**Comment by Grigaber** [comment]
I had the same problem, I found out that that keybind is supposed to be for the crouch (aka. the thing you're supposed to press before right click), there is also problem when you bind crouch button to it you cant crouch. I set it to the side button on my mouse and it works now. You just need to press that button before right click.
Hope it helps you.

**Comment by CryoNine** [comment]
> I had the same problem, I found out that that keybind is supposed to be for the crouch (aka. the thing you're supposed to press before right click), there is also problem when you bind crouch button to it you cant crouch. I set it to the side button on my mouse and it works now. You just need to press that button before right click. Hope it helps you.

Sadly this one didn't work for me :( The mod just doesn't work at all

**Comment by Tschipp** [comment]
If you just reset it, it works by crouching and right clicking. It is always in combination with a right click.
