### ISSUE TITLE
Mob Spawners can be moved by default

### ISSUE THREAD

**Issue by Cyprex** [Tschipp/CarryOn#69]
Mob spawners can be moved by default, allowing easy mob grinders, especially with mods like Twilight Forest or Roguelike Dungeons that make spawners a lot more.
![2018-01-09_20 31 11](https://user-images.githubusercontent.com/35031555/34908473-5e149c4c-f890-11e7-89b1-f91472d3c788.png)

**Comment by Tschipp** [comment]
That's right, this is intended. If you want to make it impossible to pick up spawners, you can add them to the blacklist.
