### ISSUE TITLE
Mod is simply not working on our TerraFirmaGreg Modpack Server

### ISSUE THREAD

**Issue by mcbro12345** [Tschipp/CarryOn#690]
### Expected Behavior

For it to work on the server.
### Actual Behavior
It works in Singleplayer, but not on the server. Same set of mods for both, the modpack has not been edited.

### Steps to Reproduce
Install TerraFirmaGreg 1.20.1 on a server and attempt to use CarryOn

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 Forge

We are assuming that there is some sort of config file that needs to be updated in the server files. Though we cannot find any such thing other than the normal config file and it is identical to our client side configs for the mod.

**Comment by Tschipp** [comment]
I have no clue, "not working" is not exactly descriptive, sorry.
