### ISSUE TITLE
A glitch I found while testing out a modpack

### ISSUE THREAD

**Issue by JonklerLaugh** [Tschipp/CarryOn#695]
I made a custom Minecraft modpack and was testing out one of the features by looking straight down, crouching, and right-clicking, but for some reason, a pig with a saddle spawned in my arms. The version was 1.21.1, and I don't know if it was this mod that caused it, but yea

**Comment by dandalous** [comment]
If you use the Vanilla Refresh mod/datapack, there's a setting that lets you sit anywhere. It does this by spawning a pig with a saddle below where you want to sit. CarryOn lets you pick up this entity. Disable this in the Vanilla Refresh config menu `/function vanilla_refresh:_settings` (must have cheats on which you can do with Open to LAN > Enable Cheats), or blacklist the pig with a saddle entity from being able to be carried in CarryOn
