### ISSUE TITLE
Carry On Mod for Minecraft 1.21.1 Forge Crashes game on loading.

### ISSUE THREAD

**Issue by SebastianWood1** [Tschipp/CarryOn#696]
### Expected Behavior
I am expecting the game to load as normal with the new mod I added.
Also expect keybind to show up in menu
### Actual Behavior
The game continues to crash each time I load it since this mod has been added. 
Keybind does not show in menu.
### Steps to Reproduce
add the mod to game and load it, it will crash while loading, normally after going full screen or loading world.

### Version of Minecraft, Carry On, Forge/Fabric
1.21.1 forge

**Comment by Lux-pogu** [comment]
same thing sorta happened to me,fabric. I plopped the mod in my mods folder,loaded up my world that I've had for over a year,and it corrupted the shit. I was able to get the items that were in my inventory back,but lost everything in the world. it was just default seed again. last time I use this mod.

**Comment by Tschipp** [comment]
I need to see a log
