### ISSUE TITLE
1.21.3 update

### ISSUE THREAD

**Issue by vico93** [Tschipp/CarryOn#698]
Unfortunately seems like the latest version (2.2.2) of CarryOn doesn't work with 1.21.3 (and perharps 1.21.2).

[Here](https://gist.github.com/vico93/43ceb740e26911c58cb8a5a3e92ec682)'s the crash that happens when i tried to load the game with CarryOn included.

@Tschipp

**Comment by Talvysh** [comment]
There is no 1.21.3 update...

**Comment by vico93** [comment]
> There is no 1.21.3 update...

I know. I was just letting him aware that 2.2.2 wasnt compatible with 1.21.3/4

**Comment by Tschipp** [comment]
This is done now, 1.21.4 coming soon
