### ISSUE TITLE
Cant put a sunflower stem back down

### ISSUE THREAD

**Issue by cherry-blossom-02** [Tschipp/CarryOn#702]
So I have accidentally picked up a sunflower stem before and the times it's happened before I just offed myself in-game and respawned and that worked to get rid of it but now for some reason when I do that it is still there when I respawn and I have tried so many times and I have no clue what to do, I cannot for the life of me put it down and it is stressing me out and I can't do anything else besides walking and jumping while it is in my hands, I really love this world and have worked hard on it, if anyone can offer a solution or any ideas to solve this issue it would be greatly appreciated. 
### Screenshots 
![Better MC  FABRIC  1 20 1 11_3_2024 1_18_14 AM](https://github.com/user-attachments/assets/a7ad4845-8468-4cc0-9874-e6fc56cc52f0)
![Better MC  FABRIC  1 20 1 11_3_2024 1_18_02 AM](https://github.com/user-attachments/assets/af9272f8-40a3-4e57-9310-96df537ce485)

**Comment by Tschipp** [comment]
do /carryon clear
