### ISSUE TITLE
Won't load world with Carry on (1.21.1)

### ISSUE THREAD

**Issue by ath0rus** [Tschipp/CarryOn#703]
**Minecraft Version:** 1.21.1
**Forge Version:** 52.0.24
**Java Version:** 21.0.5 

**Issue:** Game crashes with ClassCastException in CarryOnDataManager.getCarryData when loading a save. The error appears to be related to casting ServerPlayer objects.

**Error Message:**
`java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class tschipp.carryon.common.carry.CarryOnDataManager$ICarrying
	at tschipp.carryon.common.carry.CarryOnDataManager.getCarryData(CarryOnDataManager.java:33)
	at tschipp.carryon.CarryOnCommon.onCarryTick(CarryOnCommon.java:102)
	at tschipp.carryon.events.CommonEvents.onServerTick(CommonEvents.java:182)
`

**Mod List:**

- Entity Texture Features: 6.2.5
- Fast IP Ping: 1.0.5
- Double Doors: 5.9
- Mouse Tweaks: 2.26
- Keep Some Inventory: 1-v2.0.1
- Open Parties and Claims: 0.23.2
- No Chat Reports: 1.21.1-v2.9.0
- Chunky: 1.4.16
- Just Enough Items (JEI): 19.21.0.247
- FirstPerson: 2.4.5
- Dynamic Lights (Dynamic Torches): 5.1
- Ksyxis: 1.3.2
- Forge Config API Port: 21.1.1
- WTHIT: 12.4.2
- NotEnoughAnimations: 1.7.6
- Xaero's Minimap: 24.6.1
- Collective: 7.87
- Clumps: 19.0.0.1
- Xaero's World Map: 1.39.0
- Controlling: 19.0.3
- Searchables: 1.0.2
- Bad Packets: 0.8.1
- EntityCulling: 1.7.1
- MixinExtras: 0.4.0
- CoroUtil: 1.21.0-1.3.7
- WaveyCapes: 1.4.10
- Dynamic FPS: 3.7.6
- Dismount Entity: 3.5
- Carry On: 2.2.2
- BetterF3: 11.0.2
- What Are They Up To: 1.21.0-1.1.3
- BetterThanMending: 2.2.0
- 3D Skin Layers: 1.7.0
- Cloth Config v14 API: 15.0.140
- Simple Voice Chat: 1.21.1-2.5.25
- Sound Physics Remastered: 1.4.6

**Steps to Reproduce:**

1. Launch Minecraft with the above mod list.
2. Load the save file.
3. The game crashes with a ClassCastException immediately on load.

**Troubleshooting:**

- Removed Carry On, and the crash stops, confirming this mod as the cause.
- Tried disabling mods related to entity handling, such as Entity Texture Features, Entity Culling, and NotEnoughAnimations, but the issue persists with Carry On enabled.
Disabling CoroUtil and Dynamic FPS did not resolve the issue, so these are likely not direct causes.
- Disabled every mod except Carry On, issues still persist

**Log FIle**:
[---- Minecraft Crash Report ----.txt](https://github.com/user-attachments/files/17610268/----.Minecraft.Crash.Report.----.txt)

**Comment by niki142009** [comment]
this also: "
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class tschipp.carryon.common.carry.CarryOnDataManager$ICarrying (net.minecraft.client.player.LocalPlayer is in module minecraft@1.21.1 of loader 'TRANSFORMER' @3fcee3d9; tschipp.carryon.common.carry.CarryOnDataManager$ICarrying is in module carryon@2.2.2 of loader 'TRANSFORMER' @3fcee3d9) "
i didnt had any other mod
