### ISSUE TITLE
Issue with Moving and Opening Loot Chests in Minecraft 1.21 with Lootr and Carry On Mods

### ISSUE THREAD

**Issue by JebsApple** [Tschipp/CarryOn#705]
### Expected Behavior
In previous versions (Minecraft 1.20.1), we could use the "Lootr" mod along with "Carry On" to pick up loot chests from structures and bring them back to our base. There, other players who didn’t join the expedition could open these chests and get the loot.

### Actual Behavior
In the current version (Minecraft 1.21, Fabric 0.16.0), when attempting to replicate this behavior, two issues occurred:
1. My teammate could not pick up any mobs, chests, chests with minecarts, etc., using the "Carry On" mod. This issue was resolved after a while by changing some key binds, but I’m not sure if that’s the reason it was fixed. I suggest improving the user’s ability to select buttons for picking up items in the game.

2. After bringing loot chests back to base, my teammate tried to open them, but they would instantly close. When I tried opening them myself, the same issue occurred. This problem only affects loot chests naturally generated in structures, while minecart chests in mineshafts can still be opened without issue.

### Steps to Reproduce
1. In Minecraft 1.21, Fabric 0.16.0, load the "Lootr" and "Carry On" mods.
2. Use "Carry On" to try picking up and moving loot chests from naturally generated structures.
3. Attempt to open these chests in a new location after moving them.

### Version of Minecraft, Carry On, Forge/Fabric
- Minecraft: 1.21
- Fabric: 0.16.0
- Lootr: lootr-fabric-1.21.1-10.1.3
- Carry On: carryon-fabric-1.21-2.2.1

**Comment by alexpeinado-png** [comment]
How are the key bindings called? I can't do anything with the mod I'm playing on the 1.21 version of minecraft. Whe I tried to load the mod again I couldn't due to incorrect modloader, when I'm filtering only fabric mods. Help please, I beg your help.

**Comment by JebsApple** [comment]
> How are the key bindings called? I can't do anything with the mod I'm playing on the 1.21 version of minecraft. Whe I tried to load the mod again I couldn't due to incorrect modloader, when I'm filtering only fabric mods. Help please, I beg your help.

It's really not necessary to set up any key bind; you should be able to pick up animals, chests, and spawners without any problem by shift + right-clicking.

**Comment by JebsApple** [comment]
I finally discovered that the error was coming from lootr.

**Comment by alexpeinado-png** [comment]
Will it work if I try with Fabric 0.16.7? I do not know much about modding, simple things.
