### ISSUE TITLE
Carry on Villager does not work 

### ISSUE THREAD

**Issue by ZFHailey** [Tschipp/CarryOn#709]
### Expected Behavior
Crouch Right click to pick up a full grown villager

### Actual Behavior
Crouch Right click, nothing (no response)

### Steps to Reproduce
As above. 

### Version of Minecraft, Carry On, Forge/Fabric
Mod Ver. 1.12.2-1.12.7.23 | Forge | Minecraft: 1.12.2 | Modpack: RLCraft

Pretty sure this just does NOT work for me. Even with the correct settings as i've basically looked it up. It might just be me tbh. 
![image](https://github.com/user-attachments/assets/e054065e-92ac-4564-bb92-10af786babc3)

**Comment by Tschipp** [comment]
RL craft has that disabled I think
