### ISSUE TITLE
Crashing Servers with boats 

### ISSUE THREAD

**Issue by WD40503** [Tschipp/CarryOn#712]
### Expected Behavior
put boat on dragon so i can carry on a villager in the boat, and drive the boat to drive the dragon (mythic mounts mod)

### Actual Behavior
server cant handle boat on dragon = crash as soon as a player loads in, permanently

### Steps to Reproduce
craft boat, carry on, right click dragon

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1 minecraft, 2.1.2.7 Carry On, 0.16.9 Fabric, 1.20.1-7.4 mythic mounts

### Screenshots encouraged
none

**Comment by Tschipp** [comment]
This seems like a conflict of many sorts... but without any log or further information, I can't really do anything.
