### ISSUE TITLE
Would love to understand why this mod does not work with Feywild on 1.20.1

### ISSUE THREAD

**Issue by lSherozl** [Tschipp/CarryOn#719]
Is a forge mod: https://www.curseforge.com/minecraft/mc-mods/feywild

**Comment by lSherozl** [comment]
None of the mobs in that mod can be carried or interacted with

**Comment by Tschipp** [comment]
Multiple possibilities: Blacklisted by the author, the pack, entities being too large, hostile, etc. In any case, not a bug
