### ISSUE TITLE
Block parsing errors

### ISSUE THREAD

**Issue by Thyriel** [Tschipp/CarryOn#72]
### Actual Behavior
There's some hundred "block parsing errors" in the server logfile on startup caused by carryon

### Steps to Reproduce
fml-junk-earlystartup.log:
https://github.com/Thyriel/Minecraft-AEONS-dev-/blob/master/private/fml-junk-earlystartup.log
(sorry too big to upload on pastebin)

### Version of Minecraft, Carry On, Forge
MC: 1.12.2
Forge: forge-1.12.2-14.23.1.2604
CarryOn: 1.7.1

**Comment by Tschipp** [comment]
These errors are harmless and were fixed in the last version. Please reset your custom Model Overrides config section to the default
