### ISSUE TITLE
Can't carry full grown villagers

### ISSUE THREAD

**Issue by Aaron18-xd** [Tschipp/CarryOn#720]
### Expected Behavior
Right click and crouch to pick up full grown villager 

### Actual Behavior
no response

### Version of Minecraft, Carry On, Forge/Fabric
Mod version: carryon-1.16.5-1.15.6.24.jar, mc version 1.16.5, forge

**Comment by Tschipp** [comment]
To be able to pick up larger mobs, you need to set the maxEntityHeight in the config to something larger than 2, and smaller than 10. The config is located in CarryOn's server config (which is located inside of the world's serverconfig folder).

**Comment by ghost** [comment]
> To be able to pick up larger mobs, you need to set the maxEntityHeight in the config to something larger than 2, and smaller than 10. The config is located in CarryOn's server config (which is located inside of the world's serverconfig folder).

I dont have serverconfig where it is
