### ISSUE TITLE
Can't get whitelist to work.

### ISSUE THREAD

**Issue by Josral** [Tschipp/CarryOn#73]
### Expected Behavior
                 Expected to pick up blocks added to white list.

### Actual Behavior
                 Does not work.

### Steps to Reproduce
                 Turn on whitelist option. Add a couple of blocks such as dirt and vanilla crafting table and can not pick them up. The setting to pick up 'all' blocks works. And the default setting seems to work. Noticed I can pick up chests.

### Version of Minecraft, Carry On, Forge
                  Minecraft 1.12.2, Carry On 1.12.2 v1.7.1, and Forge 14.23.1.2604

**Comment by Tschipp** [comment]
can you send me your config file?

**Comment by Josral** [comment]
I have it set for 'all' blocks at the moment

[carryon.zip](https://github.com/Tschipp/CarryOn/files/1672242/carryon.zip)

**Comment by Josral** [comment]
had to zip it to select it. It wouldn't upload cfg.

**Comment by Josral** [comment]
Just tested some more. Apparently I have to have 'all' blocks and 'whitelist' activated. That gives me the behavior I want. 'All' blocks is limited to the whitelist. Can't pickup a crafting table on whitelist unless 'all' is turned on.
