### ISSUE TITLE
Please clarify licensing

### ISSUE THREAD

**Issue by alexbobp** [Tschipp/CarryOn#74]
Hello, I'd like to make sure it's clear what the licensing terms are for this mod.  On curseforge it has the LGPLv3 selected, but at the bottom of the description is a block of copyright terms that contradict the LGPL, and in the code repository I see no LICENSE file at all.

If I understand correctly, this is a bit of an awkward legal status because it's not clear that the source code itself is licensed under the LGPL, which makes it hard to consider it open source (as opposed to just a permissively licensed binary blob).

If this mod is intended to be LGPL, my advice is to remove the erroneous copyright block at the bottom of the cf description, or clarify that it applies to the official Carry On jars but not to derivative works, and also include a LICENSE.txt in the repository with the chosen license.

(If the intent is to keep anyone from re-using this code in a mod that is posted on another site, then you will want to remove the LGPL tag, but it would be sad if this ambitious mod can't be part of the growing open source mod ecosystem!)

**Comment by capnkirok** [comment]
Hey @alexbobp it should be LGPL, need to update git and the forum page, as you suggest. Will ping back when done.

**Comment by capnkirok** [comment]
Done.
