### ISSUE TITLE
Conflict with Ex Sartagine 1.12.2

### ISSUE THREAD

**Issue by ExcitedName** [Tschipp/CarryOn#77]
### Expected Behavior
To pick up an entity normally

### Actual Behavior
I have the mod Ex Sartagine. The mod utilizes a block to cause the vanilla furnace to create a multi-block structure when attached to the cooking range block. Don't ask me why but I decided to try an pick one up. Once picked up it looks like the image below and I am unable to place the block back down. If it were not for the problem with Player Storage that I just reported I would not have been able to open my inventory to remove the item. A world ender if not using any kind of back up mod. Ex Sartagine apparently turns the furnace into an air block. I love this mod by the way.

### Steps to Reproduce
Install Ex Sartagine. Place down a cooking range and place a furnace to the right of it. Pick up the multi-block component that the furnace turned into.

### Version of Minecraft, Carry On, Forge
Minecraft 1.12.2
forge-1.12.2-14.23.2.2611-universal
CarryOn+MC1.12.2+v1.7.2

### Screenshots encouraged
![2018-02-21_22 24 34](https://user-images.githubusercontent.com/17900146/36524815-4c695c90-175c-11e8-8a38-d92003a02099.png)

![2018-02-21_23 03 48](https://user-images.githubusercontent.com/17900146/36524824-563cc5e0-175c-11e8-8332-e7f44148dba7.png)

**Comment by ExcitedName** [comment]
Well, now I feel silly. Checking a mod page for supporting commands is usually the first thing I do. I ran into a roadblock as far as the exact name for the blacklist is concerned. I tried blacklisting it myself. The multiblock doesn't show up via Hwyla. So I opened the jar to locate the .class and .lang files. There is no reference to it in the .lang. The best I can do is give you the unlocalized name, TileEntityRangeExtension, since the mod uses a vanilla furnace as the multiblock and seems to turn it into an air block with NBT data. If you have any other ideas that I can test just let me know and I'd be happy to help.

**Comment by Tschipp** [comment]
Haha just press F3 and hover over the block!

**Comment by ExcitedName** [comment]
*Palms face* lol, I have been playing MC for like 6 years now, 3 on PC. There always seems to be a million and one little things I have overlooked or was just clueless about, lol. The block is called exsartagine:range_extended. I manually blacklisted it to no avail. I dig your clear command though. super convenient.
