### ISSUE TITLE
Charset's barrels and Storage Drawers' drawers keep original rotation prior to being picked up

### ISSUE THREAD

**Issue by stohun01** [Tschipp/CarryOn#78]
### Expected Behavior
the front of the block be facing you when placed. How chests behave.

### Actual Behavior
rotation is the same as before it was picked up

### Version of Minecraft, Carry On, Forge
MC: 1.12.2
CO: 1.7.2
F: 14.23.2.2619

**Comment by Tschipp** [comment]
That's on charset and storage drawers. If they don't store their Rotation with vanilla's rotation blockstates, carry on can't rotate them
