### ISSUE TITLE
Using Skyresources:Enderium Casing with Enderium Combustion Heater,Shift+ Right ,cant pick up,but my heater disappeared

### ISSUE THREAD

**Issue by Taokyla** [Tschipp/CarryOn#79]
### Expected Behavior
put the Enderium Combustion Heater in to the Enderium Casing , shift + righe click rhe casing 
and the heater disapper
### Version of Minecraft, Carry On, Forge
mc:1.12.2
forge:14.23.2.2616
carry on:1.7.2
### Screenshots encouraged
![image](https://user-images.githubusercontent.com/10359761/36933174-b0359bc0-1f0f-11e8-946f-9da3594ef47a.png)

**Comment by Tschipp** [comment]
Which mod is this from?

**Comment by Taokyla** [comment]
Skyresources,a skyland like mod
