### ISSUE TITLE
Sponge and Carry On + ftbLib on forge crash when interacting with chest right button + arms

### ISSUE THREAD

**Issue by ternsip** [Tschipp/CarryOn#80]
https://gist.github.com/ternsip/68ba1de78f56ff792c15702bc80ea72f
Sponge and Carry On+ ftbLib forge crash when interacting with chest
I'm trying to pick chest with arms and sponge crushes
[ftb](https://github.com/LatvianModder/FTBUtilities/issues/652)
[sponge](https://github.com/SpongePowered/SpongeForge/issues/2033)

**Comment by ternsip** [comment]
CarryOn+MC1.12.2+v1.7.1.jar
FTBLib-4.2.5.jar
FTBUtilities-4.2.4.jar

**Comment by Tschipp** [comment]
Yeah your carry on version is outdated.
