### ISSUE TITLE
[Bug] Picking up Lead Knot

### ISSUE THREAD

**Issue by Deshiba** [Tschipp/CarryOn#82]
### Expected Behavior
To break the lead knot

### Actual Behavior
The lead knot is picked up when shift right clicking

### Steps to Reproduce
Tie an entity to a fence to create a lead knot. Shift right click the knot.

### Version of Minecraft, Carry On, Forge
mc 1.12.
CO: 1.7

### Screenshots encouraged
![2018-03-04_06 08 17](https://user-images.githubusercontent.com/10565800/36942471-d93d636e-1f72-11e8-9b21-c46a6dc437de.png)

**Comment by Tschipp** [comment]
Oops. adding it to default blacklist
