### ISSUE TITLE
Cannot pick up Bag opener block

### ISSUE THREAD

**Issue by Steveyg101** [Tschipp/CarryOn#83]
### Expected Behavior
picked up using Shift right click

### Actual Behavior
Error given, contents deleted

### Steps to Reproduce
Shift right click to pick up block

### Version of Minecraft, Carry On, Forge
Modern skyblock 3 - 1.12.2

**Comment by Tschipp** [comment]
Which mod is this from?

**Comment by Steveyg101** [comment]
Oops forgot to add that didn't I lol, its loot bags: https://minecraft.curseforge.com/projects/lootbags

**Comment by Steveyg101** [comment]
Also to add, loving the mod, its such a good idea!
