### ISSUE TITLE
[Compatibility] Duplication Bug when pickup PrimalCore Cauldron with Carry-On

### ISSUE THREAD

**Issue by Fireztonez** [Tschipp/CarryOn#88]
When I take the PrimalCore Cauldron with Carry-on, a Cauldron falls to the ground, as if I was mining it, and I have the original in my hand ... So it is really easy to reproduce it in infinite quantity in a few seconds !

For sure, I can blacklist the pickup cauldron by Carry-On, but I think it's really helpful to pick up the cauldron when there is a liquid in it.

I just test that with a new pack with only PrimalCore, Carry-On and JEI install, and the same bug appen.

Minecraft: 1.12.2
Primal-Core : 0.6.41
Carry-On: 1.7.2
Forge 14.23.2.2632

I was already bugging on PrimalCore's issue tracker, but I was not sure which mod was really involved, so I preferred to report it here too.
https://github.com/An-Sar/PrimalCore/issues/158

Fireztonez

**Comment by Tschipp** [comment]
I’m gonna see what I can do about it.
