### ISSUE TITLE
CarryOn mod VS PlaceableItems mod

### ISSUE THREAD

**Issue by ano19920** [Tschipp/CarryOn#9]
I love this mod but I also love the PlaceableItems mod and I hope that this is an easy-to-fix bug.

https://pastebin.com/w20eSJxV

**Comment by Tschipp** [comment]
I can only quote the crash report "But It works on my machine"... What item did you try and pick up?

**Comment by ano19920** [comment]
I placed down a pumpkin pie, and it became the 3D model. When i picked it up, it crashed the game. I couldn't see if the block was even picked up, or purple. When I say purple, I am mentioning that there are some weird rendering issues with textures on some vanilla blocks and then blocks from ConquestMod, but the "purple boxes" only happen in 3rd person view. I'm not exactly bothered by that, it's "harmless."

Should I try to pick up some different PlaceableItems 3D models?

**Comment by Tschipp** [comment]
Yeah, try some other items, they all seem to work for me: https://i.gyazo.com/9e37f9040d597bcb90033398f809c2e9.gif

Then again, I have a never version, but I don't think I changed anything...

You can manually override the models, example on the wiki: https://github.com/Tschipp/CarryOn/wiki/Model-Override-Config
(So for your case it would look like this for an apple: placeableitems:block_apple->minecraft:apple
It's sadly not possible for the mod to automatically get the correct models.

Can you specify with which vanilla blocks you were having rendering issues with?

**Comment by ano19920** [comment]
Okay, I WAS having vanilla block issues, but I just figured out why that may be happening. All the vanilla blocks I picked up rendered fine-----until I picked up a Conquest block. The Conquest block rendered, but then any vanilla block I picked up afterwards was doing the purple thing. So I logged off the map and got back on, and the vanilla blocks were working fine again. I think some of these issues could be connected to Conquest...

I placed a water bucket down but it crashed the game as soon as I tried to pick it up. Would you like to see that crash log, too?

**Comment by Tschipp** [comment]
yeah, sure :)

**Comment by ano19920** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CAFMLPlugin ([1.10]CraftableAnimals v2.6.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.8.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.2.jar)
  llibrary (llibrary-1.7.6-1.10.2.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/16/17 3:30 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tschipp.carryon.common.item.ItemTile.storeTileData(ItemTile.java:186)
	at tschipp.carryon.common.event.ItemEvents.onBlockRightClick(ItemEvents.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_ItemEvents_onBlockRightClick_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:387)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at tschipp.carryon.common.item.ItemTile.storeTileData(ItemTile.java:186)
	at tschipp.carryon.common.event.ItemEvents.onBlockRightClick(ItemEvents.java:102)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_ItemEvents_onBlockRightClick_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:387)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Melinani'/822241, l='MpServer', x=-224.44, y=4.00, z=183.53]]
	Chunk stats: MultiplayerChunkCache: 1555, 1555
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-212,4,191), Chunk: (at 12,0,15 in -14,11; contains blocks -224,0,176 to -209,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4940 game time, 5940 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [MoCEntityButterfly['ButterFly'/822156, l='MpServer', x=-312.50, y=4.00, z=304.50], MoCEntityButterfly['ButterFly'/822157, l='MpServer', x=-299.50, y=4.00, z=125.50], MoCEntityButterfly['ButterFly'/822158, l='MpServer', x=-298.50, y=4.00, z=127.50], MoCEntityButterfly['ButterFly'/822159, l='MpServer', x=-297.20, y=4.00, z=128.59], MoCEntityButterfly['ButterFly'/822152, l='MpServer', x=-326.50, y=4.00, z=276.50], MoCEntityButterfly['ButterFly'/822153, l='MpServer', x=-318.19, y=4.00, z=300.46], MoCEntityButterfly['ButterFly'/822154, l='MpServer', x=-315.50, y=4.00, z=303.50], MoCEntityButterfly['ButterFly'/822155, l='MpServer', x=-313.50, y=4.00, z=307.50], MoCEntityButterfly['ButterFly'/822149, l='MpServer', x=-321.50, y=4.00, z=278.50], MoCEntityButterfly['ButterFly'/822150, l='MpServer', x=-325.50, y=4.00, z=276.50], MoCEntityButterfly['ButterFly'/822151, l='MpServer', x=-328.50, y=4.00, z=277.50], MoCEntityButterfly['ButterFly'/822172, l='MpServer', x=-283.50, y=4.00, z=266.50], MoCEntityButterfly['ButterFly'/822173, l='MpServer', x=-283.50, y=4.00, z=266.50], MoCEntityButterfly['ButterFly'/822174, l='MpServer', x=-282.50, y=4.00, z=269.50], MoCEntityButterfly['ButterFly'/822175, l='MpServer', x=-270.50, y=4.00, z=150.50], MoCEntityButterfly['ButterFly'/822168, l='MpServer', x=-272.37, y=4.00, z=152.38], MoCEntityButterfly['ButterFly'/822169, l='MpServer', x=-286.48, y=4.00, z=257.42], MoCEntityButterfly['ButterFly'/822170, l='MpServer', x=-285.50, y=4.00, z=254.50], MoCEntityButterfly['ButterFly'/822171, l='MpServer', x=-286.50, y=4.00, z=264.50], MoCEntityButterfly['ButterFly'/822164, l='MpServer', x=-291.50, y=4.00, z=147.50], MoCEntityButterfly['ButterFly'/822165, l='MpServer', x=-294.50, y=4.00, z=250.50], MoCEntityButterfly['ButterFly'/822166, l='MpServer', x=-289.50, y=4.00, z=252.50], MoCEntityButterfly['ButterFly'/822167, l='MpServer', x=-276.86, y=4.00, z=149.64], MoCEntityButterfly['ButterFly'/822160, l='MpServer', x=-299.50, y=4.00, z=128.50], MoCEntityButterfly['ButterFly'/822161, l='MpServer', x=-294.56, y=4.00, z=150.30], MoCEntityButterfly['ButterFly'/822162, l='MpServer', x=-295.50, y=4.00, z=146.50], MoCEntityButterfly['ButterFly'/822163, l='MpServer', x=-292.50, y=4.00, z=144.50], MoCEntityButterfly['ButterFly'/822188, l='MpServer', x=-154.79, y=4.00, z=96.47], MoCEntityButterfly['ButterFly'/822189, l='MpServer', x=-133.50, y=4.00, z=296.50], MoCEntityButterfly['ButterFly'/822190, l='MpServer', x=-136.50, y=4.00, z=293.50], MoCEntityButterfly['ButterFly'/822191, l='MpServer', x=-134.50, y=4.00, z=296.50], MoCEntityButterfly['ButterFly'/822184, l='MpServer', x=-156.50, y=4.00, z=100.50], MoCEntityButterfly['ButterFly'/822185, l='MpServer', x=-154.52, y=4.00, z=101.71], MoCEntityButterfly['ButterFly'/822186, l='MpServer', x=-155.47, y=4.00, z=98.54], MoCEntityButterfly['ButterFly'/822187, l='MpServer', x=-158.50, y=4.00, z=97.50], MoCEntityButterfly['ButterFly'/822180, l='MpServer', x=-194.54, y=4.00, z=139.56], MoCEntityButterfly['ButterFly'/822181, l='MpServer', x=-160.50, y=4.00, z=92.50], MoCEntityButterfly['ButterFly'/822182, l='MpServer', x=-157.50, y=4.00, z=92.50], MoCEntityButterfly['ButterFly'/822183, l='MpServer', x=-151.50, y=4.00, z=94.50], MoCEntityButterfly['ButterFly'/822176, l='MpServer', x=-271.50, y=4.00, z=149.50], MoCEntityButterfly['ButterFly'/822177, l='MpServer', x=-214.50, y=4.00, z=128.50], EntityPlayerSP['Melinani'/822241, l='MpServer', x=-224.44, y=4.00, z=183.53], MoCEntityButterfly['ButterFly'/822178, l='MpServer', x=-209.09, y=4.00, z=130.02], MoCEntityButterfly['ButterFly'/822179, l='MpServer', x=-216.41, y=4.00, z=159.31], MoCEntityButterfly['ButterFly'/822192, l='MpServer', x=-135.50, y=4.00, z=301.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1295545072 bytes (1235 MB) / 3306938368 bytes (3153 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D7 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAAAAAAA	backpacks16840{3.1.5} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.5.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAAAAAAA	forgecreeperheal{2.0.1} [Forge Creeper Heal 2.0.1] ([1.10.2]ForgeCreeperHeal-2.0.1.jar) 
	UCHIJAAAAAAAAA	CraftableAnimals{2.6.1} [Craftable Animals] ([1.10]CraftableAnimals v2.6.1.jar) 
	UCHIJAAAAAAAAA	AppleCore{2.2.0} [AppleCore] (AppleCore-mc1.10.2-2.2.0.jar) 
	UCHIJAAAAAAAAA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.10.2-1.0.7.jar) 
	UCHIJAAAAAAAAA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJAAAAAAAAA	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCHIJAAAAAAAAA	badmobs{1.2.0.17} [Bad Mobs] (BadMobs-1.10.2-1.2.0.17.jar) 
	UCHIJAAAAAAAAA	betterfoliage{2.1.8} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.8.jar) 
	UCHIJAAAAAAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJAAAAAAAAA	carryon{1.1.1} [Carry On] (CarryOn MC1.10.2 v1.1.1.jar) 
	UCHIJAAAAAAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAAAAAAA	conquest{2.1.2} [Conquest Reforged] (ConquestReforged-2.1.2-mc1.10.2.jar) 
	UCHIJAAAAAAAAA	blockpalette{1.4.1} [BlockPalette] (ConquestReforged-2.1.2-mc1.10.2.jar) 
	UCHIJAAAAAAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(25may17).jar) 
	UCHIJAAAAAAAAA	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
	UCHIJAAAAAAAAA	Ding{MC1.9.0v2} [Ding] (Ding-1.10.2-1.0.0.jar) 
	UCHIJAAAAAAAAA	doggytalents{v1.11.1g} [Doggy Talents] (DoggyTalents-1.10.2-v1.11.1g-universal.jar) 
	UCHIJAAAAAAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJAAAAAAAAA	dsurround{3.4.6.2} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.6.2.jar) 
	UCHIJAAAAAAAAA	presets{3.4.6.2} [§3Presets!] (DynamicSurroundings-1.10.2-3.4.6.2.jar) 
	UCHIJAAAAAAAAA	flowercraftmod{6.01} [Flowercraft] (Flowercraftmod v6.01 - MC1.10.2 Forge.jar) 
	UCHIJAAAAAAAAA	samsfooddetails{1.0.1} [Food Details] (FoodDetails-1.10.2-1.0.1.jar) 
	UCHIJAAAAAAAAA	guideBook{1.6.1} [Guide Book] (GuideBook-1.6.3.jar) 
	UCHIJAAAAAAAAA	HungerInPeace{1.0.0} [Hunger In Peace] (HungerInPeace-mc1.9.4-1.0.0.jar) 
	UCHIJAAAAAAAAA	InventoryPets{1.4.9.6} [Inventory Pets] (inventorypets-1.10-1.4.9.6.jar) 
	UCHIJAAAAAAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.10.2.jar) 
	UCHIJAAAAAAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAAAAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAAAAAAA	minecolonies{@VERSION@} [MineColonies] (minecolonies-universal-1.10.2-0.8.3433.jar) 
	UCHIJAAAAAAAAA	MoreCommands{1.0.0} [MoreCommands] (MoreCommands_1.7.1.1102.jar) 
	UCHIJAAAAAAAAA	morefuelsmod-1.10.x{1.6.0} [More Fuels Mod] (morefuelsmod-1.10.x-1.6.0.jar) 
	UCHIJAAAAAAAAA	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(16jul17).jar) 
	UCHIJAAAAAAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAAAAAAA	placeableitems{3.0.4} [Placeable Items Mod] (placeableitems-3.0.4.jar) 
	UCHIJAAAAAAAAA	guilib{1.0.7.2} [GUI Library] (PSG Revamped-1.10.2-1.0.0.0.jar) 
	UCHIJAAAAAAAAA	paintingselgui{1.7.2.0} [PaintingSelectionGui] (PSG Revamped-1.10.2-1.0.0.0.jar) 
	UCHIJAAAAAAAAA	stacksize{1.3} [Stacksize Mod] (stacksize-1.10.2-1.3.jar) 
	UCHIJAAAAAAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCHIJAAAAAAAAA	vending{1.4.3} [Vending] (vending-1.10.2-1.4.3.jar) 
	UCHIJAAAAAAAAA	XaeroMinimap{1.13.5} [Xaero's Minimap] (Xaeros_Minimap_1.13.5_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
CAFMLPlugin ([1.10]CraftableAnimals v2.6.1.jar)
  naruto1310.craftableAnimals.vanilla.CATransformer
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.8.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  cubex2.cxlibrary.CoreModTransformer
AppleCore (AppleCore-mc1.10.2-2.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
llibrary (llibrary-1.7.6-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  brad16840.common.asm.ClassTransformer
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2316
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1RPGWonderland.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 20
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ano19920** [comment]
Oh, sorry! I forgot to mention it but I'm on 1.10.2! It's in the logs but I noticed the label said 1.11.2...

**Comment by Tschipp** [comment]
Well, that means you're using the wrong version

**Comment by ano19920** [comment]
But I'm on 1.10.2 using "CarryOn MC1.10.2 v1.1.1"... it is the latest file released for 1.10.2...

**Comment by Tschipp** [comment]
Nevermind my comment, I see now

**Comment by ano19920** [comment]
Should I try to grab anymore blocks or do you think you have what you need to check out?

**Comment by Tschipp** [comment]
I think this will do, thanks

**Comment by Tschipp** [comment]
Fixed it! Will not do a hotfix though, avoid using it for placed items for now. The fix will be in the next release.

**Comment by ano19920** [comment]
Thank you!! <3
