### ISSUE TITLE
Error when picking up Cabinet from Rustic

### ISSUE THREAD

**Issue by randomlypickedname** [Tschipp/CarryOn#91]
### Expected Behavior
Expected to pick up a cabinet from the Rustic mod to place one block over

### Actual Behavior
Errored, emptied cabinet

### Steps to Reproduce
Attempt to pick up cabinet

### Version of Minecraft, Carry On, Forge
MC ver. 1.12.2, CarryOn ver. 1.8, Forge ver. 2635

**Comment by Somnioblivio** [comment]
Also getting Error when picking up Pot from Rustic... all same functionality as OP, posting comment here to save space. Guessing just need support for Rustic added? Love this mod BTW.... should be vanilla...
