### ISSUE TITLE
Quark Compat with Hotbar Selection

### ISSUE THREAD

**Issue by Vyraal1** [Tschipp/CarryOn#92]
### Expected Behavior
You can move carry-on tile items into your inventory if you have Quark installed (eg. SevTech Ages), allowing the player to pick up a spawner/chest/machine, etc. use Quark's hotbar feature to move the item into their inventory, and then proceed as normal with the item in their inventory.

### Steps to Reproduce
1. Pick up something with Carry On (such as a Mekanism Smelting Factory)
2. Use the Quark 'Hotbar Selection' keybind to switch your hotbar (and moving the Carry On tile to your inventoiry)
![image](https://user-images.githubusercontent.com/26587049/38456429-b74a2b52-3a52-11e8-9b26-6ece276d68be.png)
3. You can select the item normally, and move it with your mouse to your main hand anytime you want to drop it off again. 
![image](https://user-images.githubusercontent.com/26587049/38456449-d5a56184-3a52-11e8-8274-7cfc2405137c.png)

### Version of Minecraft, Carry On, Forge
Forge 2635
Minecraft: 1.12.2
Carry On: 1.8
Quark: r1.4-122

### Screenshots encouraged

![image](https://user-images.githubusercontent.com/26587049/38456355-01019c18-3a52-11e8-8b92-c471fb2e1a91.png)

**Comment by capnkirok** [comment]
Does Quark have a blacklist?

**Comment by capnkirok** [comment]
Ok, just checked. It does not. What we could do is check to see if the item is in the hotbar. If it's not in the hotbar (and instead in the main inventory), it can drop it in the real world (e.g., drop or place).

**Comment by Vyraal1** [comment]
That sounds definitely the cleanest option, just bringing this up because it definitely seem's like one of those mod interactions that goes against the 'spirit' of the mod. Although really, my other suggestion would be to have a config in carry-on that enables whether it checks if item is in inventory or not (so players could choose to use this interaction if it's more fun for them).
