### ISSUE TITLE
Error when picking up Gendustry machine

### ISSUE THREAD

**Issue by MatthiasMann** [Tschipp/CarryOn#93]
### Expected Behavior
Machine can be picked up or nothing should happen (eg no error)

### Actual Behavior
"Error detected. Cannot pick up block." And the power buffer of the Gendustry machine was cleared (Gentic Imprinter).

### Steps to Reproduce
Try to pickup a Gendustry mechine.

### Version of Minecraft, Carry On, Forge
forge-1.12.2-14.23.2.2654
CarryOn MC1.12.2 v1.8
gendustry-1.6.5.8-mc1.12.2

**Comment by capnkirok** [comment]
You can add this block to the Carry On blacklist in the config. See wiki: https://github.com/Tschipp/CarryOn/wiki/Black---and-Whitelist-Config

We can also add it to the default blacklist if it comes to that.
