### ISSUE TITLE
Carrying an Iron Chest with items inside always faces west when leaving

### ISSUE THREAD

**Issue by vpontin** [Tschipp/CarryOn#97]
### Expected Behavior
Placing the [iron chest](https://minecraft.curseforge.com/projects/iron-chests) it will face the player who place it (empty iron chests, vanilla chests and modded chests from [Features](https://minecraft.curseforge.com/projects/features) do that).

### Actual Behavior
The placed iron chest always faces west, no matter the direction the player are facing.

### Steps to Reproduce
* Create a iron chest;
* Place it;
* Put some items inside
* Carry the chest and place with you facing any direction - the chest will always face west

### Version of Minecraft, Carry On, Forge
* Minecraft 1.12.2;
* Forge b.2676;
* CarryOn 1.8
* [IronChests](https://github.com/progwml6/ironchest) 7.0.42.827

### Screenshots encouraged
Better than a screenshot, [here's a video](https://www.youtube.com/watch?v=dVZUSiSNujE) describing the issue.

**Comment by Tschipp** [comment]
This is a Problem that occurs when Blocks store their rotation in NBT and not in BlockStates. The same happens with Machines from AE2. Sadly there's nothing I can do about that.

**Comment by vpontin** [comment]
Reported on Ironchest side! Thanks!
